from datetime import datetime
from typing import Optional
import uuid
from sqlalchemy import Column, String, DateTime, Text, JSON, ForeignKey, Index, Numeric, Boolean
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
import enum

from app.database import Base


class RuleStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DEPRECATED = "DEPRECATED"


class RuleSeverity(str, enum.Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ALERT = "ALERT"
    CRITICAL = "CRITICAL"


class RuleTriggerType(str, enum.Enum):
    ON_ENCOUNTER_CREATE = "ON_ENCOUNTER_CREATE"
    ON_ENCOUNTER_UPDATE = "ON_ENCOUNTER_UPDATE"
    ON_DIAGNOSIS_ADD = "ON_DIAGNOSIS_ADD"
    ON_MEDICATION_ORDER = "ON_MEDICATION_ORDER"
    ON_LAB_ORDER = "ON_LAB_ORDER"
    ON_LAB_RESULT = "ON_LAB_RESULT"
    ON_VITALS_UPDATE = "ON_VITALS_UPDATE"
    MANUAL = "MANUAL"
    SCHEDULED = "SCHEDULED"


class MdClinicalRule(Base):
    """
    Clinical Rule Engine model.
    Defines clinical decision support rules for automated alerts and suggestions.
    """
    __tablename__ = "md_clinical_rule"

    rule_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    rule_code = Column(String(100), unique=True, nullable=False, index=True)
    rule_name = Column(String(255), nullable=False)
    rule_description = Column(Text)
    rule_category = Column(String(50), nullable=False, index=True)  # medication_safety, lab_alerts, vital_alerts, etc.
    rule_version = Column(String(20), default="1.0", nullable=False)
    status = Column(String(30), default=RuleStatus.DRAFT, nullable=False, index=True)
    severity = Column(String(20), default=RuleSeverity.INFO, nullable=False)
    trigger_type = Column(String(50), nullable=False, index=True)
    condition_expression = Column(JSONB, nullable=False, default={})  # Rule condition logic
    action_config = Column(JSONB, nullable=False, default={})  # Actions to take when rule triggers
    priority = Column(Numeric(3,0), default=5, nullable=False)  # 1-10, higher is more important
    specialty_profile_id = Column(UUID(as_uuid=True), ForeignKey("md_specialty_profile.specialty_profile_id"), nullable=True)
    facility_id = Column(UUID(as_uuid=True), ForeignKey("md_facility.facility_id"), nullable=True)
    requires_approval = Column(Boolean, default=False, nullable=False)
    auto_execute = Column(Boolean, default=False, nullable=False)
    created_by = Column(String(100), nullable=False)
    updated_by = Column(String(100), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    effective_from = Column(DateTime, nullable=True)
    effective_to = Column(DateTime, nullable=True)

    # Relationships
    specialty_profile = relationship("MdSpecialtyProfile", backref="clinical_rules")

    __table_args__ = (
        Index('idx_rule_status_category', 'status', 'rule_category'),
        Index('idx_rule_trigger_status', 'trigger_type', 'status'),
    )


class MdRuleExecution(Base):
    """
    Rule execution tracking model.
    Tracks when rules are executed and their outcomes.
    """
    __tablename__ = "md_rule_execution"

    execution_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    rule_id = Column(UUID(as_uuid=True), ForeignKey("md_clinical_rule.rule_id", ondelete="CASCADE"), nullable=False, index=True)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("md_patient.patient_id", ondelete="CASCADE"), nullable=False, index=True)
    encounter_id = Column(UUID(as_uuid=True), ForeignKey("md_encounter.encounter_id", ondelete="CASCADE"), nullable=True, index=True)
    trigger_event = Column(String(100), nullable=False)
    trigger_data = Column(JSONB, nullable=False, default={})
    execution_status = Column(String(30), nullable=False, index=True)  # TRIGGERED, SKIPPED, ERROR
    rule_matched = Column(Boolean, nullable=False, default=False)
    action_taken = Column(JSONB, nullable=False, default={})
    error_message = Column(Text, nullable=True)
    execution_time_ms = Column(Numeric(10,2), nullable=True)
    executed_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    # Relationships
    rule = relationship("MdClinicalRule", backref="executions")

    __table_args__ = (
        Index('idx_execution_patient_time', 'patient_id', 'executed_at'),
        Index('idx_execution_rule_time', 'rule_id', 'executed_at'),
    )


class MdRuleAlert(Base):
    """
    Rule alert model for displaying alerts to clinicians.
    Stores alerts generated by rule executions.
    """
    __tablename__ = "md_rule_alert"

    alert_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    execution_id = Column(UUID(as_uuid=True), ForeignKey("md_rule_execution.execution_id", ondelete="CASCADE"), nullable=False)
    rule_id = Column(UUID(as_uuid=True), ForeignKey("md_clinical_rule.rule_id", ondelete="CASCADE"), nullable=False)
    patient_id = Column(UUID(as_uuid=True), ForeignKey("md_patient.patient_id", ondelete="CASCADE"), nullable=False, index=True)
    encounter_id = Column(UUID(as_uuid=True), ForeignKey("md_encounter.encounter_id", ondelete="CASCADE"), nullable=True, index=True)
    alert_title = Column(String(255), nullable=False)
    alert_message = Column(Text, nullable=False)
    severity = Column(String(20), nullable=False, index=True)
    alert_type = Column(String(50), nullable=False)  # DRUG_INTERACTION, LAB_ALERT, VITAL_ALERT, etc.
    suggested_action = Column(Text, nullable=True)
    action_required = Column(Boolean, default=True, nullable=False)
    acknowledged = Column(Boolean, default=False, nullable=False)
    acknowledged_by = Column(String(100), nullable=True)
    acknowledged_at = Column(DateTime, nullable=True)
    dismissed = Column(Boolean, default=False, nullable=False)
    dismissed_by = Column(String(100), nullable=True)
    dismissed_at = Column(DateTime, nullable=True)
    expires_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    # Relationships
    execution = relationship("MdRuleExecution", backref="alerts")
    rule = relationship("MdClinicalRule", backref="alerts")

    __table_args__ = (
        Index('idx_alert_patient_status', 'patient_id', 'acknowledged', 'dismissed'),
        Index('idx_alert_severity_time', 'severity', 'created_at'),
    )


class MdRuleVariable(Base):
    """
    Rule variable model for defining reusable variables in rules.
    """
    __tablename__ = "md_rule_variable"

    variable_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    variable_name = Column(String(100), unique=True, nullable=False)
    variable_type = Column(String(50), nullable=False)  # string, number, boolean, date, list
    variable_value = Column(JSONB, nullable=False)
    description = Column(Text)
    category = Column(String(50), nullable=True)
    is_system = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
