ALTER TABLE inv_items ADD COLUMN IF NOT EXISTS hsn_code VARCHAR(20);
ALTER TABLE inv_items ADD COLUMN IF NOT EXISTS gst_percentage NUMERIC(5, 2) DEFAULT 0.0;
ALTER TABLE inv_items ADD COLUMN IF NOT EXISTS reorder_level NUMERIC(12, 2) DEFAULT 0.0;
ALTER TABLE inv_items ADD COLUMN IF NOT EXISTS is_approved BOOLEAN DEFAULT TRUE;
