import json
import os

locales_dir = "frontend/src/i18n/locales"

translations = {
    "en": {
        "newOrder": "New Order",
        "stepXof3": "Step {x} of 3",
        "selectOrderType": "Select Order Type",
        "chooseTheCategoryForThisClinic": "Choose the category for this clinical order",
        "priority": "Priority",
        "addOrderItems": "Add Order Items",
        "searchOrUseVoiceToAddTestsMedi": "Search or use voice to add tests, medications, or procedures",
        "searchingCatalog": "Searching catalog...",
        "qty": "Qty",
        "clinicalNotesOptional": "Clinical Notes (Optional)",
        "reviewOrder": "Review Order",
        "confirmDetailsBeforeSubmission": "Confirm details before submission",
        "orderType": "Order Type",
        "orderItems": "Order Items",
        "clinicalNotes": "Clinical Notes",
        "thisOrderWillBeSentForApproval": "This order will be sent for approval depending on your permissions.",
        "back": "Back",
        "cancel": "Cancel",
        "next": "Next",
        "submitting": "Submitting...",
        "submitOrder": "Submit Order",
        "orderManagement": "Order Management",
        "phase4Subtitle": "Phase 4 — Enterprise Order Engine",
        "encounter": "Encounter",
        "patient": "Patient",
        "selectAnEncounterTitle": "Select an Encounter",
        "chooseActiveEncounterSubtitle": "Choose an active encounter to manage orders",
        "changeBtn": "Change",
        "selectEncounterBtn": "Select Encounter",
        "noEncounterSelected": "No Encounter Selected",
        "selectAnActiveEncounterToViewA": "Select an active encounter to view and manage orders.",
        "selectEncounter": "Select Encounter",
        "filterLabel": "Filter:",
        "allTypes": "All Types",
        "allStatuses": "All Statuses",
        "ordersCountLabel": "order(s)",
        "loadingOrders": "Loading orders...",
        "noOrdersFoundCreateTheFirstOrd": "No orders found. Create the first order above.",
        "searchTestsPlaceholder": "Search \"CBC\", \"Aspirin\", \"ECG\"...",
        "specialInstructionsPlaceholder": "Special instructions...",
        "additionalClinicalContextPlaceholder": "Additional instructions or clinical context...",
        "type_LAB_ORDER": "Lab Test",
        "type_MEDICATION_ORDER": "Medication",
        "type_RADIOLOGY_ORDER": "Imaging",
        "type_PROCEDURE_ORDER": "Procedure",
        "type_NURSING_TASK": "Nursing",
        "priority_ROUTINE": "Routine",
        "priority_URGENT": "Urgent",
        "priority_STAT": "STAT",
        "status_DRAFT": "Draft",
        "status_PENDING_APPROVAL": "Pending",
        "status_APPROVED": "Approved",
        "status_IN_PROGRESS": "In Progress",
        "status_COMPLETED": "Completed",
        "status_CANCELLED": "Cancelled",
        "tab_orders": "Orders",
        "tab_templates": "Templates",
        "tab_sets": "Order Sets",
        "orderTemplates": "Order Templates",
        "reusableOrderCombinationsForFa": "Reusable order combinations for faster workflows"
    },
    "hi": {
        "newOrder": "नया आदेश",
        "stepXof3": "चरण {x} / 3",
        "selectOrderType": "आदेश प्रकार चुनें",
        "chooseTheCategoryForThisClinic": "इस नैदानिक आदेश के लिए श्रेणी चुनें",
        "priority": "प्राथमिकता",
        "addOrderItems": "आदेश आइटम जोड़ें",
        "searchOrUseVoiceToAddTestsMedi": "परीक्षण, दवाएँ, या प्रक्रियाएँ जोड़ने के लिए खोजें या आवाज़ का उपयोग करें",
        "searchingCatalog": "कैटलॉग खोजा जा रहा है...",
        "qty": "मात्रा",
        "clinicalNotesOptional": "नैदानिक नोट्स (वैकल्पिक)",
        "reviewOrder": "आदेश की समीक्षा करें",
        "confirmDetailsBeforeSubmission": "सबमिट करने से पहले विवरण की पुष्टि करें",
        "orderType": "आदेश का प्रकार",
        "orderItems": "आदेश आइटम",
        "clinicalNotes": "नैदानिक नोट्स",
        "thisOrderWillBeSentForApproval": "यह आदेश आपकी अनुमतियों के आधार पर अनुमोदन के लिए भेजा जाएगा।",
        "back": "वापस",
        "cancel": "रद्द करें",
        "next": "अगला",
        "submitting": "सबमिट किया जा रहा है...",
        "submitOrder": "आदेश सबमिट करें",
        "orderManagement": "आदेश प्रबंधन",
        "phase4Subtitle": "चरण 4 — एंटरप्राइज ऑर्डर इंजन",
        "encounter": "मुठभेड़",
        "patient": "मरीज",
        "selectAnEncounterTitle": "एक मुठभेड़ चुनें",
        "chooseActiveEncounterSubtitle": "आदेश प्रबंधित करने के लिए एक सक्रिय मुठभेड़ चुनें",
        "changeBtn": "बदलें",
        "selectEncounterBtn": "मुठभेड़ चुनें",
        "noEncounterSelected": "कोई मुठभेड़ नहीं चुना गया",
        "selectAnActiveEncounterToViewA": "आदेश देखने और प्रबंधित करने के लिए एक सक्रिय मुठभेड़ चुनें।",
        "selectEncounter": "मुठभेड़ चुनें",
        "filterLabel": "फ़िल्टर:",
        "allTypes": "सभी प्रकार",
        "allStatuses": "सभी स्थितियां",
        "ordersCountLabel": "आदेश",
        "loadingOrders": "आदेश लोड हो रहे हैं...",
        "noOrdersFoundCreateTheFirstOrd": "कोई आदेश नहीं मिला। ऊपर पहला आदेश बनाएं।",
        "searchTestsPlaceholder": '"सीबीसी", "एस्पिरिन", "ईसीजी" खोजें...',
        "specialInstructionsPlaceholder": "विशेष निर्देश...",
        "additionalClinicalContextPlaceholder": "अतिरिक्त निर्देश या नैदानिक संदर्भ...",
        "type_LAB_ORDER": "लैब टेस्ट",
        "type_MEDICATION_ORDER": "दवा",
        "type_RADIOLOGY_ORDER": "इमेजिंग",
        "type_PROCEDURE_ORDER": "प्रक्रिया",
        "type_NURSING_TASK": "नर्सिंग",
        "priority_ROUTINE": "नियमित",
        "priority_URGENT": "तत्काल",
        "priority_STAT": "अति आवश्यक",
        "status_DRAFT": "प्रारूप",
        "status_PENDING_APPROVAL": "लंबित",
        "status_APPROVED": "स्वीकृत",
        "status_IN_PROGRESS": "प्रगति में",
        "status_COMPLETED": "पूरा",
        "status_CANCELLED": "रद्द",
        "tab_orders": "आदेश",
        "tab_templates": "टेम्पलेट",
        "tab_sets": "ऑर्डर सेट",
        "orderTemplates": "आदेश टेम्पलेट",
        "reusableOrderCombinationsForFa": "तेज़ कार्यप्रवाह के लिए पुन: प्रयोज्य आदेश संयोजन"
    },
    "mr": {
        "newOrder": "नवीन आदेश",
        "stepXof3": "पायरी {x} / 3",
        "selectOrderType": "आदेश प्रकार निवडा",
        "chooseTheCategoryForThisClinic": "या वैद्यकीय आदेशासाठी श्रेणी निवडा",
        "priority": "प्राधान्य",
        "addOrderItems": "आदेश आयटम जोडा",
        "searchOrUseVoiceToAddTestsMedi": "चाचण्या, औषधे किंवा प्रक्रिया जोडण्यासाठी शोधा किंवा आवाज वापरा",
        "searchingCatalog": "कॅटलॉग शोधत आहे...",
        "qty": "प्रमाण",
        "clinicalNotesOptional": "वैद्यकीय नोंदी (पर्यायी)",
        "reviewOrder": "आदेशाचे पुनरावलोकन करा",
        "confirmDetailsBeforeSubmission": "सबमिट करण्यापूर्वी तपशीलांची पुष्टी करा",
        "orderType": "आदेशाचा प्रकार",
        "orderItems": "आदेश आयटम",
        "clinicalNotes": "वैद्यकीय नोंदी",
        "thisOrderWillBeSentForApproval": "हा आदेश तुमच्या परवानग्यांवर अवलंबून मंजुरीसाठी पाठवला जाईल.",
        "back": "मागे",
        "cancel": "रद्द करा",
        "next": "पुढे",
        "submitting": "सबमिट करत आहे...",
        "submitOrder": "आदेश सबमिट करा",
        "orderManagement": "आदेश व्यवस्थापन",
        "phase4Subtitle": "टप्पा 4 — एंटरप्राइज ऑर्डर इंजिन",
        "encounter": "भेट",
        "patient": "रुग्ण",
        "selectAnEncounterTitle": "एक भेट निवडा",
        "chooseActiveEncounterSubtitle": "आदेश व्यवस्थापित करण्यासाठी सक्रिय भेट निवडा",
        "changeBtn": "बदला",
        "selectEncounterBtn": "भेट निवडा",
        "noEncounterSelected": "कोणतीही भेट निवडली नाही",
        "selectAnActiveEncounterToViewA": "आदेश पाहण्यासाठी आणि व्यवस्थापित करण्यासाठी सक्रिय भेट निवडा.",
        "selectEncounter": "भेट निवडा",
        "filterLabel": "फिल्टर:",
        "allTypes": "सर्व प्रकार",
        "allStatuses": "सर्व स्थिती",
        "ordersCountLabel": "आदेश",
        "loadingOrders": "आदेश लोड होत आहेत...",
        "noOrdersFoundCreateTheFirstOrd": "कोणतेही आदेश आढळले नाहीत. वर पहिला आदेश तयार करा.",
        "searchTestsPlaceholder": '"सीबीसी", "अॅस्पिरिन", "ईसीजी" शोधा...',
        "specialInstructionsPlaceholder": "विशेष सूचना...",
        "additionalClinicalContextPlaceholder": "अतिरिक्त सूचना किंवा वैद्यकीय संदर्भ...",
        "type_LAB_ORDER": "लॅब टेस्ट",
        "type_MEDICATION_ORDER": "औषध",
        "type_RADIOLOGY_ORDER": "इमेजिंग",
        "type_PROCEDURE_ORDER": "प्रक्रिया",
        "type_NURSING_TASK": "नर्सिंग",
        "priority_ROUTINE": "नियमित",
        "priority_URGENT": "तातडीने",
        "priority_STAT": "अत्यंत तातडीने",
        "status_DRAFT": "मसुदा",
        "status_PENDING_APPROVAL": "प्रलंबित",
        "status_APPROVED": "मंजूर",
        "status_IN_PROGRESS": "प्रगतीपथावर",
        "status_COMPLETED": "पूर्ण",
        "status_CANCELLED": "रद्द",
        "tab_orders": "आदेश",
        "tab_templates": "टेम्प्लेट्स",
        "tab_sets": "ऑर्डर सेट",
        "orderTemplates": "आदेश टेम्प्लेट्स",
        "reusableOrderCombinationsForFa": "जलद कार्यप्रवाहासाठी पुनर्वापरण्यायोग्य आदेश संयोजन"
    }
}

for lang_code in ['en', 'hi', 'mr', 'ar', 'es', 'fr', 'pt', 'de', 'ru', 'zh', 'ja']:
    file_path = os.path.join(locales_dir, f"{lang_code}.json")
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            try:
                data = json.load(f)
            except:
                data = {}
        
        final_translations = translations["en"].copy()
        if lang_code in translations:
            final_translations.update(translations[lang_code])
            
        if "orders" not in data:
            data["orders"] = {}
        
        data["orders"].update(final_translations)
        
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"Updated orders in {file_path}")
