import json
import os

locales_dir = "frontend/src/i18n/locales"

encounter_translations = {
    "en": {
        "title": "Today's Encounters",
        "subtitle": "Manage clinical consultations and admissions.",
        "newQuickEncounter": "New Quick Encounter",
        "searchPlaceholder": "Search encounters by patient ID or department...",
        "allStatuses": "All Statuses",
        "statusScheduled": "Scheduled",
        "statusInProgress": "In Progress",
        "statusCompleted": "Completed",
        "loadingEncounters": "Loading encounters...",
        "noEncountersFound": "No encounters found",
        "clickToStart": "Click 'New Quick Encounter' to start a clinical visit.",
        "encounterId": "ENCOUNTER ID",
        "type": "TYPE",
        "department": "DEPARTMENT",
        "status": "STATUS",
        "date": "DATE",
        "action": "ACTION",
        "workspace": "Workspace",
        "newEncounter": "New Encounter",
        "loadingPatients": "Loading patients...",
        "noPatientsFound": "No patients found.",
        "encounterType": "Encounter Type",
        "opOutPatient": "OP (Out-Patient)",
        "ipInPatient": "IP (In-Patient)",
        "erEmergency": "ER (Emergency)",
        "followUp": "Follow-Up",
        "teleconsultation": "Teleconsultation",
        "generalMedicine": "General Medicine",
        "cardiology": "Cardiology",
        "orthopedics": "Orthopedics",
        "pediatrics": "Pediatrics",
        "neurology": "Neurology",
        "oncology": "Oncology",
        "dermatology": "Dermatology",
        "gynecology": "Gynecology",
        "ophthalmology": "Ophthalmology",
        "ent": "ENT",
        "psychiatry": "Psychiatry",
        "emergency": "Emergency",
        "inProgressStartNow": "In Progress (Start Now)",
        "scheduled": "Scheduled",
        "cancel": "Cancel",
        "creating": "Creating...",
        "createEncounter": "Create Encounter",
        "selectPatient": "Select Patient",
        "searchPatientPlaceholder": "Search by name, patient ID...",
        "registerOneFirst": "Register one first →",
        "selected": "Selected",
        "selectedPatientPrefix": "Patient"
    },
    "hi": {
        "title": "आज की मुलाकातें",
        "subtitle": "नैदानिक परामर्श और प्रवेश प्रबंधित करें।",
        "newQuickEncounter": "नई त्वरित मुलाकात",
        "searchPlaceholder": "रोगी आईडी या विभाग द्वारा खोजें...",
        "allStatuses": "सभी स्थितियाँ",
        "statusScheduled": "निर्धारित",
        "statusInProgress": "प्रगति में",
        "statusCompleted": "पूर्ण",
        "loadingEncounters": "मुलाकातें लोड हो रही हैं...",
        "noEncountersFound": "कोई मुलाकात नहीं मिली",
        "clickToStart": "शुरू करने के लिए 'नई त्वरित मुलाकात' पर क्लिक करें।",
        "encounterId": "मुलाकात आईडी",
        "type": "प्रकार",
        "department": "विभाग",
        "status": "स्थिति",
        "date": "तारीख",
        "action": "कार्रवाई",
        "workspace": "कार्यक्षेत्र",
        "newEncounter": "नई मुलाकात",
        "loadingPatients": "मरीज लोड हो रहे हैं...",
        "noPatientsFound": "कोई मरीज नहीं मिला।",
        "encounterType": "मुलाकात का प्रकार",
        "opOutPatient": "ओपीडी (बाह्य रोगी)",
        "ipInPatient": "आईपीडी (भर्ती रोगी)",
        "erEmergency": "ईआर (आपातकालीन)",
        "followUp": "फॉलो-अप",
        "teleconsultation": "टेलीकंसल्टेशन",
        "generalMedicine": "सामान्य चिकित्सा",
        "cardiology": "हृदय रोग",
        "orthopedics": "अस्थि रोग",
        "pediatrics": "बाल रोग",
        "neurology": "स्नायु रोग",
        "oncology": "कैंसर रोग",
        "dermatology": "त्वचा रोग",
        "gynecology": "स्त्री रोग",
        "ophthalmology": "नेत्र रोग",
        "ent": "ईएनटी",
        "psychiatry": "मनोरोग",
        "emergency": "आपातकालीन",
        "inProgressStartNow": "प्रगति में (अभी शुरू करें)",
        "scheduled": "निर्धारित",
        "cancel": "रद्द करें",
        "creating": "बनाया जा रहा है...",
        "createEncounter": "मुलाकात बनाएँ",
        "selectPatient": "रोगी चुनें",
        "searchPatientPlaceholder": "नाम, रोगी आईडी द्वारा खोजें...",
        "registerOneFirst": "पहले एक पंजीकृत करें →",
        "selected": "चयनित",
        "selectedPatientPrefix": "रोगी"
    },
    "mr": {
        "title": "आजच्या भेटी",
        "subtitle": "क्लिनिकल सल्लामसलत आणि प्रवेश व्यवस्थापित करा.",
        "newQuickEncounter": "नवीन त्वरित भेट",
        "searchPlaceholder": "रुग्ण आयडी किंवा विभागानुसार शोधा...",
        "allStatuses": "सर्व स्थिती",
        "statusScheduled": "नियोजित",
        "statusInProgress": "प्रगतीपथावर",
        "statusCompleted": "पूर्ण",
        "loadingEncounters": "भेटी लोड होत आहेत...",
        "noEncountersFound": "कोणतीही भेट आढळली नाही",
        "clickToStart": "सुरू करण्यासाठी 'नवीन त्वरित भेट' दाबा.",
        "encounterId": "भेट आयडी",
        "type": "प्रकार",
        "department": "विभाग",
        "status": "स्थिती",
        "date": "तारीख",
        "action": "कृती",
        "workspace": "कार्यक्षेत्र",
        "newEncounter": "नवीन भेट",
        "loadingPatients": "रुग्ण लोड होत आहेत...",
        "noPatientsFound": "कोणतेही रुग्ण आढळले नाहीत.",
        "encounterType": "भेटीचा प्रकार",
        "opOutPatient": "ओपीडी (बाह्य रुग्ण)",
        "ipInPatient": "आयपीडी (दाखल रुग्ण)",
        "erEmergency": "ईआर (आपत्कालीन)",
        "followUp": "फॉलो-अप",
        "teleconsultation": "टेलिकन्सल्टेशन",
        "generalMedicine": "सामान्य चिकित्सा",
        "cardiology": "हृदयरोग",
        "orthopedics": "अस्थिरोग",
        "pediatrics": "बालरोग",
        "neurology": "मज्जातंतू रोग",
        "oncology": "कर्करोग",
        "dermatology": "त्वचारोग",
        "gynecology": "स्त्रीरोग",
        "ophthalmology": "नेत्ररोग",
        "ent": "कान, नाक, घसा",
        "psychiatry": "मनोरोग",
        "emergency": "आपत्कालीन",
        "inProgressStartNow": "प्रगतीपथावर (आत्ता सुरू करा)",
        "scheduled": "नियोजित",
        "cancel": "रद्द करा",
        "creating": "तयार करत आहे...",
        "createEncounter": "भेट तयार करा",
        "selectPatient": "रुग्ण निवडा",
        "searchPatientPlaceholder": "नाव, रुग्ण आयडी द्वारे शोधा...",
        "registerOneFirst": "प्रथम नोंदणी करा →",
        "selected": "निवडलेले",
        "selectedPatientPrefix": "रुग्ण"
    },
    "ar": {
        "title": "زيارات اليوم",
        "subtitle": "إدارة الاستشارات السريرية والدخول.",
        "newQuickEncounter": "زيارة سريعة جديدة",
        "searchPlaceholder": "البحث عن طريق رقم المريض أو القسم...",
        "allStatuses": "جميع الحالات",
        "statusScheduled": "مجدول",
        "statusInProgress": "قيد التقدم",
        "statusCompleted": "مكتمل",
        "loadingEncounters": "جاري تحميل الزيارات...",
        "noEncountersFound": "لا توجد زيارات",
        "clickToStart": "انقر على 'زيارة سريعة جديدة' للبدء.",
        "encounterId": "معرف الزيارة",
        "type": "النوع",
        "department": "القسم",
        "status": "الحالة",
        "date": "التاريخ",
        "action": "إجراء",
        "workspace": "مساحة العمل",
        "newEncounter": "زيارة جديدة",
        "loadingPatients": "جاري تحميل المرضى...",
        "noPatientsFound": "لم يتم العثور على مرضى.",
        "encounterType": "نوع الزيارة",
        "opOutPatient": "عيادة خارجية (OP)",
        "ipInPatient": "تنويم (IP)",
        "erEmergency": "طوارئ (ER)",
        "followUp": "متابعة",
        "teleconsultation": "استشارة عن بعد",
        "generalMedicine": "الطب العام",
        "cardiology": "أمراض القلب",
        "orthopedics": "جراحة العظام",
        "pediatrics": "طب الأطفال",
        "neurology": "طب الأعصاب",
        "oncology": "طب الأورام",
        "dermatology": "الأمراض الجلدية",
        "gynecology": "أمراض النساء",
        "ophthalmology": "طب العيون",
        "ent": "أنف وأذن وحنجرة",
        "psychiatry": "الطب النفسي",
        "emergency": "الطوارئ",
        "inProgressStartNow": "قيد التقدم (ابدأ الآن)",
        "scheduled": "مجدول",
        "cancel": "إلغاء",
        "creating": "جاري الإنشاء...",
        "createEncounter": "إنشاء زيارة"
    },
    "es": {
        "title": "Encuentros de Hoy",
        "subtitle": "Gestione consultas clínicas e internaciones.",
        "newQuickEncounter": "Nuevo Encuentro",
        "searchPlaceholder": "Buscar por ID de paciente o departamento...",
        "allStatuses": "Todos los Estados",
        "statusScheduled": "Programado",
        "statusInProgress": "En Progreso",
        "statusCompleted": "Completado",
        "loadingEncounters": "Cargando encuentros...",
        "noEncountersFound": "No se encontraron encuentros",
        "clickToStart": "Haga clic en 'Nuevo Encuentro' para comenzar.",
        "encounterId": "ID DEL ENCUENTRO",
        "type": "TIPO",
        "department": "DEPARTAMENTO",
        "status": "ESTADO",
        "date": "FECHA",
        "action": "ACCIÓN",
        "workspace": "Espacio de Trabajo",
        "newEncounter": "Nuevo Encuentro",
        "loadingPatients": "Cargando pacientes...",
        "noPatientsFound": "No se encontraron pacientes.",
        "encounterType": "Tipo de Encuentro",
        "opOutPatient": "Ambulatorio (OPD)",
        "ipInPatient": "Internación (IPD)",
        "erEmergency": "Emergencia (ER)",
        "followUp": "Seguimiento",
        "teleconsultation": "Teleconsulta",
        "generalMedicine": "Medicina General",
        "cardiology": "Cardiología",
        "orthopedics": "Ortopedia",
        "pediatrics": "Pediatría",
        "neurology": "Neurología",
        "oncology": "Oncología",
        "dermatology": "Dermatología",
        "gynecology": "Ginecología",
        "ophthalmology": "Oftalmología",
        "ent": "ORL",
        "psychiatry": "Psiquiatría",
        "emergency": "Emergencia",
        "inProgressStartNow": "En Progreso (Iniciar)",
        "scheduled": "Programado",
        "cancel": "Cancelar",
        "creating": "Creando...",
        "createEncounter": "Crear Encuentro"
    },
    "de": {
        "title": "Heutige Begegnungen",
        "subtitle": "Verwalten Sie klinische Konsultationen.",
        "newQuickEncounter": "Neue Begegnung",
        "searchPlaceholder": "Nach Patienten-ID oder Abteilung suchen...",
        "allStatuses": "Alle Status",
        "statusScheduled": "Geplant",
        "statusInProgress": "In Bearbeitung",
        "statusCompleted": "Abgeschlossen",
        "loadingEncounters": "Lade Begegnungen...",
        "noEncountersFound": "Keine Begegnungen gefunden",
        "clickToStart": "Klicken Sie auf 'Neue Begegnung', um zu beginnen.",
        "encounterId": "BEGEGNUNGS-ID",
        "type": "TYP",
        "department": "ABTEILUNG",
        "status": "STATUS",
        "date": "DATUM",
        "action": "AKTION",
        "workspace": "Arbeitsbereich",
        "newEncounter": "Neue Begegnung",
        "loadingPatients": "Lade Patienten...",
        "noPatientsFound": "Keine Patienten gefunden.",
        "encounterType": "Begegnungstyp",
        "opOutPatient": "Ambulant (OP)",
        "ipInPatient": "Stationär (IP)",
        "erEmergency": "Notaufnahme (ER)",
        "followUp": "Nachuntersuchung",
        "teleconsultation": "Telekonsultation",
        "generalMedicine": "Allgemeinmedizin",
        "cardiology": "Kardiologie",
        "orthopedics": "Orthopädie",
        "pediatrics": "Pädiatrie",
        "neurology": "Neurologie",
        "oncology": "Onkologie",
        "dermatology": "Dermatologie",
        "gynecology": "Gynäkologie",
        "ophthalmology": "Ophthalmologie",
        "ent": "HNO",
        "psychiatry": "Psychiatrie",
        "emergency": "Notfall",
        "inProgressStartNow": "In Bearbeitung (Jetzt starten)",
        "scheduled": "Geplant",
        "cancel": "Abbrechen",
        "creating": "Erstellen...",
        "createEncounter": "Erstellen"
    },
    "fr": {
        "title": "Consultations du Jour",
        "subtitle": "Gérez les consultations et les admissions.",
        "newQuickEncounter": "Nouvelle Consultation",
        "searchPlaceholder": "Rechercher par ID ou département...",
        "allStatuses": "Tous les statuts",
        "statusScheduled": "Programmé",
        "statusInProgress": "En Cours",
        "statusCompleted": "Terminé",
        "loadingEncounters": "Chargement...",
        "noEncountersFound": "Aucune consultation trouvée",
        "clickToStart": "Cliquez sur 'Nouvelle Consultation' pour commencer.",
        "encounterId": "ID CONSULTATION",
        "type": "TYPE",
        "department": "DÉPARTEMENT",
        "status": "STATUT",
        "date": "DATE",
        "action": "ACTION",
        "workspace": "Espace de Travail",
        "newEncounter": "Nouvelle Consultation",
        "loadingPatients": "Chargement des patients...",
        "noPatientsFound": "Aucun patient trouvé.",
        "encounterType": "Type de Consultation",
        "opOutPatient": "Ambulatoire (OPD)",
        "ipInPatient": "Hospitalisation (IPD)",
        "erEmergency": "Urgences (ER)",
        "followUp": "Suivi",
        "teleconsultation": "Téléconsultation",
        "generalMedicine": "Médecine Générale",
        "cardiology": "Cardiologie",
        "orthopedics": "Orthopédie",
        "pediatrics": "Pédiatrie",
        "neurology": "Neurologie",
        "oncology": "Oncologie",
        "dermatology": "Dermatologie",
        "gynecology": "Gynécologie",
        "ophthalmology": "Ophtalmologie",
        "ent": "ORL",
        "psychiatry": "Psychiatrie",
        "emergency": "Urgences",
        "inProgressStartNow": "En Cours (Démarrer)",
        "scheduled": "Programmé",
        "cancel": "Annuler",
        "creating": "Création...",
        "createEncounter": "Créer"
    },
    "pt": {
        "title": "Consultas de Hoje",
        "subtitle": "Gerencie consultas clínicas e admissões.",
        "newQuickEncounter": "Nova Consulta",
        "searchPlaceholder": "Buscar por ID do paciente ou departamento...",
        "allStatuses": "Todos os Status",
        "statusScheduled": "Agendado",
        "statusInProgress": "Em Andamento",
        "statusCompleted": "Concluído",
        "loadingEncounters": "Carregando...",
        "noEncountersFound": "Não foram encontradas consultas",
        "clickToStart": "Clique em 'Nova Consulta' para começar.",
        "encounterId": "ID DA CONSULTA",
        "type": "TIPO",
        "department": "DEPARTAMENTO",
        "status": "STATUS",
        "date": "DATA",
        "action": "AÇÃO",
        "workspace": "Espaço de Trabalho",
        "newEncounter": "Nova Consulta",
        "loadingPatients": "Carregando pacientes...",
        "noPatientsFound": "Nenhum paciente encontrado.",
        "encounterType": "Tipo de Consulta",
        "opOutPatient": "Ambulatorial (OPD)",
        "ipInPatient": "Internação (IPD)",
        "erEmergency": "Emergência (ER)",
        "followUp": "Retorno",
        "teleconsultation": "Teleconsulta",
        "generalMedicine": "Clínica Geral",
        "cardiology": "Cardiologia",
        "orthopedics": "Ortopedia",
        "pediatrics": "Pediatria",
        "neurology": "Neurologia",
        "oncology": "Oncologia",
        "dermatology": "Dermatologia",
        "gynecology": "Ginecologia",
        "ophthalmology": "Oftalmologia",
        "ent": "Otorrino",
        "psychiatry": "Psiquiatria",
        "emergency": "Emergência",
        "inProgressStartNow": "Em Andamento (Iniciar)",
        "scheduled": "Agendado",
        "cancel": "Cancelar",
        "creating": "Criando...",
        "createEncounter": "Criar"
    },
    "ru": {
        "title": "Приемы сегодня",
        "subtitle": "Управление клиническими консультациями.",
        "newQuickEncounter": "Новый прием",
        "searchPlaceholder": "Поиск по ID или отделению...",
        "allStatuses": "Все статусы",
        "statusScheduled": "Запланировано",
        "statusInProgress": "В процессе",
        "statusCompleted": "Завершено",
        "loadingEncounters": "Загрузка приемов...",
        "noEncountersFound": "Приемы не найдены",
        "clickToStart": "Нажмите 'Новый прием' для начала.",
        "encounterId": "ID ПРИЕМА",
        "type": "ТИП",
        "department": "ОТДЕЛЕНИЕ",
        "status": "СТАТУС",
        "date": "ДАТА",
        "action": "ДЕЙСТВИЕ",
        "workspace": "Рабочая область",
        "newEncounter": "Новый прием",
        "loadingPatients": "Загрузка пациентов...",
        "noPatientsFound": "Пациенты не найдены.",
        "encounterType": "Тип приема",
        "opOutPatient": "Амбулаторно",
        "ipInPatient": "Стационар",
        "erEmergency": "Скорая",
        "followUp": "Повторный",
        "teleconsultation": "Телемедицина",
        "generalMedicine": "Общая медицина",
        "cardiology": "Кардиология",
        "orthopedics": "Ортопедия",
        "pediatrics": "Педиатрия",
        "neurology": "Неврология",
        "oncology": "Онкология",
        "dermatology": "Дерматология",
        "gynecology": "Гинекология",
        "ophthalmology": "Офтальмология",
        "ent": "ЛОР",
        "psychiatry": "Психиатрия",
        "emergency": "Экстренная",
        "inProgressStartNow": "В процессе (Начать)",
        "scheduled": "Запланировано",
        "cancel": "Отмена",
        "creating": "Создание...",
        "createEncounter": "Создать"
    },
    "zh": {
        "title": "今日就诊",
        "subtitle": "管理临床问诊和住院申请。",
        "newQuickEncounter": "新建就诊",
        "searchPlaceholder": "按患者ID或科室搜索...",
        "allStatuses": "所有状态",
        "statusScheduled": "已预约",
        "statusInProgress": "进行中",
        "statusCompleted": "已完成",
        "loadingEncounters": "加载中...",
        "noEncountersFound": "未找到就诊记录",
        "clickToStart": "点击 '新建就诊' 开始。",
        "encounterId": "就诊ID",
        "type": "类型",
        "department": "科室",
        "status": "状态",
        "date": "时间",
        "action": "操作",
        "workspace": "工作区",
        "newEncounter": "新建就诊",
        "loadingPatients": "加载患者中...",
        "noPatientsFound": "未找到患者。",
        "encounterType": "就诊类型",
        "opOutPatient": "门诊 (OP)",
        "ipInPatient": "住院 (IP)",
        "erEmergency": "急诊 (ER)",
        "followUp": "复诊",
        "teleconsultation": "远程问诊",
        "generalMedicine": "普通内科",
        "cardiology": "心内科",
        "orthopedics": "骨科",
        "pediatrics": "儿科",
        "neurology": "神经内科",
        "oncology": "肿瘤科",
        "dermatology": "皮肤科",
        "gynecology": "妇科",
        "ophthalmology": "眼科",
        "ent": "耳鼻喉科",
        "psychiatry": "精神科",
        "emergency": "急诊科",
        "inProgressStartNow": "进行中 (立即开始)",
        "scheduled": "已预约",
        "cancel": "取消",
        "creating": "创建中...",
        "createEncounter": "创建"
    },
    "ja": {
        "title": "本日の受診",
        "subtitle": "診療および入院を管理します。",
        "newQuickEncounter": "新規受診",
        "searchPlaceholder": "患者IDまたは診療科で検索...",
        "allStatuses": "全ステータス",
        "statusScheduled": "予約済",
        "statusInProgress": "進行中",
        "statusCompleted": "完了",
        "loadingEncounters": "読込中...",
        "noEncountersFound": "受診記録が見つかりません",
        "clickToStart": "「新規受診」をクリックして開始します。",
        "encounterId": "受診ID",
        "type": "タイプ",
        "department": "診療科",
        "status": "ステータス",
        "date": "日時",
        "action": "アクション",
        "workspace": "ワークスペース",
        "newEncounter": "新規受診",
        "loadingPatients": "患者を読み込んでいます...",
        "noPatientsFound": "患者が見つかりませんでした。",
        "encounterType": "受診タイプ",
        "opOutPatient": "外来 (OP)",
        "ipInPatient": "入院 (IP)",
        "erEmergency": "救急 (ER)",
        "followUp": "再診",
        "teleconsultation": "オンライン診療",
        "generalMedicine": "一般内科",
        "cardiology": "循環器内科",
        "orthopedics": "整形外科",
        "pediatrics": "小児科",
        "neurology": "神経内科",
        "oncology": "腫瘍内科",
        "dermatology": "皮膚科",
        "gynecology": "婦人科",
        "ophthalmology": "眼科",
        "ent": "耳鼻いんこう科",
        "psychiatry": "精神科",
        "emergency": "救急科",
        "inProgressStartNow": "進行中 (開始する)",
        "scheduled": "予約済",
        "cancel": "キャンセル",
        "creating": "作成中...",
        "createEncounter": "作成する"
    }
}

for lang_code, translations in encounter_translations.items():
    file_path = os.path.join(locales_dir, f"{lang_code}.json")
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            try:
                data = json.load(f)
            except:
                data = {}
        
        # Merge if missing or overwrite completely to be safe
        final_translations = encounter_translations["en"].copy()
        final_translations.update(translations)
        data["encounters"] = final_translations
        
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"Updated {file_path}")
