import json
import os

locales_dir = "frontend/src/i18n/locales"

translations = {
    "ar": {
        "dashboard": {
            "totalPatients": "إجمالي المرضى",
            "activeEncounters": "الزيارات النشطة",
            "pendingTasks": "المهام المعلقة",
            "lowStock": "تنبيهات انخفاض المخزون",
            "pendingRx": "الوصفات المعلقة",
            "nearExpiry": "قريب من الانتهاء",
            "labSamples": "عينات المختبر",
            "invoices": "الفواتير",
            "quickNav": "التنقل السريع",
            "quickNavDesc": "الوصول المباشر إلى الوحدات الأساسية",
            "Registeredpatients": "المرضى المسجلين",
            "Inprogress&scheduled": "قيد التقدم ومجدولة",
            "Awaitingexecution": "في انتظار التنفيذ",
            "Itemsbelowthreshold": "عناصر أقل من الحد الأدنى",
            "Awaitingdispensing": "في انتظار الصرف",
            "Expiringin60days": "تنتهي صلاحيته خلال ٦٠ يومًا",
            "Pendingprocessing": "في انتظار المعالجة",
            "1pendingpayment": "1 دفعة معلقة",
            "Register&searchpatie": "تسجيل والبحث عن المرضى",
            "Manageclinicalvisits": "إدارة الزيارات السريرية",
            "Labtests,medications": "الفحوصات الطبية والأدوية",
            "Clinicalworkflows&nu": "سير العمل السريري",
            "Testcatalog,samples&": "كتالوج الفحوصات والنتائج",
            "Inventory,prescripti": "المخزون والوصفات الطبية",
            "Invoices,payments&in": "الفواتير والمدفوعات",
            "PatientRegistry": "سجل المرضى",
            "Encounters": "الزيارات",
            "OrderManagement": "إدارة الطلبات",
            "TaskQueue": "قائمة المهام",
            "Laboratory": "المختبر",
            "Pharmacy": "الصيدلية",
            "Billing": "الفواتير"
        }
    },
    "de": {
        "dashboard": {
            "totalPatients": "Patienten gesamt",
            "activeEncounters": "Aktive Konsultationen",
            "pendingTasks": "Ausstehende Aufgaben",
            "lowStock": "Warnungen: Niedriger Bestand",
            "pendingRx": "Ausstehende Rezepte",
            "nearExpiry": "Bald ablaufend",
            "labSamples": "Laborproben",
            "invoices": "Rechnungen",
            "quickNav": "Schnellnavigation",
            "quickNavDesc": "Direkter Zugriff auf Kernmodule",
            "Registeredpatients": "Registrierte Patienten",
            "Inprogress&scheduled": "In Bearbeitung & geplant",
            "Awaitingexecution": "Wartet auf Ausführung",
            "Itemsbelowthreshold": "Artikel unter Schwellenwert",
            "Awaitingdispensing": "Wartet auf Abgabe",
            "Expiringin60days": "Läuft in 60 Tagen ab",
            "Pendingprocessing": "Verarbeitung ausstehend",
            "1pendingpayment": "1 ausstehende Zahlung",
            "Register&searchpatie": "Patienten registrieren & suchen",
            "Manageclinicalvisits": "Klinische Besuche verwalten",
            "Labtests,medications": "Labortests, Medikamente",
            "Clinicalworkflows&nu": "Klinische Workflows",
            "Testcatalog,samples&": "Testkatalog, Ergebnisse",
            "Inventory,prescripti": "Inventar, Rezepte",
            "Invoices,payments&in": "Rechnungen, Zahlungen",
            "PatientRegistry": "Patientenregister",
            "Encounters": "Konsultationen",
            "OrderManagement": "Auftragsverwaltung",
            "TaskQueue": "Aufgabenwarteschlange",
            "Laboratory": "Labor",
            "Pharmacy": "Apotheke",
            "Billing": "Abrechnung"
        }
    },
    "es": {
        "dashboard": {
            "totalPatients": "Pacientes Totales",
            "activeEncounters": "Encuentros Activos",
            "pendingTasks": "Tareas Pendientes",
            "lowStock": "Bajo Inventario",
            "pendingRx": "Recetas Pendientes",
            "nearExpiry": "Próximo a Caducar",
            "labSamples": "Muestras de Laboratorio",
            "invoices": "Facturas",
            "quickNav": "Navegación Rápida",
            "quickNavDesc": "Acceso directo a módulos centrales",
            "Registeredpatients": "Pacientes registrados",
            "Inprogress&scheduled": "En progreso y programado",
            "Awaitingexecution": "Esperando ejecución",
            "Itemsbelowthreshold": "Artículos bajo el límite",
            "Awaitingdispensing": "Esperando dispensación",
            "Expiringin60days": "Caduca en 60 días",
            "Pendingprocessing": "Procesamiento pendiente",
            "1pendingpayment": "1 pago pendiente",
            "Register&searchpatie": "Registrar y buscar pacientes",
            "Manageclinicalvisits": "Gestionar visitas clínicas",
            "Labtests,medications": "Pruebas de laboratorio, medicinas",
            "Clinicalworkflows&nu": "Flujos de trabajo clínicos",
            "Testcatalog,samples&": "Catálogo de pruebas y resultados",
            "Inventory,prescripti": "Inventario, recetas",
            "Invoices,payments&in": "Facturas, pagos",
            "PatientRegistry": "Registro de Pacientes",
            "Encounters": "Encuentros",
            "OrderManagement": "Gestión de Órdenes",
            "TaskQueue": "Cola de Tareas",
            "Laboratory": "Laboratorio",
            "Pharmacy": "Farmacia",
            "Billing": "Facturación"
        }
    },
    "fr": {
        "dashboard": {
            "totalPatients": "Total des Patients",
            "activeEncounters": "Consultations Actives",
            "pendingTasks": "Tâches en Attente",
            "lowStock": "Alerte de Stock Faible",
            "pendingRx": "Ordonnances en Attente",
            "nearExpiry": "Preès de l'Expiration",
            "labSamples": "Échantillons de Laboratoire",
            "invoices": "Factures",
            "quickNav": "Navigation Rapide",
            "quickNavDesc": "Accès direct aux modules centraux",
            "Registeredpatients": "Patients enregistrés",
            "Inprogress&scheduled": "En cours et programmé",
            "Awaitingexecution": "En attente d'exécution",
            "Itemsbelowthreshold": "Articles sous le seuil",
            "Awaitingdispensing": "En attente de dispensation",
            "Expiringin60days": "Expire dans 60 jours",
            "Pendingprocessing": "Le traitement est en attente",
            "1pendingpayment": "1 paiement en attente",
            "Register&searchpatie": "Enregistrer et rechercher",
            "Manageclinicalvisits": "Gérer les visites cliniques",
            "Labtests,medications": "Tests de laboratoire, médicaments",
            "Clinicalworkflows&nu": "Flux de travail",
            "Testcatalog,samples&": "Catalogue de tests, résultats",
            "Inventory,prescripti": "Inventaire, ordonnances",
            "Invoices,payments&in": "Factures, paiements",
            "PatientRegistry": "Registre des Patients",
            "Encounters": "Consultations",
            "OrderManagement": "Gestion des Commandes",
            "TaskQueue": "File d'attente",
            "Laboratory": "Laboratoire",
            "Pharmacy": "Pharmacie",
            "Billing": "Facturation"
        }
    },
    "ja": {
        "dashboard": {
            "totalPatients": "総患者数",
            "activeEncounters": "アクティブな診察",
            "pendingTasks": "保留中のタスク",
            "lowStock": "在庫不足アラート",
            "pendingRx": "保留中の処方箋",
            "nearExpiry": "有効期限切れ間近",
            "labSamples": "臨床検査サンプル",
            "invoices": "請求書",
            "quickNav": "クイックナビゲーション",
            "quickNavDesc": "コアモジュールへの直接アクセス",
            "Registeredpatients": "登録患者",
            "Inprogress&scheduled": "進行中および予定済み",
            "Awaitingexecution": "実行待ち",
            "Itemsbelowthreshold": "しきい値を下回るアイテム",
            "Awaitingdispensing": "調剤待ち",
            "Expiringin60days": "60日以内に有効期限切れ",
            "Pendingprocessing": "処理待ち",
            "1pendingpayment": "1件の保留中の支払い",
            "Register&searchpatie": "患者の登録と検索",
            "Manageclinicalvisits": "臨床訪問の管理",
            "Labtests,medications": "臨床検査、薬剤",
            "Clinicalworkflows&nu": "臨床ワークフローと看護",
            "Testcatalog,samples&": "テストカタログと結果",
            "Inventory,prescripti": "在庫、処方箋",
            "Invoices,payments&in": "請求書、支払い",
            "PatientRegistry": "患者登録",
            "Encounters": "診察",
            "OrderManagement": "注文管理",
            "TaskQueue": "タスクキュー",
            "Laboratory": "検査室",
            "Pharmacy": "薬局",
            "Billing": "請求書作成"
        }
    },
    "pt": {
        "dashboard": {
            "totalPatients": "Pacientes Registrados",
            "activeEncounters": "Consultas Ativas",
            "pendingTasks": "Tarefas Pendentes",
            "lowStock": "Alerta de Estoque Baixo",
            "pendingRx": "Receitas Pendentes",
            "nearExpiry": "Perto da Validade",
            "labSamples": "Amostras de Laboratório",
            "invoices": "Faturas",
            "quickNav": "Navegação Rápida",
            "quickNavDesc": "Acesso direto aos módulos centrais",
            "Registeredpatients": "Pacientes registrados",
            "Inprogress&scheduled": "Em andamento e agendado",
            "Awaitingexecution": "Aguardando execução",
            "Itemsbelowthreshold": "Itens abaixo do limite limite",
            "Awaitingdispensing": "Aguardando dispensação",
            "Expiringin60days": "Termina em 60 dias",
            "Pendingprocessing": "Processamento pendente",
            "1pendingpayment": "1 pagamento pendente",
            "Register&searchpatie": "Registrar e pesquisar pacientes",
            "Manageclinicalvisits": "Gerenciar visitas clínicas",
            "Labtests,medications": "Testes de laboratório, medicamentos",
            "Clinicalworkflows&nu": "Fluxos de trabalho clínicos",
            "Testcatalog,samples&": "Catálogo de testes e resultados",
            "Inventory,prescripti": "Inventário, prescrições",
            "Invoices,payments&in": "Faturas, pagamentos",
            "PatientRegistry": "Registro de Pacientes",
            "Encounters": "Consultas",
            "OrderManagement": "Gestão de Ordenes",
            "TaskQueue": "Fila de Tarefas",
            "Laboratory": "Laboratório",
            "Pharmacy": "Farmácia",
            "Billing": "Faturamento"
        }
    },
    "ru": {
        "dashboard": {
            "totalPatients": "Всего пациентов",
            "activeEncounters": "Активные приемы",
            "pendingTasks": "Ожидающие задачи",
            "lowStock": "Оповещения о низком запасе",
            "pendingRx": "Ожидающие рецепты",
            "nearExpiry": "Скоро истекает срок",
            "labSamples": "Лабораторные образцы",
            "invoices": "Счета",
            "quickNav": "Быстрая навигация",
            "quickNavDesc": "Прямой доступ к основным модулям",
            "Registeredpatients": "Зарегистрированные пациенты",
            "Inprogress&scheduled": "В процессе и запланировано",
            "Awaitingexecution": "Ожидает выполнения",
            "Itemsbelowthreshold": "Товары ниже порогового значения",
            "Awaitingdispensing": "Ожидает выдачи",
            "Expiringin60days": "Истекает через 60 дней",
            "Pendingprocessing": "Ожидание обработки",
            "1pendingpayment": "1 ожидающий платеж",
            "Register&searchpatie": "Регистрация и поиск пациентов",
            "Manageclinicalvisits": "Управление визитами",
            "Labtests,medications": "Лабораторные тесты, лекарства",
            "Clinicalworkflows&nu": "Клинические рабочие процессы",
            "Testcatalog,samples&": "Каталог тестов и результаты",
            "Inventory,prescripti": "Инвентарь, рецепты",
            "Invoices,payments&in": "Счета, платежи",
            "PatientRegistry": "Реестр Пациентов",
            "Encounters": "Приемы",
            "OrderManagement": "Управление заказами",
            "TaskQueue": "Очередь задач",
            "Laboratory": "Лаборатория",
            "Pharmacy": "Аптека",
            "Billing": "Оплата"
        }
    },
    "zh": {
        "dashboard": {
            "totalPatients": "总患者数",
            "activeEncounters": "当前就诊",
            "pendingTasks": "待办任务",
            "lowStock": "低库存警报",
            "pendingRx": "待处理处方",
            "nearExpiry": "临近过期",
            "labSamples": "待处理样本",
            "invoices": "账单",
            "quickNav": "快速导航",
            "quickNavDesc": "直接访问核心模块",
            "Registeredpatients": "已注册患者",
            "Inprogress&scheduled": "进行中和已安排",
            "Awaitingexecution": "等待执行",
            "Itemsbelowthreshold": "低于阈值的项目",
            "Awaitingdispensing": "等待配药",
            "Expiringin60days": "60天内到期",
            "Pendingprocessing": "等待处理",
            "1pendingpayment": "1个待处理付款",
            "Register&searchpatie": "注册和搜索患者",
            "Manageclinicalvisits": "管理就诊记录",
            "Labtests,medications": "实验室测试和药物",
            "Clinicalworkflows&nu": "临床工作流程和护理",
            "Testcatalog,samples&": "测试目录和结果",
            "Inventory,prescripti": "库存和处方",
            "Invoices,payments&in": "账单和付款",
            "PatientRegistry": "患者登记",
            "Encounters": "就诊记录",
            "OrderManagement": "订单管理",
            "TaskQueue": "任务队列",
            "Laboratory": "实验室",
            "Pharmacy": "药房",
            "Billing": "账单"
        }
    }
}

for lang_code, lang_trans in translations.items():
    file_path = os.path.join(locales_dir, f"{lang_code}.json")
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        
        # Merge dashboard translation into the language file
        data["dashboard"] = lang_trans["dashboard"]
        
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"Updated {file_path}")
