"""
AXONHIS AI Platform – Phase 9 Database Models.

Tables:
  ai_summaries        – Cached patient summaries generated by LLM
  clinical_insights   – Detected clinical insights / recommendations
  risk_alerts         – Risk detection alerts (sepsis, drug, critical labs)
  voice_commands      – Voice command log with transcript and parsed intent
  ai_agent_tasks      – AI agent orchestration task log
"""
import uuid
from datetime import datetime, timezone
from enum import StrEnum
from typing import Any

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


# ── Enumerations ─────────────────────────────────────────────────────────────


class AlertSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertCategory(StrEnum):
    CLINICAL_RISK = "CLINICAL_RISK"
    MEDICATION_SAFETY = "MEDICATION_SAFETY"
    LAB_CRITICAL = "LAB_CRITICAL"
    PATIENT_DETERIORATION = "PATIENT_DETERIORATION"


class InsightType(StrEnum):
    ABNORMAL_LAB = "ABNORMAL_LAB"
    DRUG_INTERACTION = "DRUG_INTERACTION"
    RAPID_DETERIORATION = "RAPID_DETERIORATION"
    DELAYED_RESULT = "DELAYED_RESULT"
    SEPSIS_RISK = "SEPSIS_RISK"
    GENERAL = "GENERAL"


class VoiceCommandStatus(StrEnum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"
    EXECUTED = "EXECUTED"


class AgentTaskStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


# ── AI Patient Summary ────────────────────────────────────────────────────────


class AISummary(Base):
    """Cached AI-generated patient summary. Refreshed per encounter request."""
    __tablename__ = "ai_summaries"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    encounter_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("encounters.id", ondelete="CASCADE"), nullable=False, index=True
    )
    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("patients.id", ondelete="CASCADE"), nullable=False, index=True
    )
    narrative: Mapped[str] = mapped_column(Text, nullable=False)
    primary_diagnosis: Mapped[str | None] = mapped_column(Text, nullable=True)
    active_treatments: Mapped[list[Any]] = mapped_column(JSONB, nullable=False, default=list)
    recent_abnormal_labs: Mapped[list[Any]] = mapped_column(JSONB, nullable=False, default=list)
    pending_tests: Mapped[list[Any]] = mapped_column(JSONB, nullable=False, default=list)
    clinical_trends: Mapped[list[Any]] = mapped_column(JSONB, nullable=False, default=list)
    risk_flags: Mapped[list[Any]] = mapped_column(JSONB, nullable=False, default=list)
    llm_model: Mapped[str] = mapped_column(String(100), nullable=False, default="llama-3.3-70b-versatile")
    token_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    generated_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )
    is_stale: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)


# ── Clinical Insights ─────────────────────────────────────────────────────────


class ClinicalInsight(Base):
    """AI-detected clinical insight / recommendation for a patient encounter."""
    __tablename__ = "clinical_insights"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    encounter_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("encounters.id", ondelete="CASCADE"), nullable=False, index=True
    )
    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("patients.id", ondelete="CASCADE"), nullable=False, index=True
    )
    insight_type: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    recommendation: Mapped[str | None] = mapped_column(Text, nullable=True)
    confidence_score: Mapped[float | None] = mapped_column(nullable=True)
    source_data: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    is_acknowledged: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    acknowledged_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )


# ── Risk Alerts ───────────────────────────────────────────────────────────────


class RiskAlert(Base):
    """Clinically significant risk alerts detected by the AI engine."""
    __tablename__ = "risk_alerts"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    encounter_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("encounters.id", ondelete="CASCADE"), nullable=True, index=True
    )
    patient_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("patients.id", ondelete="CASCADE"), nullable=False, index=True
    )
    category: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    severity: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    recommended_action: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_data: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    is_resolved: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    resolved_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )


# ── Voice Commands ────────────────────────────────────────────────────────────


class VoiceCommand(Base):
    """Log of voice commands issued by clinicians; never auto-executed."""
    __tablename__ = "voice_commands"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    issued_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    encounter_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("encounters.id", ondelete="SET NULL"), nullable=True
    )
    raw_transcript: Mapped[str] = mapped_column(Text, nullable=False)
    detected_language: Mapped[str] = mapped_column(String(10), nullable=False, default="en")
    translated_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    intent: Mapped[str | None] = mapped_column(String(100), nullable=True)
    parsed_action: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    suggested_orders: Mapped[list[Any]] = mapped_column(JSONB, nullable=False, default=list)
    confidence: Mapped[float] = mapped_column(nullable=False, default=0.0)
    status: Mapped[str] = mapped_column(
        String(30), nullable=False, default=VoiceCommandStatus.PENDING, index=True
    )
    confirmed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )


# ── AI Agent Tasks ────────────────────────────────────────────────────────────


class AIAgentTask(Base):
    """AI agent task that requires clinician approval before execution."""
    __tablename__ = "ai_agent_tasks"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    agent_type: Mapped[str] = mapped_column(String(100), nullable=False)  # e.g. discharge_summary
    encounter_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("encounters.id", ondelete="SET NULL"), nullable=True
    )
    patient_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("patients.id", ondelete="SET NULL"), nullable=True
    )
    requested_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    task_input: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    draft_output: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(
        String(30), nullable=False, default=AgentTaskStatus.PENDING, index=True
    )
    approved_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
