import uuid
from typing import Sequence
from sqlalchemy import select, or_, func, text
from sqlalchemy.orm import selectinload
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.patients.patients.models import Patient
from app.core.patients.patients.schemas import PatientCreate, PatientUpdate
from app.core.patients.identifiers.models import PatientIdentifier
from app.core.patients.contacts.models import PatientContact

class DuplicateResult:
    def __init__(self, patient: Patient, confidence_score: float):
        self.patient = patient
        self.confidence_score = confidence_score

from app.core.auth.models import User

class PatientService:
    def __init__(self, db: AsyncSession, user: User = None):
        self.db = db
        self.user = user

    def _apply_tenant_filter(self, stmt):
        if self.user and getattr(self.user, 'org_id', None):
            return stmt.where(Patient.org_id == self.user.org_id)
        return stmt

    async def create_patient(self, data: PatientCreate) -> Patient:
        # Check for absolute matches on unique fields before insert (e.g. UUID)
        # But uuid is generated by us. We generate a globally unique patient_uuid
        patient_uuid = f"AX-{uuid.uuid4().hex[:8].upper()}"
        
        patient = Patient(
            patient_uuid=patient_uuid,
            first_name=data.first_name,
            last_name=data.last_name,
            date_of_birth=data.date_of_birth,
            gender=data.gender,
            primary_phone=data.primary_phone,
            email=data.email,
            org_id=self.user.org_id if self.user and getattr(self.user, 'org_id', None) else None
        )
        self.db.add(patient)
        await self.db.flush()
        
        # Eager load relationships to avoid MissingGreenlet error during Pydantic serialization
        return await self.get_patient_by_id(patient.id)

    async def get_patient_by_id(self, patient_id: uuid.UUID) -> Patient | None:
        stmt = (
            select(Patient)
            .options(
                selectinload(Patient.identifiers),
                selectinload(Patient.contacts),
                selectinload(Patient.guardians),
                selectinload(Patient.insurance),
                selectinload(Patient.consents),
                selectinload(Patient.appointments)
            )
            .where(Patient.id == patient_id)
        )
        stmt = self._apply_tenant_filter(stmt)
        result = await self.db.execute(stmt)
        return result.scalar_one_or_none()

    async def update_patient(self, patient: Patient, data: PatientUpdate) -> Patient:
        update_data = data.model_dump(exclude_unset=True)
        for key, value in update_data.items():
            setattr(patient, key, value)
        await self.db.flush()
        return patient

    async def list_patients(self, skip: int = 0, limit: int = 20) -> Sequence[Patient]:
        stmt = (
            select(Patient)
            .options(
                selectinload(Patient.identifiers),
                selectinload(Patient.contacts),
                selectinload(Patient.guardians),
                selectinload(Patient.insurance),
                selectinload(Patient.consents),
                selectinload(Patient.appointments)
            )
            .offset(skip)
            .limit(limit)
        )
        stmt = self._apply_tenant_filter(stmt)
        result = await self.db.execute(stmt)
        return result.scalars().unique().all()

    async def detect_duplicates(self, first_name: str, last_name: str, date_of_birth: str, phone: str | None = None) -> list[DuplicateResult]:
        """
        Duplicate engine using fuzzy matching.
        Using similarity function from pg_trgm.
        """
        # Thresholds
        SIMILARITY_THRESHOLD = 0.4
        
        # Combine name for full-text / trigram
        search_name = f"{first_name} {last_name}"
        
        # Parse date_of_birth if it's a string
        target_dob = date_of_birth
        if isinstance(date_of_birth, str):
            from datetime import date as py_date
            try:
                target_dob = py_date.fromisoformat(date_of_birth)
            except Exception:
                pass

        # We find patients that matched on exact DOB, OR fuzzy match on name.
        stmt = select(Patient).where(
            or_(
                Patient.date_of_birth == target_dob,
                func.similarity(func.concat(Patient.first_name, ' ', Patient.last_name), search_name) > SIMILARITY_THRESHOLD,
                Patient.primary_phone == (phone if phone else "xxx")
            )
        )
        stmt = self._apply_tenant_filter(stmt)
        
        result = await self.db.execute(stmt)
        patients = result.scalars().all()
        
        duplicates = []
        for p in patients:
            score = 0.0
            
            # Simple scoring algo
            # 1. Exact Name = 40 points, Fuzzy Name = proportional (max 40)
            # Cannot call func.similarity directly in Python, so do basic logic:
            if p.first_name.lower() == first_name.lower() and p.last_name.lower() == last_name.lower():
                score += 40
            elif p.last_name.lower() == last_name.lower() or p.first_name.lower() == first_name.lower():
                score += 20
                
            # 2. Exact DOB = 30 points
            if str(p.date_of_birth) == str(date_of_birth):
                score += 30
                
            # 3. Phone = 30 points
            if phone and p.primary_phone == phone:
                score += 30
                
            if score >= 30: # Minimum to be flagged as possible duplicate
                duplicates.append(DuplicateResult(patient=p, confidence_score=score))
                
        # Sort by score descending
        duplicates.sort(key=lambda x: x.confidence_score, reverse=True)
        return duplicates

    async def search_patients(self, query: str, limit: int = 20) -> Sequence[Patient]:
        """
        Enterprise patient search engine:
        Supports name search, phone search, patient_id search.
        """
        stmt = (
            select(Patient)
            .outerjoin(PatientIdentifier)
            .outerjoin(PatientContact)
            .where(
                or_(
                    func.similarity(func.concat(Patient.first_name, ' ', Patient.last_name), query) > 0.3,
                    Patient.patient_uuid.ilike(f"%{query}%"),
                    Patient.primary_phone.ilike(f"%{query}%"),
                    PatientContact.contact_value.ilike(f"%{query}%"),
                    PatientIdentifier.identifier_value.ilike(f"%{query}%")
                )
            )
        )
        stmt = self._apply_tenant_filter(stmt)
        stmt = stmt.limit(limit)
        # Add loaders for output
        stmt = stmt.options(
            selectinload(Patient.identifiers),
            selectinload(Patient.contacts),
            selectinload(Patient.guardians),
            selectinload(Patient.insurance),
            selectinload(Patient.consents),
            selectinload(Patient.appointments)
        )

        result = await self.db.execute(stmt)
        # Distinct avoids duplication from joins
        return result.scalars().unique().all()
