"""Analyzer Engine Models

Revision ID: 01f3fa824e9e
Revises: a8ea5db785c5
Create Date: 2026-03-23 17:10:09.024318
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01f3fa824e9e'
down_revision: Union[str, None] = 'a8ea5db785c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lis_analyzer_device',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_code', sa.String(length=50), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('connection_string', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_communication', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_maintenance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_code_mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_format_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_analyzer_device_department'), 'lis_analyzer_device', ['department'], unique=False)
    op.create_index(op.f('ix_lis_analyzer_device_device_code'), 'lis_analyzer_device', ['device_code'], unique=True)
    op.create_index(op.f('ix_lis_analyzer_device_status'), 'lis_analyzer_device', ['status'], unique=False)
    op.create_table('lis_device_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('data_transmitted', sa.Text(), nullable=True),
    sa.Column('data_received', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_device_audit_action'), 'lis_device_audit', ['action'], unique=False)
    op.create_index(op.f('ix_lis_device_audit_device_id'), 'lis_device_audit', ['device_id'], unique=False)
    op.create_table('lis_analyzer_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('worklist_id', sa.UUID(), nullable=True),
    sa.Column('sample_id', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('analyzer_test_code', sa.String(length=50), nullable=True),
    sa.Column('result_value', sa.Text(), nullable=True),
    sa.Column('result_numeric', sa.Float(), nullable=True),
    sa.Column('result_unit', sa.String(length=30), nullable=True),
    sa.Column('result_flag', sa.String(length=20), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('is_qc_sample', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['lis_analyzer_device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_analyzer_result_device_id'), 'lis_analyzer_result', ['device_id'], unique=False)
    op.create_index(op.f('ix_lis_analyzer_result_sample_id'), 'lis_analyzer_result', ['sample_id'], unique=False)
    op.create_index(op.f('ix_lis_analyzer_result_status'), 'lis_analyzer_result', ['status'], unique=False)
    op.create_index(op.f('ix_lis_analyzer_result_worklist_id'), 'lis_analyzer_result', ['worklist_id'], unique=False)
    op.create_table('lis_analyzer_worklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('patient_uhid', sa.String(length=50), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('analyzer_test_code', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['lis_analyzer_device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_analyzer_worklist_barcode'), 'lis_analyzer_worklist', ['barcode'], unique=False)
    op.create_index(op.f('ix_lis_analyzer_worklist_device_id'), 'lis_analyzer_worklist', ['device_id'], unique=False)
    op.create_index(op.f('ix_lis_analyzer_worklist_sample_id'), 'lis_analyzer_worklist', ['sample_id'], unique=False)
    op.create_index(op.f('ix_lis_analyzer_worklist_status'), 'lis_analyzer_worklist', ['status'], unique=False)
    op.create_table('lis_device_error',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['lis_analyzer_device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_device_error_device_id'), 'lis_device_error', ['device_id'], unique=False)
    op.create_table('lis_reagent_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('reagent_name', sa.String(length=255), nullable=False),
    sa.Column('reagent_lot', sa.String(length=100), nullable=True),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('quantity_used', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=True),
    sa.Column('reorder_level', sa.Float(), nullable=True),
    sa.Column('is_low_stock', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['lis_analyzer_device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_reagent_usage_device_id'), 'lis_reagent_usage', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lis_reagent_usage_device_id'), table_name='lis_reagent_usage')
    op.drop_table('lis_reagent_usage')
    op.drop_index(op.f('ix_lis_device_error_device_id'), table_name='lis_device_error')
    op.drop_table('lis_device_error')
    op.drop_index(op.f('ix_lis_analyzer_worklist_status'), table_name='lis_analyzer_worklist')
    op.drop_index(op.f('ix_lis_analyzer_worklist_sample_id'), table_name='lis_analyzer_worklist')
    op.drop_index(op.f('ix_lis_analyzer_worklist_device_id'), table_name='lis_analyzer_worklist')
    op.drop_index(op.f('ix_lis_analyzer_worklist_barcode'), table_name='lis_analyzer_worklist')
    op.drop_table('lis_analyzer_worklist')
    op.drop_index(op.f('ix_lis_analyzer_result_worklist_id'), table_name='lis_analyzer_result')
    op.drop_index(op.f('ix_lis_analyzer_result_status'), table_name='lis_analyzer_result')
    op.drop_index(op.f('ix_lis_analyzer_result_sample_id'), table_name='lis_analyzer_result')
    op.drop_index(op.f('ix_lis_analyzer_result_device_id'), table_name='lis_analyzer_result')
    op.drop_table('lis_analyzer_result')
    op.drop_index(op.f('ix_lis_device_audit_device_id'), table_name='lis_device_audit')
    op.drop_index(op.f('ix_lis_device_audit_action'), table_name='lis_device_audit')
    op.drop_table('lis_device_audit')
    op.drop_index(op.f('ix_lis_analyzer_device_status'), table_name='lis_analyzer_device')
    op.drop_index(op.f('ix_lis_analyzer_device_device_code'), table_name='lis_analyzer_device')
    op.drop_index(op.f('ix_lis_analyzer_device_department'), table_name='lis_analyzer_device')
    op.drop_table('lis_analyzer_device')
    # ### end Alembic commands ###
