"""add_order_templates_and_sets

Revision ID: 0467c51d8416
Revises: fa24e3ed747f
Create Date: 2026-03-16 14:56:05.111424
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0467c51d8416'
down_revision: Union[str, None] = 'fa24e3ed747f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('set_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('clinical_context', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_sets_set_name'), 'order_sets', ['set_name'], unique=False)
    op.create_table('order_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_type', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_templates_template_name'), 'order_templates', ['template_name'], unique=False)
    op.create_table('order_set_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('set_id', sa.UUID(), nullable=False),
    sa.Column('order_type', sa.String(length=30), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('default_quantity', sa.Float(), nullable=False),
    sa.Column('default_instructions', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['order_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_set_items_set_id'), 'order_set_items', ['set_id'], unique=False)
    op.create_table('order_template_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('default_quantity', sa.Float(), nullable=False),
    sa.Column('default_instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['order_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_template_items_template_id'), 'order_template_items', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_template_items_template_id'), table_name='order_template_items')
    op.drop_table('order_template_items')
    op.drop_index(op.f('ix_order_set_items_set_id'), table_name='order_set_items')
    op.drop_table('order_set_items')
    op.drop_index(op.f('ix_order_templates_template_name'), table_name='order_templates')
    op.drop_table('order_templates')
    op.drop_index(op.f('ix_order_sets_set_name'), table_name='order_sets')
    op.drop_table('order_sets')
    # ### end Alembic commands ###
