"""smart_queue_orchestration

Revision ID: 145b1ea3e4bf
Revises: fad1c641d064
Create Date: 2026-03-23 10:43:31.745196
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '145b1ea3e4bf'
down_revision: Union[str, None] = 'fad1c641d064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('queue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('room_status', sa.String(length=30), nullable=True),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('current_length', sa.Integer(), nullable=True),
    sa.Column('avg_consult_time_min', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_queue_master_date', 'queue_master', ['queue_date'], unique=False)
    op.create_index('ix_queue_master_doctor', 'queue_master', ['doctor_id'], unique=False)
    op.create_table('queue_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_room_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('wayfinding_node_id', sa.String(length=50), nullable=True),
    sa.Column('display_instructions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_number')
    )
    op.create_table('queue_wait_time_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('predicted_peak_start', sa.String(length=10), nullable=True),
    sa.Column('predicted_peak_end', sa.String(length=10), nullable=True),
    sa.Column('predicted_inflow_count', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('factors_used', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prediction_date', 'queue_wait_time_predictions', ['prediction_date'], unique=False)
    op.create_table('wayfinding_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=50), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('directions_from_parent', sa.Text(), nullable=True),
    sa.Column('parent_node_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_table('queue_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('queue_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_details', sa.JSON(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['queue_id'], ['queue_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_queue_events_visit', 'queue_events', ['visit_id'], unique=False)
    op.create_table('queue_patient_position',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('queue_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('priority_level', sa.String(length=30), nullable=True),
    sa.Column('calculated_priority_score', sa.Integer(), nullable=True),
    sa.Column('position_number', sa.Integer(), nullable=True),
    sa.Column('estimated_wait_time_min', sa.Integer(), nullable=True),
    sa.Column('estimated_call_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('missed_calls_count', sa.Integer(), nullable=True),
    sa.Column('last_called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consultation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consultation_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['queue_id'], ['queue_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_index('ix_queue_patient_queue', 'queue_patient_position', ['queue_id'], unique=False)
    op.create_index('ix_queue_patient_status', 'queue_patient_position', ['status'], unique=False)
    op.create_index('ix_queue_patient_visit', 'queue_patient_position', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_queue_patient_visit', table_name='queue_patient_position')
    op.drop_index('ix_queue_patient_status', table_name='queue_patient_position')
    op.drop_index('ix_queue_patient_queue', table_name='queue_patient_position')
    op.drop_table('queue_patient_position')
    op.drop_index('ix_queue_events_visit', table_name='queue_events')
    op.drop_table('queue_events')
    op.drop_table('wayfinding_nodes')
    op.drop_index('ix_prediction_date', table_name='queue_wait_time_predictions')
    op.drop_table('queue_wait_time_predictions')
    op.drop_table('queue_room_mapping')
    op.drop_table('queue_notifications')
    op.drop_index('ix_queue_master_doctor', table_name='queue_master')
    op.drop_index('ix_queue_master_date', table_name='queue_master')
    op.drop_table('queue_master')
    # ### end Alembic commands ###
