"""Drop duplicate IPD beds and fix references

Revision ID: 1b7db9a40792
Revises: 7d4287c9ba5b
Create Date: 2026-03-24 06:52:16.587151
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b7db9a40792'
down_revision: Union[str, None] = '7d4287c9ba5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ipd_admission_records_bed_uuid_fkey'), 'ipd_admission_records', type_='foreignkey')
    op.drop_table('ipd_bed_status')
    op.drop_table('ipd_bed_reservations')
    op.drop_index(op.f('ix_ipd_bed_master_bed_id'), table_name='ipd_bed_master')
    op.drop_table('ipd_bed_master')
    op.create_foreign_key(None, 'ipd_admission_records', 'beds', ['bed_uuid'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ipd_admission_records', type_='foreignkey')
    op.create_foreign_key(op.f('ipd_admission_records_bed_uuid_fkey'), 'ipd_admission_records', 'ipd_bed_master', ['bed_uuid'], ['id'], ondelete='RESTRICT')
    op.create_table('ipd_bed_reservations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bed_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_uhid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('doctor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reservation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bed_uuid'], ['ipd_bed_master.id'], name=op.f('ipd_bed_reservations_bed_uuid_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ipd_bed_reservations_pkey'))
    )
    op.create_table('ipd_bed_status',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bed_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('current_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('patient_uhid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admission_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bed_uuid'], ['ipd_bed_master.id'], name=op.f('ipd_bed_status_bed_uuid_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ipd_bed_status_pkey'))
    )
    op.create_table('ipd_bed_master',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bed_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ward', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('floor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bed_category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ipd_bed_master_pkey'))
    )
    op.create_index(op.f('ix_ipd_bed_master_bed_id'), 'ipd_bed_master', ['bed_id'], unique=True)
    # ### end Alembic commands ###
