"""Phase 22: Visitor and MLC Engine

Revision ID: 1e9fbd73c980
Revises: c23bbfe6bb64
Create Date: 2026-03-24 10:51:41.139082
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9fbd73c980'
down_revision: Union[str, None] = 'c23bbfe6bb64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipd_security_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_mlc_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('case_type', sa.String(), nullable=False),
    sa.Column('incident_details', sa.Text(), nullable=True),
    sa.Column('police_station', sa.String(), nullable=True),
    sa.Column('fir_number', sa.String(), nullable=True),
    sa.Column('officer_name', sa.String(), nullable=True),
    sa.Column('officer_badge', sa.String(), nullable=True),
    sa.Column('registered_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_number')
    )
    op.create_table('ipd_visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('visitor_name', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=False),
    sa.Column('id_proof', sa.String(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_mlc_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mlc_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mlc_id'], ['ipd_mlc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_visitor_passes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pass_number', sa.String(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('ward_name', sa.String(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('pass_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['ipd_visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipd_visitor_passes_pass_number'), 'ipd_visitor_passes', ['pass_number'], unique=True)
    op.create_table('ipd_visitor_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pass_number', sa.String(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkpoint', sa.String(), nullable=False),
    sa.Column('security_guard_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pass_number'], ['ipd_visitor_passes.pass_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipd_visitor_logs')
    op.drop_index(op.f('ix_ipd_visitor_passes_pass_number'), table_name='ipd_visitor_passes')
    op.drop_table('ipd_visitor_passes')
    op.drop_table('ipd_mlc_documents')
    op.drop_table('ipd_visitors')
    op.drop_table('ipd_mlc_cases')
    op.drop_table('ipd_security_notifications')
    # ### end Alembic commands ###
