"""robust_billing_insurance

Revision ID: 1fc2897c873e
Revises: 489a1dc0872a
Create Date: 2026-03-18 04:35:14.061722
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc2897c873e'
down_revision: Union[str, None] = '489a1dc0872a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('package_name', sa.String(length=200), nullable=False),
    sa.Column('default_co_pay_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('default_deductible', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('annual_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('coverage_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['insurance_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_authorizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('auth_code', sa.String(length=100), nullable=True),
    sa.Column('request_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('request_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinical_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['insurance_providers.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['billing_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_authorizations_patient_id'), 'pre_authorizations', ['patient_id'], unique=False)
    op.create_table('claim_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('billing_entry_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['billing_entry_id'], ['billing_entries.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['insurance_claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('insurance_claims', sa.Column('claim_number', sa.String(length=100), nullable=True))
    op.add_column('insurance_claims', sa.Column('allowed_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('insurance_claims', sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('insurance_claims', sa.Column('rejection_reason', sa.String(length=500), nullable=True))
    op.add_column('insurance_claims', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_insurance_claims_claim_number'), 'insurance_claims', ['claim_number'], unique=True)
    op.add_column('insurance_policies', sa.Column('package_id', sa.UUID(), nullable=False))
    op.add_column('insurance_policies', sa.Column('priority', sa.Numeric(precision=2, scale=0), nullable=True))
    op.add_column('insurance_policies', sa.Column('group_number', sa.String(length=100), nullable=True))
    op.add_column('insurance_policies', sa.Column('status', sa.String(length=20), nullable=True))
    op.drop_index(op.f('ix_insurance_policies_provider_id'), table_name='insurance_policies')
    op.drop_constraint(op.f('insurance_policies_provider_id_fkey'), 'insurance_policies', type_='foreignkey')
    op.create_foreign_key(None, 'insurance_policies', 'insurance_packages', ['package_id'], ['id'], ondelete='CASCADE')
    op.drop_column('insurance_policies', 'provider_id')
    op.drop_column('insurance_policies', 'coverage_percentage')
    op.add_column('insurance_providers', sa.Column('provider_code', sa.String(length=50), nullable=True))
    op.add_column('insurance_providers', sa.Column('billing_address', sa.String(length=500), nullable=True))
    op.add_column('insurance_providers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'insurance_providers', ['provider_code'])
    op.drop_column('insurance_providers', 'policy_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_providers', sa.Column('policy_rules', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'insurance_providers', type_='unique')
    op.drop_column('insurance_providers', 'is_active')
    op.drop_column('insurance_providers', 'billing_address')
    op.drop_column('insurance_providers', 'provider_code')
    op.add_column('insurance_policies', sa.Column('coverage_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('insurance_policies', sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'insurance_policies', type_='foreignkey')
    op.create_foreign_key(op.f('insurance_policies_provider_id_fkey'), 'insurance_policies', 'insurance_providers', ['provider_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_insurance_policies_provider_id'), 'insurance_policies', ['provider_id'], unique=False)
    op.drop_column('insurance_policies', 'status')
    op.drop_column('insurance_policies', 'group_number')
    op.drop_column('insurance_policies', 'priority')
    op.drop_column('insurance_policies', 'package_id')
    op.drop_index(op.f('ix_insurance_claims_claim_number'), table_name='insurance_claims')
    op.drop_column('insurance_claims', 'last_updated')
    op.drop_column('insurance_claims', 'rejection_reason')
    op.drop_column('insurance_claims', 'paid_amount')
    op.drop_column('insurance_claims', 'allowed_amount')
    op.drop_column('insurance_claims', 'claim_number')
    op.drop_table('claim_items')
    op.drop_index(op.f('ix_pre_authorizations_patient_id'), table_name='pre_authorizations')
    op.drop_table('pre_authorizations')
    op.drop_table('insurance_packages')
    # ### end Alembic commands ###
