"""Add pharmacy sales worklist engine

Revision ID: 24c0f8c59702
Revises: 3350e68307b3
Create Date: 2026-03-25 08:21:02.857134
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24c0f8c59702'
down_revision: Union[str, None] = '3350e68307b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_dispense_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worklist_id', sa.UUID(), nullable=False),
    sa.Column('pharmacist_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('billing_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_dispense_logs_worklist_id'), 'pharmacy_dispense_logs', ['worklist_id'], unique=False)
    op.create_table('pharmacy_sales_worklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('patient_name', sa.String(length=200), nullable=True),
    sa.Column('uhid', sa.String(length=50), nullable=True),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('doctor_name', sa.String(length=200), nullable=True),
    sa.Column('prescription_id', sa.UUID(), nullable=True),
    sa.Column('prescription_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_sales_worklist_patient_id'), 'pharmacy_sales_worklist', ['patient_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_sales_worklist_prescription_id'), 'pharmacy_sales_worklist', ['prescription_id'], unique=False)
    op.create_table('pharmacy_worklist_prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worklist_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=True),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('dosage_instructions', sa.String(length=500), nullable=True),
    sa.Column('quantity_prescribed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('is_non_formulary', sa.Boolean(), nullable=True),
    sa.Column('substituted_for', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['worklist_id'], ['pharmacy_sales_worklist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_worklist_prescriptions_worklist_id'), 'pharmacy_worklist_prescriptions', ['worklist_id'], unique=False)
    op.create_table('pharmacy_dispensing_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worklist_id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=True),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('quantity_dispensed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dosage_instructions', sa.String(length=500), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dispensed_by', sa.UUID(), nullable=True),
    sa.Column('dispensed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dispensed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prescription_id'], ['pharmacy_prescriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worklist_id'], ['pharmacy_sales_worklist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_dispensing_records_worklist_id'), 'pharmacy_dispensing_records', ['worklist_id'], unique=False)
    op.create_table('pharmacy_dispense_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispense_record_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dispense_record_id'], ['pharmacy_dispensing_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_dispense_batches_dispense_record_id'), 'pharmacy_dispense_batches', ['dispense_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_dispense_batches_dispense_record_id'), table_name='pharmacy_dispense_batches')
    op.drop_table('pharmacy_dispense_batches')
    op.drop_index(op.f('ix_pharmacy_dispensing_records_worklist_id'), table_name='pharmacy_dispensing_records')
    op.drop_table('pharmacy_dispensing_records')
    op.drop_index(op.f('ix_pharmacy_worklist_prescriptions_worklist_id'), table_name='pharmacy_worklist_prescriptions')
    op.drop_table('pharmacy_worklist_prescriptions')
    op.drop_index(op.f('ix_pharmacy_sales_worklist_prescription_id'), table_name='pharmacy_sales_worklist')
    op.drop_index(op.f('ix_pharmacy_sales_worklist_patient_id'), table_name='pharmacy_sales_worklist')
    op.drop_table('pharmacy_sales_worklist')
    op.drop_index(op.f('ix_pharmacy_dispense_logs_worklist_id'), table_name='pharmacy_dispense_logs')
    op.drop_table('pharmacy_dispense_logs')
    # ### end Alembic commands ###
