"""lis_phlebotomy_sample_collection_engine

Revision ID: 28a0d958374a
Revises: c9dc24290877
Create Date: 2026-03-23 13:00:26.967968
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28a0d958374a'
down_revision: Union[str, None] = 'c9dc24290877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lis_phlebotomy_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_phlebotomy_audit_action'), 'lis_phlebotomy_audit', ['action'], unique=False)
    op.create_table('lis_phlebotomy_worklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('patient_uhid', sa.String(length=50), nullable=True),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('sample_type', sa.String(length=30), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('collection_location', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('consent_required', sa.Boolean(), nullable=False),
    sa.Column('consent_uploaded', sa.Boolean(), nullable=False),
    sa.Column('assigned_collector', sa.String(length=255), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_repeat', sa.Boolean(), nullable=False),
    sa.Column('repeat_schedule_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_phlebotomy_worklist_barcode'), 'lis_phlebotomy_worklist', ['barcode'], unique=False)
    op.create_index(op.f('ix_lis_phlebotomy_worklist_order_id'), 'lis_phlebotomy_worklist', ['order_id'], unique=False)
    op.create_index(op.f('ix_lis_phlebotomy_worklist_order_item_id'), 'lis_phlebotomy_worklist', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_lis_phlebotomy_worklist_patient_id'), 'lis_phlebotomy_worklist', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lis_phlebotomy_worklist_priority'), 'lis_phlebotomy_worklist', ['priority'], unique=False)
    op.create_index(op.f('ix_lis_phlebotomy_worklist_status'), 'lis_phlebotomy_worklist', ['status'], unique=False)
    op.create_table('lis_repeat_sample_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('total_samples', sa.Integer(), nullable=False),
    sa.Column('collected_count', sa.Integer(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('schedule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lis_sample_transport',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('sample_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('transport_personnel', sa.String(length=255), nullable=False),
    sa.Column('transport_method', sa.String(length=50), nullable=False),
    sa.Column('dispatch_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_by', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_sample_transport_batch_id'), 'lis_sample_transport', ['batch_id'], unique=True)
    op.create_table('lis_consent_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worklist_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['worklist_id'], ['lis_phlebotomy_worklist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_consent_documents_worklist_id'), 'lis_consent_documents', ['worklist_id'], unique=False)
    op.create_table('lis_sample_collection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worklist_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('patient_uhid', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('sample_type', sa.String(length=30), nullable=False),
    sa.Column('container_type', sa.String(length=30), nullable=False),
    sa.Column('collection_location', sa.String(length=30), nullable=False),
    sa.Column('collector_name', sa.String(length=255), nullable=False),
    sa.Column('collector_id', sa.UUID(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('identity_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quantity_ml', sa.Float(), nullable=True),
    sa.Column('status_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['worklist_id'], ['lis_phlebotomy_worklist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_sample_collection_barcode'), 'lis_sample_collection', ['barcode'], unique=False)
    op.create_index(op.f('ix_lis_sample_collection_sample_id'), 'lis_sample_collection', ['sample_id'], unique=True)
    op.create_index(op.f('ix_lis_sample_collection_worklist_id'), 'lis_sample_collection', ['worklist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lis_sample_collection_worklist_id'), table_name='lis_sample_collection')
    op.drop_index(op.f('ix_lis_sample_collection_sample_id'), table_name='lis_sample_collection')
    op.drop_index(op.f('ix_lis_sample_collection_barcode'), table_name='lis_sample_collection')
    op.drop_table('lis_sample_collection')
    op.drop_index(op.f('ix_lis_consent_documents_worklist_id'), table_name='lis_consent_documents')
    op.drop_table('lis_consent_documents')
    op.drop_index(op.f('ix_lis_sample_transport_batch_id'), table_name='lis_sample_transport')
    op.drop_table('lis_sample_transport')
    op.drop_table('lis_repeat_sample_schedule')
    op.drop_index(op.f('ix_lis_phlebotomy_worklist_status'), table_name='lis_phlebotomy_worklist')
    op.drop_index(op.f('ix_lis_phlebotomy_worklist_priority'), table_name='lis_phlebotomy_worklist')
    op.drop_index(op.f('ix_lis_phlebotomy_worklist_patient_id'), table_name='lis_phlebotomy_worklist')
    op.drop_index(op.f('ix_lis_phlebotomy_worklist_order_item_id'), table_name='lis_phlebotomy_worklist')
    op.drop_index(op.f('ix_lis_phlebotomy_worklist_order_id'), table_name='lis_phlebotomy_worklist')
    op.drop_index(op.f('ix_lis_phlebotomy_worklist_barcode'), table_name='lis_phlebotomy_worklist')
    op.drop_table('lis_phlebotomy_worklist')
    op.drop_index(op.f('ix_lis_phlebotomy_audit_action'), table_name='lis_phlebotomy_audit')
    op.drop_table('lis_phlebotomy_audit')
    # ### end Alembic commands ###
