"""Add Pharmacy Billing and Compliance Models

Revision ID: 2a7e436dcd3f
Revises: 9a577cf236ee
Create Date: 2026-03-25 11:33:49.531603
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7e436dcd3f'
down_revision: Union[str, None] = '9a577cf236ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_billing_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('action_details', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_billing_audit_logs_bill_id'), 'pharmacy_billing_audit_logs', ['bill_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_billing_audit_logs_id'), 'pharmacy_billing_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacy_billing_audit_logs_patient_id'), 'pharmacy_billing_audit_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_billing_audit_logs_timestamp'), 'pharmacy_billing_audit_logs', ['timestamp'], unique=False)
    op.create_table('pharmacy_billing_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('bill_number', sa.String(), nullable=True),
    sa.Column('billing_type', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('net_payable', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('bill_items', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_billing_records_bill_number'), 'pharmacy_billing_records', ['bill_number'], unique=True)
    op.create_index(op.f('ix_pharmacy_billing_records_billing_type'), 'pharmacy_billing_records', ['billing_type'], unique=False)
    op.create_index(op.f('ix_pharmacy_billing_records_encounter_id'), 'pharmacy_billing_records', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_billing_records_id'), 'pharmacy_billing_records', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacy_billing_records_patient_id'), 'pharmacy_billing_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_billing_records_payment_status'), 'pharmacy_billing_records', ['payment_status'], unique=False)
    op.create_table('pharmacy_financial_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('data_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_financial_reports_id'), 'pharmacy_financial_reports', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacy_financial_reports_report_type'), 'pharmacy_financial_reports', ['report_type'], unique=False)
    op.create_table('pharmacy_discount_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=True),
    sa.Column('discount_type', sa.String(), nullable=True),
    sa.Column('discount_mode', sa.String(), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('authorized_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['pharmacy_billing_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_discount_records_bill_id'), 'pharmacy_discount_records', ['bill_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_discount_records_id'), 'pharmacy_discount_records', ['id'], unique=False)
    op.create_table('pharmacy_payment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=True),
    sa.Column('receipt_number', sa.String(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('payment_mode', sa.String(), nullable=True),
    sa.Column('transaction_reference', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('cashier_id', sa.UUID(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['pharmacy_billing_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_payment_transactions_bill_id'), 'pharmacy_payment_transactions', ['bill_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_payment_transactions_id'), 'pharmacy_payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacy_payment_transactions_receipt_number'), 'pharmacy_payment_transactions', ['receipt_number'], unique=True)
    op.create_table('pharmacy_refund_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('refund_mode', sa.String(), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('authorized_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['pharmacy_billing_records.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['pharmacy_payment_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_refund_records_bill_id'), 'pharmacy_refund_records', ['bill_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_refund_records_id'), 'pharmacy_refund_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_refund_records_id'), table_name='pharmacy_refund_records')
    op.drop_index(op.f('ix_pharmacy_refund_records_bill_id'), table_name='pharmacy_refund_records')
    op.drop_table('pharmacy_refund_records')
    op.drop_index(op.f('ix_pharmacy_payment_transactions_receipt_number'), table_name='pharmacy_payment_transactions')
    op.drop_index(op.f('ix_pharmacy_payment_transactions_id'), table_name='pharmacy_payment_transactions')
    op.drop_index(op.f('ix_pharmacy_payment_transactions_bill_id'), table_name='pharmacy_payment_transactions')
    op.drop_table('pharmacy_payment_transactions')
    op.drop_index(op.f('ix_pharmacy_discount_records_id'), table_name='pharmacy_discount_records')
    op.drop_index(op.f('ix_pharmacy_discount_records_bill_id'), table_name='pharmacy_discount_records')
    op.drop_table('pharmacy_discount_records')
    op.drop_index(op.f('ix_pharmacy_financial_reports_report_type'), table_name='pharmacy_financial_reports')
    op.drop_index(op.f('ix_pharmacy_financial_reports_id'), table_name='pharmacy_financial_reports')
    op.drop_table('pharmacy_financial_reports')
    op.drop_index(op.f('ix_pharmacy_billing_records_payment_status'), table_name='pharmacy_billing_records')
    op.drop_index(op.f('ix_pharmacy_billing_records_patient_id'), table_name='pharmacy_billing_records')
    op.drop_index(op.f('ix_pharmacy_billing_records_id'), table_name='pharmacy_billing_records')
    op.drop_index(op.f('ix_pharmacy_billing_records_encounter_id'), table_name='pharmacy_billing_records')
    op.drop_index(op.f('ix_pharmacy_billing_records_billing_type'), table_name='pharmacy_billing_records')
    op.drop_index(op.f('ix_pharmacy_billing_records_bill_number'), table_name='pharmacy_billing_records')
    op.drop_table('pharmacy_billing_records')
    op.drop_index(op.f('ix_pharmacy_billing_audit_logs_timestamp'), table_name='pharmacy_billing_audit_logs')
    op.drop_index(op.f('ix_pharmacy_billing_audit_logs_patient_id'), table_name='pharmacy_billing_audit_logs')
    op.drop_index(op.f('ix_pharmacy_billing_audit_logs_id'), table_name='pharmacy_billing_audit_logs')
    op.drop_index(op.f('ix_pharmacy_billing_audit_logs_bill_id'), table_name='pharmacy_billing_audit_logs')
    op.drop_table('pharmacy_billing_audit_logs')
    # ### end Alembic commands ###
