"""Add phase 2 patient models

Revision ID: 2cae45fb6cf7
Revises: 2329cd0b16b6
Create Date: 2026-03-16 12:09:23.070990
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cae45fb6cf7'
down_revision: Union[str, None] = '2329cd0b16b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('appointment_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_time'), 'appointments', ['appointment_time'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_table('patient_consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=100), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=False),
    sa.Column('signature_file_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_consents_patient_id'), 'patient_consents', ['patient_id'], unique=False)
    op.create_table('patient_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('contact_type', sa.String(length=50), nullable=False),
    sa.Column('contact_value', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_contacts_patient_id'), 'patient_contacts', ['patient_id'], unique=False)
    op.create_table('patient_guardians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('guardian_name', sa.String(length=150), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_guardians_patient_id'), 'patient_guardians', ['patient_id'], unique=False)
    op.create_table('patient_identifiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('identifier_type', sa.String(length=50), nullable=False),
    sa.Column('identifier_value', sa.String(length=100), nullable=False),
    sa.Column('issuing_authority', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_identifiers_identifier_value'), 'patient_identifiers', ['identifier_value'], unique=False)
    op.create_index(op.f('ix_patient_identifiers_patient_id'), 'patient_identifiers', ['patient_id'], unique=False)
    op.create_table('patient_insurance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('insurance_provider', sa.String(length=150), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('coverage_type', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_insurance_patient_id'), 'patient_insurance', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_insurance_policy_number'), 'patient_insurance', ['policy_number'], unique=False)
    op.add_column('patients', sa.Column('patient_uuid', sa.String(length=50), nullable=False))
    op.add_column('patients', sa.Column('primary_phone', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('patients', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('patients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.create_index(op.f('ix_patients_patient_uuid'), 'patients', ['patient_uuid'], unique=True)
    op.drop_column('patients', 'emergency_contact_phone')
    op.drop_column('patients', 'address')
    op.drop_column('patients', 'emergency_contact_name')
    op.drop_column('patients', 'phone')
    op.drop_column('patients', 'allergies')
    op.drop_column('patients', 'mrn')
    op.drop_column('patients', 'blood_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('blood_group', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('mrn', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_patients_patient_uuid'), table_name='patients')
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=True)
    op.alter_column('patients', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('patients', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('patients', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('patients', 'status')
    op.drop_column('patients', 'primary_phone')
    op.drop_column('patients', 'patient_uuid')
    op.drop_index(op.f('ix_patient_insurance_policy_number'), table_name='patient_insurance')
    op.drop_index(op.f('ix_patient_insurance_patient_id'), table_name='patient_insurance')
    op.drop_table('patient_insurance')
    op.drop_index(op.f('ix_patient_identifiers_patient_id'), table_name='patient_identifiers')
    op.drop_index(op.f('ix_patient_identifiers_identifier_value'), table_name='patient_identifiers')
    op.drop_table('patient_identifiers')
    op.drop_index(op.f('ix_patient_guardians_patient_id'), table_name='patient_guardians')
    op.drop_table('patient_guardians')
    op.drop_index(op.f('ix_patient_contacts_patient_id'), table_name='patient_contacts')
    op.drop_table('patient_contacts')
    op.drop_index(op.f('ix_patient_consents_patient_id'), table_name='patient_consents')
    op.drop_table('patient_consents')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_time'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
