"""Phase12_CDSS_Engine

Revision ID: 2d322d91a310
Revises: 77872b36d539
Create Date: 2026-03-17 12:06:22.121399
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d322d91a310'
down_revision: Union[str, None] = '77872b36d539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdss_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('is_overridden', sa.Boolean(), nullable=True),
    sa.Column('overridden_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_allergy_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('allergy_type', sa.String(length=100), nullable=False),
    sa.Column('drug_class', sa.String(length=100), nullable=False),
    sa.Column('reaction_risk', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.String(length=100), nullable=False),
    sa.Column('drug_class', sa.String(length=100), nullable=False),
    sa.Column('therapeutic_group', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_contraindications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.String(length=100), nullable=False),
    sa.Column('contraindicated_condition', sa.String(length=200), nullable=False),
    sa.Column('risk_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_dosage_guidelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.String(length=100), nullable=False),
    sa.Column('min_dose', sa.Float(), nullable=False),
    sa.Column('max_dose', sa.Float(), nullable=False),
    sa.Column('age_group', sa.String(length=50), nullable=True),
    sa.Column('weight_range', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('drug_interactions', sa.Column('drug_a', sa.String(length=100), nullable=False))
    op.add_column('drug_interactions', sa.Column('drug_b', sa.String(length=100), nullable=False))
    op.add_column('drug_interactions', sa.Column('interaction_description', sa.Text(), nullable=False))
    op.add_column('drug_interactions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_drug_interactions_drug_a_id'), table_name='drug_interactions')
    op.drop_index(op.f('ix_drug_interactions_drug_b_id'), table_name='drug_interactions')
    op.drop_constraint(op.f('drug_interactions_drug_a_id_fkey'), 'drug_interactions', type_='foreignkey')
    op.drop_constraint(op.f('drug_interactions_drug_b_id_fkey'), 'drug_interactions', type_='foreignkey')
    op.drop_column('drug_interactions', 'drug_b_id')
    op.drop_column('drug_interactions', 'interaction_type')
    op.drop_column('drug_interactions', 'description')
    op.drop_column('drug_interactions', 'drug_a_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_interactions', sa.Column('drug_a_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('drug_interactions', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('drug_interactions', sa.Column('interaction_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('drug_interactions', sa.Column('drug_b_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('drug_interactions_drug_b_id_fkey'), 'drug_interactions', 'medications', ['drug_b_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('drug_interactions_drug_a_id_fkey'), 'drug_interactions', 'medications', ['drug_a_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_drug_interactions_drug_b_id'), 'drug_interactions', ['drug_b_id'], unique=False)
    op.create_index(op.f('ix_drug_interactions_drug_a_id'), 'drug_interactions', ['drug_a_id'], unique=False)
    op.drop_column('drug_interactions', 'created_at')
    op.drop_column('drug_interactions', 'interaction_description')
    op.drop_column('drug_interactions', 'drug_b')
    op.drop_column('drug_interactions', 'drug_a')
    op.drop_table('drug_dosage_guidelines')
    op.drop_table('drug_contraindications')
    op.drop_table('drug_classes')
    op.drop_table('drug_allergy_mappings')
    op.drop_table('cdss_alerts')
    # ### end Alembic commands ###
