"""enterprise_rcm_billing

Revision ID: 2f5eff6c43aa
Revises: 9ad2ec73b58f
Create Date: 2026-03-23 11:26:45.943689
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5eff6c43aa'
down_revision: Union[str, None] = '9ad2ec73b58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rcm_billing_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('balance_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_number')
    )
    op.create_table('rcm_billing_tariffs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('tariff_category', sa.String(length=100), nullable=False),
    sa.Column('doctor_grade', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rcm_billing_discounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('discount_type', sa.String(length=50), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('authorized_by', sa.UUID(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['rcm_billing_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rcm_billing_payers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('payer_type', sa.String(length=50), nullable=True),
    sa.Column('insurance_provider', sa.String(length=255), nullable=True),
    sa.Column('policy_number', sa.String(length=255), nullable=True),
    sa.Column('authorization_status', sa.String(length=50), nullable=True),
    sa.Column('corporate_employer', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['rcm_billing_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rcm_billing_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('collected_by', sa.UUID(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['rcm_billing_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rcm_billing_refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refund_mode', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('authorized_by', sa.UUID(), nullable=False),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['rcm_billing_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rcm_billing_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('sub_department', sa.String(length=100), nullable=True),
    sa.Column('base_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_auto_billed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['rcm_billing_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rcm_billing_services')
    op.drop_table('rcm_billing_refunds')
    op.drop_table('rcm_billing_payments')
    op.drop_table('rcm_billing_payers')
    op.drop_table('rcm_billing_discounts')
    op.drop_table('rcm_billing_tariffs')
    op.drop_table('rcm_billing_master')
    # ### end Alembic commands ###
