"""Pharmacy Walk-In Sales Engine

Revision ID: 3350e68307b3
Revises: f3b77f861a2d
Create Date: 2026-03-24 12:36:48.272076
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3350e68307b3'
down_revision: Union[str, None] = 'f3b77f861a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_sales_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('pharmacist_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_sales_audit_logs_sale_id'), 'pharmacy_sales_audit_logs', ['sale_id'], unique=False)
    op.create_table('pharmacy_walkin_sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('walkin_name', sa.String(length=200), nullable=True),
    sa.Column('walkin_mobile', sa.String(length=20), nullable=True),
    sa.Column('pharmacist_id', sa.UUID(), nullable=False),
    sa.Column('sale_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_walkin_sales_patient_id'), 'pharmacy_walkin_sales', ['patient_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_walkin_sales_pharmacist_id'), 'pharmacy_walkin_sales', ['pharmacist_id'], unique=False)
    op.create_table('pharmacy_prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('doctor_name', sa.String(length=200), nullable=True),
    sa.Column('requires_validation', sa.Boolean(), nullable=True),
    sa.Column('validated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['pharmacy_walkin_sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_prescriptions_sale_id'), 'pharmacy_prescriptions', ['sale_id'], unique=False)
    op.create_table('pharmacy_sales_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dosage_instructions', sa.String(length=500), nullable=True),
    sa.Column('substituted_for_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['drug_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['drug_id'], ['medications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['pharmacy_walkin_sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substituted_for_id'], ['medications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_sales_items_batch_id'), 'pharmacy_sales_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_sales_items_drug_id'), 'pharmacy_sales_items', ['drug_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_sales_items_sale_id'), 'pharmacy_sales_items', ['sale_id'], unique=False)
    op.create_table('pharmacy_sales_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['pharmacy_walkin_sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pharmacy_sales_payments')
    op.drop_index(op.f('ix_pharmacy_sales_items_sale_id'), table_name='pharmacy_sales_items')
    op.drop_index(op.f('ix_pharmacy_sales_items_drug_id'), table_name='pharmacy_sales_items')
    op.drop_index(op.f('ix_pharmacy_sales_items_batch_id'), table_name='pharmacy_sales_items')
    op.drop_table('pharmacy_sales_items')
    op.drop_index(op.f('ix_pharmacy_prescriptions_sale_id'), table_name='pharmacy_prescriptions')
    op.drop_table('pharmacy_prescriptions')
    op.drop_index(op.f('ix_pharmacy_walkin_sales_pharmacist_id'), table_name='pharmacy_walkin_sales')
    op.drop_index(op.f('ix_pharmacy_walkin_sales_patient_id'), table_name='pharmacy_walkin_sales')
    op.drop_table('pharmacy_walkin_sales')
    op.drop_index(op.f('ix_pharmacy_sales_audit_logs_sale_id'), table_name='pharmacy_sales_audit_logs')
    op.drop_table('pharmacy_sales_audit_logs')
    # ### end Alembic commands ###
