"""Add IPD Nursing Models Phase 15

Revision ID: 3f11206babb8
Revises: fbfbf19c4e1e
Create Date: 2026-03-24 07:36:37.315744
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f11206babb8'
down_revision: Union[str, None] = 'fbfbf19c4e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipd_nursing_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('nurse_id', sa.UUID(), nullable=False),
    sa.Column('nurse_name', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_care_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('primary_nurse_id', sa.UUID(), nullable=True),
    sa.Column('primary_nurse_name', sa.String(), nullable=True),
    sa.Column('shift_nurse_id', sa.UUID(), nullable=True),
    sa.Column('shift_nurse_name', sa.String(), nullable=True),
    sa.Column('ward_supervisor_id', sa.UUID(), nullable=True),
    sa.Column('ward_supervisor_name', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_nursing_coversheets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('bed_uuid', sa.UUID(), nullable=False),
    sa.Column('primary_diagnosis', sa.String(), nullable=True),
    sa.Column('treating_doctor_id', sa.UUID(), nullable=True),
    sa.Column('treating_doctor_name', sa.String(), nullable=True),
    sa.Column('priority_status', sa.String(), nullable=True),
    sa.Column('acceptance_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_nurse_id', sa.UUID(), nullable=True),
    sa.Column('accepted_by_nurse_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_number')
    )
    op.create_table('ipd_nursing_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=True),
    sa.Column('clinical_note', sa.Text(), nullable=False),
    sa.Column('logged_by_id', sa.UUID(), nullable=False),
    sa.Column('logged_by_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_nursing_worklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('bed_uuid', sa.UUID(), nullable=False),
    sa.Column('ward_name', sa.String(), nullable=True),
    sa.Column('bed_number', sa.String(), nullable=True),
    sa.Column('admitting_doctor', sa.String(), nullable=True),
    sa.Column('admission_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_number')
    )
    op.create_table('ipd_patient_status_monitor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipd_patient_status_monitor')
    op.drop_table('ipd_nursing_worklist')
    op.drop_table('ipd_nursing_notes')
    op.drop_table('ipd_nursing_coversheets')
    op.drop_table('ipd_care_assignments')
    op.drop_table('ipd_nursing_audit_logs')
    # ### end Alembic commands ###
