"""Phase 23: RPIW tables

Revision ID: 44dd0aaa8ec1
Revises: 1e9fbd73c980
Create Date: 2026-03-24 11:22:18.998932
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44dd0aaa8ec1'
down_revision: Union[str, None] = '1e9fbd73c980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpiw_role_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('action_label', sa.String(), nullable=True),
    sa.Column('patient_uhid', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_role_activity_logs_patient_uhid'), 'rpiw_role_activity_logs', ['patient_uhid'], unique=False)
    op.create_index(op.f('ix_rpiw_role_activity_logs_user_id'), 'rpiw_role_activity_logs', ['user_id'], unique=False)
    op.create_table('rpiw_role_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.String(), nullable=False),
    sa.Column('component_key', sa.String(), nullable=False),
    sa.Column('component_label', sa.String(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=True),
    sa.Column('component_config', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_role_components_role_code'), 'rpiw_role_components', ['role_code'], unique=False)
    op.create_table('rpiw_role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.String(), nullable=False),
    sa.Column('permission_key', sa.String(), nullable=False),
    sa.Column('permission_label', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('can_create', sa.Boolean(), nullable=True),
    sa.Column('can_read', sa.Boolean(), nullable=True),
    sa.Column('can_update', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_role_permissions_role_code'), 'rpiw_role_permissions', ['role_code'], unique=False)
    op.create_table('rpiw_role_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('active_workspace', sa.String(), nullable=True),
    sa.Column('assigned_patients', sa.JSON(), nullable=True),
    sa.Column('session_token', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_role_sessions_user_id'), 'rpiw_role_sessions', ['user_id'], unique=False)
    op.create_table('rpiw_role_workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.String(), nullable=False),
    sa.Column('workflow_key', sa.String(), nullable=False),
    sa.Column('workflow_label', sa.String(), nullable=False),
    sa.Column('workflow_description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('route_path', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_role_workflows_role_code'), 'rpiw_role_workflows', ['role_code'], unique=False)
    op.create_table('rpiw_user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.String(), nullable=False),
    sa.Column('role_label', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_user_roles_role_code'), 'rpiw_user_roles', ['role_code'], unique=False)
    op.create_index(op.f('ix_rpiw_user_roles_user_id'), 'rpiw_user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rpiw_user_roles_user_id'), table_name='rpiw_user_roles')
    op.drop_index(op.f('ix_rpiw_user_roles_role_code'), table_name='rpiw_user_roles')
    op.drop_table('rpiw_user_roles')
    op.drop_index(op.f('ix_rpiw_role_workflows_role_code'), table_name='rpiw_role_workflows')
    op.drop_table('rpiw_role_workflows')
    op.drop_index(op.f('ix_rpiw_role_sessions_user_id'), table_name='rpiw_role_sessions')
    op.drop_table('rpiw_role_sessions')
    op.drop_index(op.f('ix_rpiw_role_permissions_role_code'), table_name='rpiw_role_permissions')
    op.drop_table('rpiw_role_permissions')
    op.drop_index(op.f('ix_rpiw_role_components_role_code'), table_name='rpiw_role_components')
    op.drop_table('rpiw_role_components')
    op.drop_index(op.f('ix_rpiw_role_activity_logs_user_id'), table_name='rpiw_role_activity_logs')
    op.drop_index(op.f('ix_rpiw_role_activity_logs_patient_uhid'), table_name='rpiw_role_activity_logs')
    op.drop_table('rpiw_role_activity_logs')
    # ### end Alembic commands ###
