"""Add Blood Bank Phase 13

Revision ID: 489a1dc0872a
Revises: 2d322d91a310
Create Date: 2026-03-17 15:05:40.135380
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489a1dc0872a'
down_revision: Union[str, None] = '2d322d91a310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('storage_temperature', sa.String(length=50), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_name')
    )
    op.create_table('blood_donors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=False),
    sa.Column('rh_factor', sa.String(length=10), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('screening_status', sa.String(length=50), nullable=False),
    sa.Column('last_donation_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_donors_donor_id'), 'blood_donors', ['donor_id'], unique=True)
    op.create_table('blood_storage_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('storage_name', sa.String(length=100), nullable=False),
    sa.Column('temperature_range', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_load', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_name')
    )
    op.create_table('blood_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('collection_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collection_location', sa.String(length=255), nullable=False),
    sa.Column('collected_by', sa.String(length=255), nullable=False),
    sa.Column('collection_volume', sa.Float(), nullable=False),
    sa.Column('screening_results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['blood_donors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_collections_donor_id'), 'blood_collections', ['donor_id'], unique=False)
    op.create_table('blood_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.String(length=50), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=False),
    sa.Column('rh_factor', sa.String(length=10), nullable=False),
    sa.Column('component_type', sa.UUID(), nullable=True),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('collection_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('storage_location', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['blood_collections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['component_type'], ['blood_components.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storage_location'], ['blood_storage_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_units_collection_id'), 'blood_units', ['collection_id'], unique=False)
    op.create_index(op.f('ix_blood_units_component_type'), 'blood_units', ['component_type'], unique=False)
    op.create_index(op.f('ix_blood_units_storage_location'), 'blood_units', ['storage_location'], unique=False)
    op.create_index(op.f('ix_blood_units_unit_id'), 'blood_units', ['unit_id'], unique=True)
    op.create_table('transfusion_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('requested_component_id', sa.UUID(), nullable=False),
    sa.Column('units_requested', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('order_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_component_id'], ['blood_components.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfusion_orders_encounter_id'), 'transfusion_orders', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_transfusion_orders_order_id'), 'transfusion_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_transfusion_orders_patient_id'), 'transfusion_orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_transfusion_orders_requested_component_id'), 'transfusion_orders', ['requested_component_id'], unique=False)
    op.create_table('blood_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfusion_order_id', sa.UUID(), nullable=False),
    sa.Column('blood_unit_id', sa.UUID(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('allocated_by', sa.String(length=255), nullable=False),
    sa.Column('allocation_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['blood_unit_id'], ['blood_units.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfusion_order_id'], ['transfusion_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_allocations_blood_unit_id'), 'blood_allocations', ['blood_unit_id'], unique=False)
    op.create_index(op.f('ix_blood_allocations_transfusion_order_id'), 'blood_allocations', ['transfusion_order_id'], unique=False)
    op.create_table('crossmatch_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('blood_unit_id', sa.UUID(), nullable=False),
    sa.Column('patient_blood_group', sa.String(length=10), nullable=False),
    sa.Column('unit_blood_group', sa.String(length=10), nullable=False),
    sa.Column('compatibility_result', sa.String(length=50), nullable=False),
    sa.Column('tested_by', sa.String(length=255), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blood_unit_id'], ['blood_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crossmatch_tests_blood_unit_id'), 'crossmatch_tests', ['blood_unit_id'], unique=False)
    op.create_index(op.f('ix_crossmatch_tests_patient_id'), 'crossmatch_tests', ['patient_id'], unique=False)
    op.create_table('transfusions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('blood_unit_id', sa.UUID(), nullable=False),
    sa.Column('transfusion_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transfusion_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('administered_by', sa.String(length=255), nullable=False),
    sa.Column('supervised_by', sa.String(length=255), nullable=True),
    sa.Column('transfusion_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blood_unit_id'], ['blood_units.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfusions_blood_unit_id'), 'transfusions', ['blood_unit_id'], unique=False)
    op.create_index(op.f('ix_transfusions_encounter_id'), 'transfusions', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_transfusions_patient_id'), 'transfusions', ['patient_id'], unique=False)
    op.create_table('transfusion_reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfusion_id', sa.UUID(), nullable=False),
    sa.Column('reaction_type', sa.String(length=50), nullable=False),
    sa.Column('reaction_severity', sa.String(length=50), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('reported_by', sa.String(length=255), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transfusion_id'], ['transfusions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfusion_reactions_transfusion_id'), 'transfusion_reactions', ['transfusion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfusion_reactions_transfusion_id'), table_name='transfusion_reactions')
    op.drop_table('transfusion_reactions')
    op.drop_index(op.f('ix_transfusions_patient_id'), table_name='transfusions')
    op.drop_index(op.f('ix_transfusions_encounter_id'), table_name='transfusions')
    op.drop_index(op.f('ix_transfusions_blood_unit_id'), table_name='transfusions')
    op.drop_table('transfusions')
    op.drop_index(op.f('ix_crossmatch_tests_patient_id'), table_name='crossmatch_tests')
    op.drop_index(op.f('ix_crossmatch_tests_blood_unit_id'), table_name='crossmatch_tests')
    op.drop_table('crossmatch_tests')
    op.drop_index(op.f('ix_blood_allocations_transfusion_order_id'), table_name='blood_allocations')
    op.drop_index(op.f('ix_blood_allocations_blood_unit_id'), table_name='blood_allocations')
    op.drop_table('blood_allocations')
    op.drop_index(op.f('ix_transfusion_orders_requested_component_id'), table_name='transfusion_orders')
    op.drop_index(op.f('ix_transfusion_orders_patient_id'), table_name='transfusion_orders')
    op.drop_index(op.f('ix_transfusion_orders_order_id'), table_name='transfusion_orders')
    op.drop_index(op.f('ix_transfusion_orders_encounter_id'), table_name='transfusion_orders')
    op.drop_table('transfusion_orders')
    op.drop_index(op.f('ix_blood_units_unit_id'), table_name='blood_units')
    op.drop_index(op.f('ix_blood_units_storage_location'), table_name='blood_units')
    op.drop_index(op.f('ix_blood_units_component_type'), table_name='blood_units')
    op.drop_index(op.f('ix_blood_units_collection_id'), table_name='blood_units')
    op.drop_table('blood_units')
    op.drop_index(op.f('ix_blood_collections_donor_id'), table_name='blood_collections')
    op.drop_table('blood_collections')
    op.drop_table('blood_storage_units')
    op.drop_index(op.f('ix_blood_donors_donor_id'), table_name='blood_donors')
    op.drop_table('blood_donors')
    op.drop_table('blood_components')
    # ### end Alembic commands ###
