"""Add IPD Clinical Orders phase 18 models

Revision ID: 512200f00198
Revises: c1eaee47860e
Create Date: 2026-03-24 08:54:40.134125
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512200f00198'
down_revision: Union[str, None] = 'c1eaee47860e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipd_orders_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('doctor_uuid', sa.UUID(), nullable=True),
    sa.Column('doctor_name', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_pattern', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_lab_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('sample_type', sa.String(), nullable=True),
    sa.Column('clinical_indication', sa.Text(), nullable=True),
    sa.Column('result_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['ipd_orders_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_medication_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('medicine_name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('pharmacy_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['ipd_orders_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_order_status_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['ipd_orders_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_procedure_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('procedure_service_name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('scheduling_notes', sa.Text(), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['ipd_orders_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_radiology_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('imaging_type', sa.String(), nullable=False),
    sa.Column('target_area', sa.String(), nullable=False),
    sa.Column('clinical_indication', sa.Text(), nullable=True),
    sa.Column('report_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['ipd_orders_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipd_radiology_orders')
    op.drop_table('ipd_procedure_orders')
    op.drop_table('ipd_order_status_logs')
    op.drop_table('ipd_medication_orders')
    op.drop_table('ipd_lab_orders')
    op.drop_table('ipd_orders_master')
    # ### end Alembic commands ###
