"""Phase 26: RPIW Role-Based AI Assistant Engine

Revision ID: 5a4671e66a16
Revises: dfbcfec086a1
Create Date: 2026-03-24 11:56:42.042167
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a4671e66a16'
down_revision: Union[str, None] = 'dfbcfec086a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpiw_ai_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_code', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_ai_activity_logs_patient_uhid'), 'rpiw_ai_activity_logs', ['patient_uhid'], unique=False)
    op.create_table('rpiw_ai_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=False),
    sa.Column('risk_category', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_ai_alerts_patient_uhid'), 'rpiw_ai_alerts', ['patient_uhid'], unique=False)
    op.create_table('rpiw_ai_context',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_code', sa.String(), nullable=False),
    sa.Column('clinical_summary', sa.Text(), nullable=True),
    sa.Column('recent_vitals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active_medications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latest_labs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_ai_context_patient_uhid'), 'rpiw_ai_context', ['patient_uhid'], unique=False)
    op.create_table('rpiw_ai_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=False),
    sa.Column('suggestion_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['rpiw_ai_context.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_ai_suggestions_patient_uhid'), 'rpiw_ai_suggestions', ['patient_uhid'], unique=False)
    op.create_table('rpiw_ai_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('suggestion_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('feedback_rating', sa.String(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['suggestion_id'], ['rpiw_ai_suggestions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suggestion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rpiw_ai_feedback')
    op.drop_index(op.f('ix_rpiw_ai_suggestions_patient_uhid'), table_name='rpiw_ai_suggestions')
    op.drop_table('rpiw_ai_suggestions')
    op.drop_index(op.f('ix_rpiw_ai_context_patient_uhid'), table_name='rpiw_ai_context')
    op.drop_table('rpiw_ai_context')
    op.drop_index(op.f('ix_rpiw_ai_alerts_patient_uhid'), table_name='rpiw_ai_alerts')
    op.drop_table('rpiw_ai_alerts')
    op.drop_index(op.f('ix_rpiw_ai_activity_logs_patient_uhid'), table_name='rpiw_ai_activity_logs')
    op.drop_table('rpiw_ai_activity_logs')
    # ### end Alembic commands ###
