"""phase10_analytics

Revision ID: 5c7ca72296d5
Revises: c9f1a2b3d4e5
Create Date: 2026-03-17 09:46:14.022626
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c7ca72296d5'
down_revision: Union[str, None] = 'c9f1a2b3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_clinical_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('admissions_count', sa.Integer(), nullable=False),
    sa.Column('readmission_rate', sa.Float(), nullable=False),
    sa.Column('average_los_hours', sa.Float(), nullable=False),
    sa.Column('avg_lab_turnaround_hours', sa.Float(), nullable=False),
    sa.Column('critical_alerts_count', sa.Integer(), nullable=False),
    sa.Column('avg_alert_response_mins', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_clinical_metrics_metric_date'), 'analytics_clinical_metrics', ['metric_date'], unique=True)
    op.create_table('analytics_financial_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('daily_revenue', sa.Float(), nullable=False),
    sa.Column('outpatient_revenue', sa.Float(), nullable=False),
    sa.Column('inpatient_revenue', sa.Float(), nullable=False),
    sa.Column('insurance_claims_count', sa.Integer(), nullable=False),
    sa.Column('claim_approval_rate', sa.Float(), nullable=False),
    sa.Column('billing_error_rate', sa.Float(), nullable=False),
    sa.Column('outstanding_invoices_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_financial_metrics_metric_date'), 'analytics_financial_metrics', ['metric_date'], unique=True)
    op.create_table('analytics_operational_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('bed_occupancy_rate', sa.Float(), nullable=False),
    sa.Column('patient_throughput', sa.Integer(), nullable=False),
    sa.Column('avg_task_completion_mins', sa.Float(), nullable=False),
    sa.Column('lab_processing_volume', sa.Integer(), nullable=False),
    sa.Column('pharmacy_dispensing_volume', sa.Integer(), nullable=False),
    sa.Column('staff_workload_index', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_operational_metrics_metric_date'), 'analytics_operational_metrics', ['metric_date'], unique=True)
    op.create_table('analytics_predictive_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('prediction_type', sa.String(length=100), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence_interval_low', sa.Float(), nullable=True),
    sa.Column('confidence_interval_high', sa.Float(), nullable=True),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_predictive_models_prediction_type'), 'analytics_predictive_models', ['prediction_type'], unique=False)
    op.create_index(op.f('ix_analytics_predictive_models_target_date'), 'analytics_predictive_models', ['target_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_predictive_models_target_date'), table_name='analytics_predictive_models')
    op.drop_index(op.f('ix_analytics_predictive_models_prediction_type'), table_name='analytics_predictive_models')
    op.drop_table('analytics_predictive_models')
    op.drop_index(op.f('ix_analytics_operational_metrics_metric_date'), table_name='analytics_operational_metrics')
    op.drop_table('analytics_operational_metrics')
    op.drop_index(op.f('ix_analytics_financial_metrics_metric_date'), table_name='analytics_financial_metrics')
    op.drop_table('analytics_financial_metrics')
    op.drop_index(op.f('ix_analytics_clinical_metrics_metric_date'), table_name='analytics_clinical_metrics')
    op.drop_table('analytics_clinical_metrics')
    # ### end Alembic commands ###
