"""Multitenant Orgs

Revision ID: 60eb18cedd31
Revises: 713e4c499332
Create Date: 2026-03-26 15:14:47.705457
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60eb18cedd31'
down_revision: Union[str, None] = '713e4c499332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('encounters', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('encounters', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
