"""add_org_id_to_opd_models

Revision ID: 6afc69fa0d5e
Revises: 60eb18cedd31
Create Date: 2026-03-27 09:47:38.511751
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6afc69fa0d5e'
down_revision: Union[str, None] = '60eb18cedd31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.alter_column('encounters', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('organizations_abdm_hfr_id_key'), 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_abdm_hfr_id'), 'organizations', ['abdm_hfr_id'], unique=True)
    op.create_index(op.f('ix_patients_org_id'), 'patients', ['org_id'], unique=False)
    op.add_column('rcm_billing_master', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_rcm_billing_master_org_id'), 'rcm_billing_master', ['org_id'], unique=False)
    op.add_column('rcm_billing_payments', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_rcm_billing_payments_org_id'), 'rcm_billing_payments', ['org_id'], unique=False)
    op.add_column('rcm_billing_tariffs', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_rcm_billing_tariffs_org_id'), 'rcm_billing_tariffs', ['org_id'], unique=False)
    op.add_column('rpiw_role_activity_logs', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_rpiw_role_activity_logs_org_id'), 'rpiw_role_activity_logs', ['org_id'], unique=False)
    op.add_column('rpiw_role_components', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_rpiw_role_components_org_id'), 'rpiw_role_components', ['org_id'], unique=False)
    op.add_column('rpiw_role_sessions', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_rpiw_role_sessions_org_id'), 'rpiw_role_sessions', ['org_id'], unique=False)
    op.add_column('rpiw_user_roles', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_rpiw_user_roles_org_id'), 'rpiw_user_roles', ['org_id'], unique=False)
    op.drop_constraint(op.f('users_abdm_hpr_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_abdm_hpr_id'), 'users', ['abdm_hpr_id'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.add_column('visit_analytics_snapshots', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_visit_analytics_snapshots_org_id'), 'visit_analytics_snapshots', ['org_id'], unique=False)
    op.add_column('visit_master', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_visit_master_org_id'), 'visit_master', ['org_id'], unique=False)
    op.add_column('visit_questionnaire_templates', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_visit_questionnaire_templates_org_id'), 'visit_questionnaire_templates', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_questionnaire_templates_org_id'), table_name='visit_questionnaire_templates')
    op.drop_column('visit_questionnaire_templates', 'org_id')
    op.drop_index(op.f('ix_visit_master_org_id'), table_name='visit_master')
    op.drop_column('visit_master', 'org_id')
    op.drop_index(op.f('ix_visit_analytics_snapshots_org_id'), table_name='visit_analytics_snapshots')
    op.drop_column('visit_analytics_snapshots', 'org_id')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_abdm_hpr_id'), table_name='users')
    op.create_unique_constraint(op.f('users_abdm_hpr_id_key'), 'users', ['abdm_hpr_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_rpiw_user_roles_org_id'), table_name='rpiw_user_roles')
    op.drop_column('rpiw_user_roles', 'org_id')
    op.drop_index(op.f('ix_rpiw_role_sessions_org_id'), table_name='rpiw_role_sessions')
    op.drop_column('rpiw_role_sessions', 'org_id')
    op.drop_index(op.f('ix_rpiw_role_components_org_id'), table_name='rpiw_role_components')
    op.drop_column('rpiw_role_components', 'org_id')
    op.drop_index(op.f('ix_rpiw_role_activity_logs_org_id'), table_name='rpiw_role_activity_logs')
    op.drop_column('rpiw_role_activity_logs', 'org_id')
    op.drop_index(op.f('ix_rcm_billing_tariffs_org_id'), table_name='rcm_billing_tariffs')
    op.drop_column('rcm_billing_tariffs', 'org_id')
    op.drop_index(op.f('ix_rcm_billing_payments_org_id'), table_name='rcm_billing_payments')
    op.drop_column('rcm_billing_payments', 'org_id')
    op.drop_index(op.f('ix_rcm_billing_master_org_id'), table_name='rcm_billing_master')
    op.drop_column('rcm_billing_master', 'org_id')
    op.drop_index(op.f('ix_patients_org_id'), table_name='patients')
    op.drop_index(op.f('ix_organizations_abdm_hfr_id'), table_name='organizations')
    op.create_unique_constraint(op.f('organizations_abdm_hfr_id_key'), 'organizations', ['abdm_hfr_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('encounters', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    # ### end Alembic commands ###
