"""Add IP Pharmacy Returns Engine

Revision ID: 6ce3866c890f
Revises: baf9f7765ade
Create Date: 2026-03-25 09:15:07.148077
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce3866c890f'
down_revision: Union[str, None] = 'baf9f7765ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_ip_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('uhid', sa.String(length=100), nullable=False),
    sa.Column('admission_number', sa.String(length=100), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('bed_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('request_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('processed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['pharmacy_ip_pending_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_ip_returns_admission_number'), 'pharmacy_ip_returns', ['admission_number'], unique=False)
    op.create_index(op.f('ix_pharmacy_ip_returns_issue_id'), 'pharmacy_ip_returns', ['issue_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_ip_returns_patient_id'), 'pharmacy_ip_returns', ['patient_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_ip_returns_uhid'), 'pharmacy_ip_returns', ['uhid'], unique=False)
    op.create_table('pharmacy_ip_billing_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('admission_number', sa.String(length=100), nullable=False),
    sa.Column('adjustment_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('adjustment_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['return_id'], ['pharmacy_ip_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_ip_billing_adjustments_return_id'), 'pharmacy_ip_billing_adjustments', ['return_id'], unique=False)
    op.create_table('pharmacy_ip_return_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_id', sa.UUID(), nullable=False),
    sa.Column('dispense_record_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('drug_id', sa.UUID(), nullable=True),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('return_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('is_restockable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dispense_record_id'], ['pharmacy_ip_dispense_records.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['pharmacy_ip_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_ip_return_items_dispense_record_id'), 'pharmacy_ip_return_items', ['dispense_record_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_ip_return_items_return_id'), 'pharmacy_ip_return_items', ['return_id'], unique=False)
    op.create_table('pharmacy_ip_return_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['return_id'], ['pharmacy_ip_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_ip_return_logs_return_id'), 'pharmacy_ip_return_logs', ['return_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_ip_return_logs_return_id'), table_name='pharmacy_ip_return_logs')
    op.drop_table('pharmacy_ip_return_logs')
    op.drop_index(op.f('ix_pharmacy_ip_return_items_return_id'), table_name='pharmacy_ip_return_items')
    op.drop_index(op.f('ix_pharmacy_ip_return_items_dispense_record_id'), table_name='pharmacy_ip_return_items')
    op.drop_table('pharmacy_ip_return_items')
    op.drop_index(op.f('ix_pharmacy_ip_billing_adjustments_return_id'), table_name='pharmacy_ip_billing_adjustments')
    op.drop_table('pharmacy_ip_billing_adjustments')
    op.drop_index(op.f('ix_pharmacy_ip_returns_uhid'), table_name='pharmacy_ip_returns')
    op.drop_index(op.f('ix_pharmacy_ip_returns_patient_id'), table_name='pharmacy_ip_returns')
    op.drop_index(op.f('ix_pharmacy_ip_returns_issue_id'), table_name='pharmacy_ip_returns')
    op.drop_index(op.f('ix_pharmacy_ip_returns_admission_number'), table_name='pharmacy_ip_returns')
    op.drop_table('pharmacy_ip_returns')
    # ### end Alembic commands ###
