"""Phase 24: RPIW Patient Summary Engine

Revision ID: 6dd8020356c9
Revises: 44dd0aaa8ec1
Create Date: 2026-03-24 11:34:21.818260
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd8020356c9'
down_revision: Union[str, None] = '44dd0aaa8ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpiw_patient_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=True),
    sa.Column('visit_id', sa.String(), nullable=True),
    sa.Column('chief_issue', sa.Text(), nullable=True),
    sa.Column('primary_diagnosis', sa.String(), nullable=True),
    sa.Column('current_clinical_status', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_patient_summary_admission_number'), 'rpiw_patient_summary', ['admission_number'], unique=False)
    op.create_index(op.f('ix_rpiw_patient_summary_patient_uhid'), 'rpiw_patient_summary', ['patient_uhid'], unique=False)
    op.create_index(op.f('ix_rpiw_patient_summary_visit_id'), 'rpiw_patient_summary', ['visit_id'], unique=False)
    op.create_table('rpiw_summary_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['rpiw_patient_summary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_summary_alerts_summary_id'), 'rpiw_summary_alerts', ['summary_id'], unique=False)
    op.create_table('rpiw_summary_medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('drug_name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['rpiw_patient_summary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_summary_medications_summary_id'), 'rpiw_summary_medications', ['summary_id'], unique=False)
    op.create_table('rpiw_summary_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('source_module', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=False),
    sa.Column('timestamp_aggregated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['rpiw_patient_summary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_summary_sources_summary_id'), 'rpiw_summary_sources', ['summary_id'], unique=False)
    op.create_table('rpiw_summary_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('task_category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['rpiw_patient_summary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_summary_tasks_summary_id'), 'rpiw_summary_tasks', ['summary_id'], unique=False)
    op.create_table('rpiw_summary_vitals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('vital_sign', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('is_abnormal', sa.Boolean(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['rpiw_patient_summary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_summary_vitals_summary_id'), 'rpiw_summary_vitals', ['summary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rpiw_summary_vitals_summary_id'), table_name='rpiw_summary_vitals')
    op.drop_table('rpiw_summary_vitals')
    op.drop_index(op.f('ix_rpiw_summary_tasks_summary_id'), table_name='rpiw_summary_tasks')
    op.drop_table('rpiw_summary_tasks')
    op.drop_index(op.f('ix_rpiw_summary_sources_summary_id'), table_name='rpiw_summary_sources')
    op.drop_table('rpiw_summary_sources')
    op.drop_index(op.f('ix_rpiw_summary_medications_summary_id'), table_name='rpiw_summary_medications')
    op.drop_table('rpiw_summary_medications')
    op.drop_index(op.f('ix_rpiw_summary_alerts_summary_id'), table_name='rpiw_summary_alerts')
    op.drop_table('rpiw_summary_alerts')
    op.drop_index(op.f('ix_rpiw_patient_summary_visit_id'), table_name='rpiw_patient_summary')
    op.drop_index(op.f('ix_rpiw_patient_summary_patient_uhid'), table_name='rpiw_patient_summary')
    op.drop_index(op.f('ix_rpiw_patient_summary_admission_number'), table_name='rpiw_patient_summary')
    op.drop_table('rpiw_patient_summary')
    # ### end Alembic commands ###
