"""Add pharmacy sales returns engine

Revision ID: 6f665620eda0
Revises: 997a27c101c6
Create Date: 2026-03-25 08:44:51.688743
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f665620eda0'
down_revision: Union[str, None] = '997a27c101c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_return_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_id', sa.UUID(), nullable=False),
    sa.Column('pharmacist_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_return_logs_return_id'), 'pharmacy_return_logs', ['return_id'], unique=False)
    op.create_table('pharmacy_return_reasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('reason_text', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reason_code')
    )
    op.create_table('pharmacy_sales_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_number', sa.String(length=50), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('worklist_id', sa.UUID(), nullable=True),
    sa.Column('bill_number', sa.String(length=100), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('patient_name', sa.String(length=200), nullable=True),
    sa.Column('uhid', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('pharmacist_id', sa.UUID(), nullable=True),
    sa.Column('pharmacist_name', sa.String(length=200), nullable=True),
    sa.Column('total_refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_adjustment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_adjustment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_refund', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sale_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_sales_returns_bill_number'), 'pharmacy_sales_returns', ['bill_number'], unique=False)
    op.create_index(op.f('ix_pharmacy_sales_returns_patient_id'), 'pharmacy_sales_returns', ['patient_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_sales_returns_return_number'), 'pharmacy_sales_returns', ['return_number'], unique=True)
    op.create_index(op.f('ix_pharmacy_sales_returns_sale_id'), 'pharmacy_sales_returns', ['sale_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_sales_returns_worklist_id'), 'pharmacy_sales_returns', ['worklist_id'], unique=False)
    op.create_table('pharmacy_return_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=True),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('quantity_sold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_returned', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason_id', sa.UUID(), nullable=True),
    sa.Column('reason_text', sa.String(length=255), nullable=True),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('eligibility_note', sa.String(length=500), nullable=True),
    sa.Column('stock_restored', sa.Boolean(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['return_id'], ['pharmacy_sales_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_return_items_return_id'), 'pharmacy_return_items', ['return_id'], unique=False)
    op.create_table('pharmacy_return_refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_id', sa.UUID(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_mode', sa.String(length=50), nullable=False),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refunded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['return_id'], ['pharmacy_sales_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pharmacy_return_refunds')
    op.drop_index(op.f('ix_pharmacy_return_items_return_id'), table_name='pharmacy_return_items')
    op.drop_table('pharmacy_return_items')
    op.drop_index(op.f('ix_pharmacy_sales_returns_worklist_id'), table_name='pharmacy_sales_returns')
    op.drop_index(op.f('ix_pharmacy_sales_returns_sale_id'), table_name='pharmacy_sales_returns')
    op.drop_index(op.f('ix_pharmacy_sales_returns_return_number'), table_name='pharmacy_sales_returns')
    op.drop_index(op.f('ix_pharmacy_sales_returns_patient_id'), table_name='pharmacy_sales_returns')
    op.drop_index(op.f('ix_pharmacy_sales_returns_bill_number'), table_name='pharmacy_sales_returns')
    op.drop_table('pharmacy_sales_returns')
    op.drop_table('pharmacy_return_reasons')
    op.drop_index(op.f('ix_pharmacy_return_logs_return_id'), table_name='pharmacy_return_logs')
    op.drop_table('pharmacy_return_logs')
    # ### end Alembic commands ###
