"""Phase 7 Billing Models

Revision ID: 71db12fad498
Revises: 64db44f2deef
Create Date: 2026-03-17 05:15:35.894507
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71db12fad498'
down_revision: Union[str, None] = '64db44f2deef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_code', sa.String(length=50), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('service_category', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_services_service_code'), 'billing_services', ['service_code'], unique=True)
    op.create_table('discount_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('discount_type', sa.String(length=50), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('contact_details', sa.String(length=500), nullable=True),
    sa.Column('policy_rules', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name')
    )
    op.create_table('financial_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('coverage_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['insurance_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_number')
    )
    op.create_index(op.f('ix_insurance_policies_patient_id'), 'insurance_policies', ['patient_id'], unique=False)
    op.create_index(op.f('ix_insurance_policies_provider_id'), 'insurance_policies', ['provider_id'], unique=False)
    op.create_table('service_tariffs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['billing_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_tariffs_service_id'), 'service_tariffs', ['service_id'], unique=False)
    op.create_table('insurance_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('claim_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['insurance_providers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_claims_invoice_id'), 'insurance_claims', ['invoice_id'], unique=False)
    op.create_table('billing_reversals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('billing_entry_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('reversed_by', sa.UUID(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['billing_entry_id'], ['billing_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_entry_id')
    )
    op.drop_index(op.f('ix_tariffs_code'), table_name='tariffs')
    op.drop_table('tariffs')
    op.add_column('billing_entries', sa.Column('service_id', sa.UUID(), nullable=False))
    op.add_column('billing_entries', sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('billing_entries', sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('billing_entries', sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.alter_column('billing_entries', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('billing_entries', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_index(op.f('ix_billing_entries_patient_id'), 'billing_entries', ['patient_id'], unique=False)
    op.create_index(op.f('ix_billing_entries_service_id'), 'billing_entries', ['service_id'], unique=False)
    op.drop_constraint(op.f('billing_entries_reversal_of_fkey'), 'billing_entries', type_='foreignkey')
    op.drop_constraint(op.f('billing_entries_created_by_fkey'), 'billing_entries', type_='foreignkey')
    op.create_foreign_key(None, 'billing_entries', 'billing_services', ['service_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('billing_entries', 'description')
    op.drop_column('billing_entries', 'reversal_of')
    op.drop_column('billing_entries', 'amount')
    op.drop_column('billing_entries', 'created_by')
    op.add_column('invoices', sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('invoices_invoice_number_key'), 'invoices', type_='unique')
    op.create_index(op.f('ix_invoices_encounter_id'), 'invoices', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_patient_id'), 'invoices', ['patient_id'], unique=False)
    op.drop_column('invoices', 'net_amount')
    op.drop_column('invoices', 'discount')
    op.drop_column('invoices', 'created_at')
    op.add_column('payments', sa.Column('payment_method', sa.String(length=50), nullable=False))
    op.add_column('payments', sa.Column('payment_status', sa.String(length=50), nullable=False))
    op.add_column('payments', sa.Column('payment_time', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.drop_constraint(op.f('payments_received_by_fkey'), 'payments', type_='foreignkey')
    op.drop_column('payments', 'reference')
    op.drop_column('payments', 'method')
    op.drop_column('payments', 'received_at')
    op.drop_column('payments', 'received_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('received_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('method', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('payments_received_by_fkey'), 'payments', 'users', ['received_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_column('payments', 'payment_time')
    op.drop_column('payments', 'payment_status')
    op.drop_column('payments', 'payment_method')
    op.add_column('invoices', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('discount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('net_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_invoices_patient_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_encounter_id'), table_name='invoices')
    op.create_unique_constraint(op.f('invoices_invoice_number_key'), 'invoices', ['invoice_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('invoices', 'generated_at')
    op.add_column('billing_entries', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('billing_entries', sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('billing_entries', sa.Column('reversal_of', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('billing_entries', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'billing_entries', type_='foreignkey')
    op.create_foreign_key(op.f('billing_entries_created_by_fkey'), 'billing_entries', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('billing_entries_reversal_of_fkey'), 'billing_entries', 'billing_entries', ['reversal_of'], ['id'])
    op.drop_index(op.f('ix_billing_entries_service_id'), table_name='billing_entries')
    op.drop_index(op.f('ix_billing_entries_patient_id'), table_name='billing_entries')
    op.alter_column('billing_entries', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('billing_entries', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('billing_entries', 'total_price')
    op.drop_column('billing_entries', 'unit_price')
    op.drop_column('billing_entries', 'quantity')
    op.drop_column('billing_entries', 'service_id')
    op.create_table('tariffs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('base_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tariffs_pkey'))
    )
    op.create_index(op.f('ix_tariffs_code'), 'tariffs', ['code'], unique=True)
    op.drop_table('billing_reversals')
    op.drop_index(op.f('ix_insurance_claims_invoice_id'), table_name='insurance_claims')
    op.drop_table('insurance_claims')
    op.drop_index(op.f('ix_service_tariffs_service_id'), table_name='service_tariffs')
    op.drop_table('service_tariffs')
    op.drop_index(op.f('ix_insurance_policies_provider_id'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_patient_id'), table_name='insurance_policies')
    op.drop_table('insurance_policies')
    op.drop_table('financial_audit_logs')
    op.drop_table('insurance_providers')
    op.drop_table('discount_rules')
    op.drop_index(op.f('ix_billing_services_service_code'), table_name='billing_services')
    op.drop_table('billing_services')
    # ### end Alembic commands ###
