"""enterprise_registration_module

Revision ID: 778d602f2408
Revises: 22d2aee6b0dc
Create Date: 2026-03-23 08:47:21.109325
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '778d602f2408'
down_revision: Union[str, None] = '22d2aee6b0dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_directory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_directory_pincode'), 'address_directory', ['pincode'], unique=False)
    op.create_table('face_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('embedding_vector', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_embeddings_patient_id'), 'face_embeddings', ['patient_id'], unique=True)
    op.create_table('health_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('uhid', sa.String(length=30), nullable=False),
    sa.Column('card_number', sa.String(length=30), nullable=False),
    sa.Column('qr_code_data', sa.Text(), nullable=False),
    sa.Column('qr_payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_cards_card_number'), 'health_cards', ['card_number'], unique=True)
    op.create_index(op.f('ix_health_cards_patient_id'), 'health_cards', ['patient_id'], unique=False)
    op.create_index(op.f('ix_health_cards_uhid'), 'health_cards', ['uhid'], unique=True)
    op.create_table('registration_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ID_PROOF', 'MEDICAL_DOCUMENT', 'PATIENT_PHOTO', 'INSURANCE_CARD', 'OTHER', name='document_category_enum'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_documents_patient_id'), 'registration_documents', ['patient_id'], unique=False)
    op.create_table('registration_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('SMS', 'EMAIL', 'WHATSAPP', name='reg_notification_channel_enum'), nullable=False),
    sa.Column('recipient', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'DELIVERED', 'FAILED', name='reg_notification_status_enum'), nullable=False),
    sa.Column('external_message_id', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_notifications_patient_id'), 'registration_notifications', ['patient_id'], unique=False)
    op.create_table('registration_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'PENDING_REVIEW', 'COMPLETED', 'CANCELLED', name='registration_status_enum'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('collected_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_suggestions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('voice_language', sa.String(length=10), nullable=False),
    sa.Column('registration_method', sa.String(length=30), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_sessions_patient_id'), 'registration_sessions', ['patient_id'], unique=False)
    op.create_table('id_scan_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.Enum('PASSPORT', 'NATIONAL_ID', 'AADHAAR', 'DRIVING_LICENSE', 'OTHER', name='id_document_type_enum'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('extracted_name', sa.String(length=200), nullable=True),
    sa.Column('extracted_dob', sa.String(length=20), nullable=True),
    sa.Column('extracted_gender', sa.String(length=20), nullable=True),
    sa.Column('extracted_id_number', sa.String(length=100), nullable=True),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['registration_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_id_scan_records_patient_id'), 'id_scan_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_id_scan_records_session_id'), 'id_scan_records', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_id_scan_records_session_id'), table_name='id_scan_records')
    op.drop_index(op.f('ix_id_scan_records_patient_id'), table_name='id_scan_records')
    op.drop_table('id_scan_records')
    op.drop_index(op.f('ix_registration_sessions_patient_id'), table_name='registration_sessions')
    op.drop_table('registration_sessions')
    op.drop_index(op.f('ix_registration_notifications_patient_id'), table_name='registration_notifications')
    op.drop_table('registration_notifications')
    op.drop_index(op.f('ix_registration_documents_patient_id'), table_name='registration_documents')
    op.drop_table('registration_documents')
    op.drop_index(op.f('ix_health_cards_uhid'), table_name='health_cards')
    op.drop_index(op.f('ix_health_cards_patient_id'), table_name='health_cards')
    op.drop_index(op.f('ix_health_cards_card_number'), table_name='health_cards')
    op.drop_table('health_cards')
    op.drop_index(op.f('ix_face_embeddings_patient_id'), table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_index(op.f('ix_address_directory_pincode'), table_name='address_directory')
    op.drop_table('address_directory')
    # ### end Alembic commands ###
