"""hospital_intelligence_bi_analytics

Revision ID: 7858e870dd40
Revises: 2f5eff6c43aa
Create Date: 2026-03-23 11:50:42.056635
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7858e870dd40'
down_revision: Union[str, None] = '2f5eff6c43aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_clinical_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('disease_icd_code', sa.String(), nullable=True),
    sa.Column('disease_name', sa.String(), nullable=True),
    sa.Column('incidence_count', sa.Integer(), nullable=True),
    sa.Column('prescriptions_generated', sa.Integer(), nullable=True),
    sa.Column('follow_up_compliance_rate_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_clinical_statistics_disease_icd_code'), 'analytics_clinical_statistics', ['disease_icd_code'], unique=False)
    op.create_index(op.f('ix_analytics_clinical_statistics_record_date'), 'analytics_clinical_statistics', ['record_date'], unique=False)
    op.create_table('analytics_doctor_productivity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('doctor_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('patients_seen', sa.Integer(), nullable=True),
    sa.Column('avg_consult_time_mins', sa.Float(), nullable=True),
    sa.Column('revenue_generated', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('orders_prescribed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_doctor_productivity_department'), 'analytics_doctor_productivity', ['department'], unique=False)
    op.create_index(op.f('ix_analytics_doctor_productivity_doctor_name'), 'analytics_doctor_productivity', ['doctor_name'], unique=False)
    op.create_index(op.f('ix_analytics_doctor_productivity_record_date'), 'analytics_doctor_productivity', ['record_date'], unique=False)
    op.create_table('analytics_patient_flow',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('total_registered', sa.Integer(), nullable=True),
    sa.Column('total_consulted', sa.Integer(), nullable=True),
    sa.Column('total_no_shows', sa.Integer(), nullable=True),
    sa.Column('avg_waiting_time_mins', sa.Float(), nullable=True),
    sa.Column('avg_consult_duration_mins', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_patient_flow_department'), 'analytics_patient_flow', ['department'], unique=False)
    op.create_index(op.f('ix_analytics_patient_flow_record_date'), 'analytics_patient_flow', ['record_date'], unique=False)
    op.create_table('analytics_prediction_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('predicted_footfall', sa.Integer(), nullable=True),
    sa.Column('confidence_score_pct', sa.Float(), nullable=True),
    sa.Column('peak_hours_expected', sa.String(), nullable=True),
    sa.Column('is_anomaly_alert', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_prediction_models_department'), 'analytics_prediction_models', ['department'], unique=False)
    op.create_index(op.f('ix_analytics_prediction_models_target_date'), 'analytics_prediction_models', ['target_date'], unique=False)
    op.create_table('analytics_revenue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('gross_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discounts_given', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_modes_split', sa.JSON(), nullable=True),
    sa.Column('payer_type_split', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_revenue_department'), 'analytics_revenue', ['department'], unique=False)
    op.create_index(op.f('ix_analytics_revenue_record_date'), 'analytics_revenue', ['record_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_revenue_record_date'), table_name='analytics_revenue')
    op.drop_index(op.f('ix_analytics_revenue_department'), table_name='analytics_revenue')
    op.drop_table('analytics_revenue')
    op.drop_index(op.f('ix_analytics_prediction_models_target_date'), table_name='analytics_prediction_models')
    op.drop_index(op.f('ix_analytics_prediction_models_department'), table_name='analytics_prediction_models')
    op.drop_table('analytics_prediction_models')
    op.drop_index(op.f('ix_analytics_patient_flow_record_date'), table_name='analytics_patient_flow')
    op.drop_index(op.f('ix_analytics_patient_flow_department'), table_name='analytics_patient_flow')
    op.drop_table('analytics_patient_flow')
    op.drop_index(op.f('ix_analytics_doctor_productivity_record_date'), table_name='analytics_doctor_productivity')
    op.drop_index(op.f('ix_analytics_doctor_productivity_doctor_name'), table_name='analytics_doctor_productivity')
    op.drop_index(op.f('ix_analytics_doctor_productivity_department'), table_name='analytics_doctor_productivity')
    op.drop_table('analytics_doctor_productivity')
    op.drop_index(op.f('ix_analytics_clinical_statistics_record_date'), table_name='analytics_clinical_statistics')
    op.drop_index(op.f('ix_analytics_clinical_statistics_disease_icd_code'), table_name='analytics_clinical_statistics')
    op.drop_table('analytics_clinical_statistics')
    # ### end Alembic commands ###
