"""Add IPD Admission and Bed Management models

Revision ID: 7d4287c9ba5b
Revises: 7d4fa608f94b
Create Date: 2026-03-24 06:34:36.505615
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4287c9ba5b'
down_revision: Union[str, None] = '7d4fa608f94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipd_bed_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bed_id', sa.String(), nullable=False),
    sa.Column('ward', sa.String(), nullable=False),
    sa.Column('floor', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('bed_category', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipd_bed_master_bed_id'), 'ipd_bed_master', ['bed_id'], unique=True)
    op.create_table('ipd_admission_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_admission_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('blood_group', sa.String(), nullable=True),
    sa.Column('admitting_doctor', sa.String(), nullable=False),
    sa.Column('treating_doctor', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('reason_for_admission', sa.String(), nullable=False),
    sa.Column('admission_category', sa.String(), nullable=False),
    sa.Column('admission_source', sa.String(), nullable=False),
    sa.Column('preferred_bed_category', sa.String(), nullable=False),
    sa.Column('expected_admission_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipd_admission_requests_patient_uhid'), 'ipd_admission_requests', ['patient_uhid'], unique=False)
    op.create_index(op.f('ix_ipd_admission_requests_request_id'), 'ipd_admission_requests', ['request_id'], unique=True)
    op.create_table('ipd_bed_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bed_uuid', sa.UUID(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('doctor', sa.String(), nullable=False),
    sa.Column('reservation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bed_uuid'], ['ipd_bed_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_bed_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bed_uuid', sa.UUID(), nullable=False),
    sa.Column('current_status', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=True),
    sa.Column('admission_number', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bed_uuid'], ['ipd_bed_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_admission_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('visit_id', sa.String(), nullable=True),
    sa.Column('bed_uuid', sa.UUID(), nullable=False),
    sa.Column('admitting_doctor', sa.String(), nullable=False),
    sa.Column('admission_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discharge_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bed_uuid'], ['ipd_bed_master.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['ipd_admission_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipd_admission_records_admission_number'), 'ipd_admission_records', ['admission_number'], unique=True)
    op.create_index(op.f('ix_ipd_admission_records_patient_uhid'), 'ipd_admission_records', ['patient_uhid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipd_admission_records_patient_uhid'), table_name='ipd_admission_records')
    op.drop_index(op.f('ix_ipd_admission_records_admission_number'), table_name='ipd_admission_records')
    op.drop_table('ipd_admission_records')
    op.drop_table('ipd_bed_status')
    op.drop_table('ipd_bed_reservations')
    op.drop_index(op.f('ix_ipd_admission_requests_request_id'), table_name='ipd_admission_requests')
    op.drop_index(op.f('ix_ipd_admission_requests_patient_uhid'), table_name='ipd_admission_requests')
    op.drop_table('ipd_admission_requests')
    op.drop_table('ipd_admission_audit_logs')
    op.drop_index(op.f('ix_ipd_bed_master_bed_id'), table_name='ipd_bed_master')
    op.drop_table('ipd_bed_master')
    # ### end Alembic commands ###
