"""Extended Lab QC Models

Revision ID: 7d4fa608f94b
Revises: d98e23b234b2
Create Date: 2026-03-24 06:06:01.003655
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4fa608f94b'
down_revision: Union[str, None] = 'd98e23b234b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lis_equipment_maintenance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=True),
    sa.Column('equipment_name', sa.String(), nullable=True),
    sa.Column('maintenance_schedule', sa.String(), nullable=True),
    sa.Column('last_calibration_date', sa.DateTime(), nullable=True),
    sa.Column('next_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('service_history', sa.Text(), nullable=True),
    sa.Column('is_overdue', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_equipment_maintenance_equipment_id'), 'lis_equipment_maintenance', ['equipment_id'], unique=False)
    op.create_table('lis_home_collection_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('patient_uhid', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('test_requested', sa.String(), nullable=True),
    sa.Column('preferred_collection_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('test_order_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_home_collection_requests_patient_name'), 'lis_home_collection_requests', ['patient_name'], unique=False)
    op.create_index(op.f('ix_lis_home_collection_requests_patient_uhid'), 'lis_home_collection_requests', ['patient_uhid'], unique=False)
    op.create_index(op.f('ix_lis_home_collection_requests_test_order_id'), 'lis_home_collection_requests', ['test_order_id'], unique=False)
    op.create_table('lis_outsource_lab_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lab_name', sa.String(), nullable=True),
    sa.Column('contact_details', sa.String(), nullable=True),
    sa.Column('test_capabilities', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_outsource_lab_master_lab_name'), 'lis_outsource_lab_master', ['lab_name'], unique=False)
    op.create_table('lis_quality_control',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=True),
    sa.Column('equipment_id', sa.String(), nullable=True),
    sa.Column('qc_date', sa.DateTime(), nullable=True),
    sa.Column('result_value', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('failure_alert_sent', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_quality_control_equipment_id'), 'lis_quality_control', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_lis_quality_control_test_name'), 'lis_quality_control', ['test_name'], unique=False)
    op.create_table('lis_external_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('outsource_lab_id', sa.String(), nullable=True),
    sa.Column('test_order_id', sa.String(), nullable=True),
    sa.Column('sample_id', sa.String(), nullable=True),
    sa.Column('patient_uhid', sa.String(), nullable=True),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['outsource_lab_id'], ['lis_outsource_lab_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_external_results_patient_uhid'), 'lis_external_results', ['patient_uhid'], unique=False)
    op.create_index(op.f('ix_lis_external_results_sample_id'), 'lis_external_results', ['sample_id'], unique=False)
    op.create_index(op.f('ix_lis_external_results_test_order_id'), 'lis_external_results', ['test_order_id'], unique=False)
    op.create_table('lis_phlebotomist_schedule',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('collection_date', sa.DateTime(), nullable=True),
    sa.Column('collection_time', sa.DateTime(), nullable=True),
    sa.Column('assigned_phlebotomist', sa.String(), nullable=True),
    sa.Column('collection_location', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['lis_home_collection_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_phlebotomist_schedule_assigned_phlebotomist'), 'lis_phlebotomist_schedule', ['assigned_phlebotomist'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lis_phlebotomist_schedule_assigned_phlebotomist'), table_name='lis_phlebotomist_schedule')
    op.drop_table('lis_phlebotomist_schedule')
    op.drop_index(op.f('ix_lis_external_results_test_order_id'), table_name='lis_external_results')
    op.drop_index(op.f('ix_lis_external_results_sample_id'), table_name='lis_external_results')
    op.drop_index(op.f('ix_lis_external_results_patient_uhid'), table_name='lis_external_results')
    op.drop_table('lis_external_results')
    op.drop_index(op.f('ix_lis_quality_control_test_name'), table_name='lis_quality_control')
    op.drop_index(op.f('ix_lis_quality_control_equipment_id'), table_name='lis_quality_control')
    op.drop_table('lis_quality_control')
    op.drop_index(op.f('ix_lis_outsource_lab_master_lab_name'), table_name='lis_outsource_lab_master')
    op.drop_table('lis_outsource_lab_master')
    op.drop_index(op.f('ix_lis_home_collection_requests_test_order_id'), table_name='lis_home_collection_requests')
    op.drop_index(op.f('ix_lis_home_collection_requests_patient_uhid'), table_name='lis_home_collection_requests')
    op.drop_index(op.f('ix_lis_home_collection_requests_patient_name'), table_name='lis_home_collection_requests')
    op.drop_table('lis_home_collection_requests')
    op.drop_index(op.f('ix_lis_equipment_maintenance_equipment_id'), table_name='lis_equipment_maintenance')
    op.drop_table('lis_equipment_maintenance')
    # ### end Alembic commands ###
