"""Add Narcotics Management Engine

Revision ID: 7ed32f368f72
Revises: 6ce3866c890f
Create Date: 2026-03-25 09:49:11.433967
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed32f368f72'
down_revision: Union[str, None] = '6ce3866c890f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_narcotics_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=True),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('stock_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_narcotics_inventory_batch_id'), 'pharmacy_narcotics_inventory', ['batch_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_narcotics_inventory_drug_id'), 'pharmacy_narcotics_inventory', ['drug_id'], unique=False)
    op.create_table('pharmacy_narcotics_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('uhid', sa.String(length=100), nullable=False),
    sa.Column('admission_number', sa.String(length=100), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('bed_number', sa.String(length=100), nullable=True),
    sa.Column('prescribing_doctor', sa.String(length=200), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=True),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('requested_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_narcotics', sa.Boolean(), nullable=True),
    sa.Column('validated_by', sa.UUID(), nullable=True),
    sa.Column('validation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_remarks', sa.Text(), nullable=True),
    sa.Column('nurse_name', sa.String(length=200), nullable=True),
    sa.Column('delivery_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handover_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_narcotics_orders_admission_number'), 'pharmacy_narcotics_orders', ['admission_number'], unique=False)
    op.create_index(op.f('ix_pharmacy_narcotics_orders_patient_id'), 'pharmacy_narcotics_orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_narcotics_orders_uhid'), 'pharmacy_narcotics_orders', ['uhid'], unique=False)
    op.create_table('pharmacy_narcotics_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['pharmacy_narcotics_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_narcotics_audit_logs_order_id'), 'pharmacy_narcotics_audit_logs', ['order_id'], unique=False)
    op.create_table('pharmacy_narcotics_dispense',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('dispensed_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dispensing_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispensed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['pharmacy_narcotics_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_narcotics_dispense_order_id'), 'pharmacy_narcotics_dispense', ['order_id'], unique=False)
    op.create_table('pharmacy_narcotics_ampoule_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('dispense_id', sa.UUID(), nullable=True),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('returned_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('returned_by_nurse', sa.String(length=200), nullable=False),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_pharmacist', sa.UUID(), nullable=True),
    sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dispense_id'], ['pharmacy_narcotics_dispense.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['pharmacy_narcotics_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_narcotics_ampoule_returns_order_id'), 'pharmacy_narcotics_ampoule_returns', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_narcotics_ampoule_returns_order_id'), table_name='pharmacy_narcotics_ampoule_returns')
    op.drop_table('pharmacy_narcotics_ampoule_returns')
    op.drop_index(op.f('ix_pharmacy_narcotics_dispense_order_id'), table_name='pharmacy_narcotics_dispense')
    op.drop_table('pharmacy_narcotics_dispense')
    op.drop_index(op.f('ix_pharmacy_narcotics_audit_logs_order_id'), table_name='pharmacy_narcotics_audit_logs')
    op.drop_table('pharmacy_narcotics_audit_logs')
    op.drop_index(op.f('ix_pharmacy_narcotics_orders_uhid'), table_name='pharmacy_narcotics_orders')
    op.drop_index(op.f('ix_pharmacy_narcotics_orders_patient_id'), table_name='pharmacy_narcotics_orders')
    op.drop_index(op.f('ix_pharmacy_narcotics_orders_admission_number'), table_name='pharmacy_narcotics_orders')
    op.drop_table('pharmacy_narcotics_orders')
    op.drop_index(op.f('ix_pharmacy_narcotics_inventory_drug_id'), table_name='pharmacy_narcotics_inventory')
    op.drop_index(op.f('ix_pharmacy_narcotics_inventory_batch_id'), table_name='pharmacy_narcotics_inventory')
    op.drop_table('pharmacy_narcotics_inventory')
    # ### end Alembic commands ###
