"""Pharmacy Phase 8

Revision ID: 8aa6a64f5101
Revises: 71db12fad498
Create Date: 2026-03-17 06:11:50.106249
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8aa6a64f5101'
down_revision: Union[str, None] = '71db12fad498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controlled_drug_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['medications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controlled_drug_logs_drug_id'), 'controlled_drug_logs', ['drug_id'], unique=False)
    op.create_table('drug_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('manufacture_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_batches_drug_id'), 'drug_batches', ['drug_id'], unique=False)
    op.create_index(op.f('ix_drug_batches_expiry_date'), 'drug_batches', ['expiry_date'], unique=False)
    op.create_table('drug_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_a_id', sa.UUID(), nullable=False),
    sa.Column('drug_b_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['drug_a_id'], ['medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drug_b_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_interactions_drug_a_id'), 'drug_interactions', ['drug_a_id'], unique=False)
    op.create_index(op.f('ix_drug_interactions_drug_b_id'), 'drug_interactions', ['drug_b_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reorder_threshold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_drug_id'), 'inventory_items', ['drug_id'], unique=True)
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('prescribing_doctor_id', sa.UUID(), nullable=False),
    sa.Column('prescription_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prescribing_doctor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_encounter_id'), 'prescriptions', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_order_id'), 'prescriptions', ['order_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_prescribing_doctor_id'), 'prescriptions', ['prescribing_doctor_id'], unique=False)
    op.create_table('dispensing_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('dispensed_by', sa.UUID(), nullable=False),
    sa.Column('dispensed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dispensed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispensing_records_dispensed_by'), 'dispensing_records', ['dispensed_by'], unique=False)
    op.create_index(op.f('ix_dispensing_records_prescription_id'), 'dispensing_records', ['prescription_id'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['medications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_items_drug_id'), 'prescription_items', ['drug_id'], unique=False)
    op.create_index(op.f('ix_prescription_items_prescription_id'), 'prescription_items', ['prescription_id'], unique=False)
    op.drop_index(op.f('ix_dispenses_order_id'), table_name='dispenses')
    op.drop_table('dispenses')
    op.drop_index(op.f('ix_pharmacy_stock_medication_id'), table_name='pharmacy_stock')
    op.drop_table('pharmacy_stock')
    op.add_column('medications', sa.Column('drug_code', sa.String(length=50), nullable=False))
    op.add_column('medications', sa.Column('drug_name', sa.String(length=200), nullable=False))
    op.add_column('medications', sa.Column('drug_class', sa.String(length=100), nullable=True))
    op.add_column('medications', sa.Column('manufacturer', sa.String(length=200), nullable=True))
    op.add_column('medications', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('medications', 'generic_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('medications', 'form',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('medications', 'strength',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_medications_code'), table_name='medications')
    op.create_index(op.f('ix_medications_drug_code'), 'medications', ['drug_code'], unique=True)
    op.drop_column('medications', 'name')
    op.drop_column('medications', 'unit_price')
    op.drop_column('medications', 'code')
    op.drop_column('medications', 'is_active')
    op.drop_column('medications', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medications', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('medications', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('medications', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('medications', sa.Column('unit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('medications', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_medications_drug_code'), table_name='medications')
    op.create_index(op.f('ix_medications_code'), 'medications', ['code'], unique=True)
    op.alter_column('medications', 'strength',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('medications', 'form',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('medications', 'generic_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('medications', 'created_at')
    op.drop_column('medications', 'manufacturer')
    op.drop_column('medications', 'drug_class')
    op.drop_column('medications', 'drug_name')
    op.drop_column('medications', 'drug_code')
    op.create_table('pharmacy_stock',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('medication_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reorder_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expiry_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('pharmacy_stock_medication_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pharmacy_stock_pkey'))
    )
    op.create_index(op.f('ix_pharmacy_stock_medication_id'), 'pharmacy_stock', ['medication_id'], unique=False)
    op.create_table('dispenses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('medication_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dispensed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('dispensed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dispensed_by'], ['users.id'], name=op.f('dispenses_dispensed_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('dispenses_medication_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('dispenses_order_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('dispenses_patient_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('dispenses_pkey'))
    )
    op.create_index(op.f('ix_dispenses_order_id'), 'dispenses', ['order_id'], unique=False)
    op.drop_index(op.f('ix_prescription_items_prescription_id'), table_name='prescription_items')
    op.drop_index(op.f('ix_prescription_items_drug_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_dispensing_records_prescription_id'), table_name='dispensing_records')
    op.drop_index(op.f('ix_dispensing_records_dispensed_by'), table_name='dispensing_records')
    op.drop_table('dispensing_records')
    op.drop_index(op.f('ix_prescriptions_prescribing_doctor_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_order_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_encounter_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_inventory_items_drug_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_drug_interactions_drug_b_id'), table_name='drug_interactions')
    op.drop_index(op.f('ix_drug_interactions_drug_a_id'), table_name='drug_interactions')
    op.drop_table('drug_interactions')
    op.drop_index(op.f('ix_drug_batches_expiry_date'), table_name='drug_batches')
    op.drop_index(op.f('ix_drug_batches_drug_id'), table_name='drug_batches')
    op.drop_table('drug_batches')
    op.drop_index(op.f('ix_controlled_drug_logs_drug_id'), table_name='controlled_drug_logs')
    op.drop_table('controlled_drug_logs')
    # ### end Alembic commands ###
