"""Fix prescription_id FK to worklist_prescriptions

Revision ID: 997a27c101c6
Revises: bb4f91942652
Create Date: 2026-03-25 08:34:47.680723
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997a27c101c6'
down_revision: Union[str, None] = 'bb4f91942652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pharmacy_dispensing_records_prescription_id_fkey'), 'pharmacy_dispensing_records', type_='foreignkey')
    op.create_foreign_key(None, 'pharmacy_dispensing_records', 'pharmacy_worklist_prescriptions', ['prescription_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pharmacy_dispensing_records', type_='foreignkey')
    op.create_foreign_key(op.f('pharmacy_dispensing_records_prescription_id_fkey'), 'pharmacy_dispensing_records', 'pharmacy_prescriptions', ['prescription_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
