"""Add Pharmacy Inventory Intelligence Models

Revision ID: 9a577cf236ee
Revises: 7ed32f368f72
Create Date: 2026-03-25 10:52:24.006274
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a577cf236ee'
down_revision: Union[str, None] = '7ed32f368f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_item_kits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kit_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('kit_components', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kit_name')
    )
    op.create_table('pharmacy_inventory_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('abc_category', sa.String(length=5), nullable=True),
    sa.Column('ved_category', sa.String(length=10), nullable=True),
    sa.Column('is_dead_stock', sa.Integer(), nullable=True),
    sa.Column('last_analyzed', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id')
    )
    op.create_table('pharmacy_inventory_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['medications.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_inventory_batches_batch_number'), 'pharmacy_inventory_batches', ['batch_number'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_batches_drug_id'), 'pharmacy_inventory_batches', ['drug_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_batches_expiry_date'), 'pharmacy_inventory_batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_batches_store_id'), 'pharmacy_inventory_batches', ['store_id'], unique=False)
    op.create_table('pharmacy_inventory_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=True),
    sa.Column('quantity_change', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pharmacy_inventory_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('alert_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['pharmacy_inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pharmacy_stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['pharmacy_inventory_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_stock_movements_transaction_type'), 'pharmacy_stock_movements', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_stock_movements_transaction_type'), table_name='pharmacy_stock_movements')
    op.drop_table('pharmacy_stock_movements')
    op.drop_table('pharmacy_inventory_alerts')
    op.drop_table('pharmacy_inventory_logs')
    op.drop_index(op.f('ix_pharmacy_inventory_batches_store_id'), table_name='pharmacy_inventory_batches')
    op.drop_index(op.f('ix_pharmacy_inventory_batches_expiry_date'), table_name='pharmacy_inventory_batches')
    op.drop_index(op.f('ix_pharmacy_inventory_batches_drug_id'), table_name='pharmacy_inventory_batches')
    op.drop_index(op.f('ix_pharmacy_inventory_batches_batch_number'), table_name='pharmacy_inventory_batches')
    op.drop_table('pharmacy_inventory_batches')
    op.drop_table('pharmacy_inventory_analysis')
    op.drop_table('pharmacy_item_kits')
    # ### end Alembic commands ###
