"""Smart Reporting Models

Revision ID: a2b10ab3f23e
Revises: 7e45ac8f94a1
Create Date: 2026-03-24 05:38:55.848787
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b10ab3f23e'
down_revision: Union[str, None] = '7e45ac8f94a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lis_report_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('test_code', sa.String(), nullable=True),
    sa.Column('condition_rule', sa.String(), nullable=True),
    sa.Column('auto_comment', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_report_comments_department'), 'lis_report_comments', ['department'], unique=False)
    op.create_index(op.f('ix_lis_report_comments_test_code'), 'lis_report_comments', ['test_code'], unique=False)
    op.create_table('lis_report_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('layout_config', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_report_templates_department'), 'lis_report_templates', ['department'], unique=True)
    op.create_table('lis_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('test_order_id', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=False),
    sa.Column('visit_id', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('test_details', sa.JSON(), nullable=False),
    sa.Column('result_values', sa.JSON(), nullable=False),
    sa.Column('reference_ranges', sa.JSON(), nullable=True),
    sa.Column('abnormal_flags', sa.JSON(), nullable=True),
    sa.Column('interpretative_comments', sa.String(), nullable=True),
    sa.Column('is_signed', sa.Boolean(), nullable=True),
    sa.Column('signed_by_id', sa.String(), nullable=True),
    sa.Column('signed_by_name', sa.String(), nullable=True),
    sa.Column('signed_by_designation', sa.String(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_reports_department'), 'lis_reports', ['department'], unique=False)
    op.create_index(op.f('ix_lis_reports_patient_uhid'), 'lis_reports', ['patient_uhid'], unique=False)
    op.create_index(op.f('ix_lis_reports_sample_id'), 'lis_reports', ['sample_id'], unique=False)
    op.create_index(op.f('ix_lis_reports_status'), 'lis_reports', ['status'], unique=False)
    op.create_index(op.f('ix_lis_reports_test_order_id'), 'lis_reports', ['test_order_id'], unique=False)
    op.create_table('lis_report_audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('actor_name', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['lis_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_report_audit_logs_report_id'), 'lis_report_audit_logs', ['report_id'], unique=False)
    op.create_table('lis_report_release',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('released_by_id', sa.String(), nullable=False),
    sa.Column('released_by_name', sa.String(), nullable=False),
    sa.Column('distribution_channels', sa.JSON(), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['lis_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_report_release_report_id'), 'lis_report_release', ['report_id'], unique=False)
    op.create_table('lis_report_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('changes_made', sa.JSON(), nullable=False),
    sa.Column('amended_by_id', sa.String(), nullable=False),
    sa.Column('amended_by_name', sa.String(), nullable=False),
    sa.Column('amended_at', sa.DateTime(), nullable=True),
    sa.Column('previous_snapshot', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['lis_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_report_versions_report_id'), 'lis_report_versions', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lis_report_versions_report_id'), table_name='lis_report_versions')
    op.drop_table('lis_report_versions')
    op.drop_index(op.f('ix_lis_report_release_report_id'), table_name='lis_report_release')
    op.drop_table('lis_report_release')
    op.drop_index(op.f('ix_lis_report_audit_logs_report_id'), table_name='lis_report_audit_logs')
    op.drop_table('lis_report_audit_logs')
    op.drop_index(op.f('ix_lis_reports_test_order_id'), table_name='lis_reports')
    op.drop_index(op.f('ix_lis_reports_status'), table_name='lis_reports')
    op.drop_index(op.f('ix_lis_reports_sample_id'), table_name='lis_reports')
    op.drop_index(op.f('ix_lis_reports_patient_uhid'), table_name='lis_reports')
    op.drop_index(op.f('ix_lis_reports_department'), table_name='lis_reports')
    op.drop_table('lis_reports')
    op.drop_index(op.f('ix_lis_report_templates_department'), table_name='lis_report_templates')
    op.drop_table('lis_report_templates')
    op.drop_index(op.f('ix_lis_report_comments_test_code'), table_name='lis_report_comments')
    op.drop_index(op.f('ix_lis_report_comments_department'), table_name='lis_report_comments')
    op.drop_table('lis_report_comments')
    # ### end Alembic commands ###
