"""Phase 3 encounters

Revision ID: a48b14859976
Revises: 2cae45fb6cf7
Create Date: 2026-03-16 12:44:35.419148
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a48b14859976'
down_revision: Union[str, None] = '2cae45fb6cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.String(length=100), nullable=False),
    sa.Column('flag_description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounter_diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_code', sa.String(length=50), nullable=False),
    sa.Column('diagnosis_description', sa.String(length=255), nullable=False),
    sa.Column('diagnosis_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounter_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('note_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounter_timeline',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('encounters', sa.Column('encounter_uuid', sa.String(length=50), nullable=True))
    op.add_column('encounters', sa.Column('department', sa.String(length=100), nullable=False))
    op.add_column('encounters', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('encounters', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('encounters', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('encounters', 'encounter_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('encounters', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('encounters', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('encounters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.create_index(op.f('ix_encounters_encounter_uuid'), 'encounters', ['encounter_uuid'], unique=True)
    op.drop_constraint(op.f('encounters_doctor_id_fkey'), 'encounters', type_='foreignkey')
    op.drop_constraint(op.f('encounters_patient_id_fkey'), 'encounters', type_='foreignkey')
    op.create_foreign_key(None, 'encounters', 'users', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'encounters', 'patients', ['patient_id'], ['id'])
    op.drop_column('encounters', 'admitted_at')
    op.drop_column('encounters', 'room')
    op.drop_column('encounters', 'notes')
    op.drop_column('encounters', 'discharged_at')
    op.drop_column('encounters', 'chief_complaint')
    op.drop_column('encounters', 'ward')
    op.drop_column('encounters', 'bed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('bed', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('encounters', sa.Column('ward', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('encounters', sa.Column('chief_complaint', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('encounters', sa.Column('discharged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('encounters', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('encounters', sa.Column('room', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('encounters', sa.Column('admitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'encounters', type_='foreignkey')
    op.drop_constraint(None, 'encounters', type_='foreignkey')
    op.create_foreign_key(op.f('encounters_patient_id_fkey'), 'encounters', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('encounters_doctor_id_fkey'), 'encounters', 'users', ['doctor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_encounters_encounter_uuid'), table_name='encounters')
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.alter_column('encounters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('encounters', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('encounters', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('encounters', 'encounter_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('encounters', 'updated_at')
    op.drop_column('encounters', 'end_time')
    op.drop_column('encounters', 'start_time')
    op.drop_column('encounters', 'department')
    op.drop_column('encounters', 'encounter_uuid')
    op.drop_table('encounter_timeline')
    op.drop_table('encounter_notes')
    op.drop_table('encounter_diagnoses')
    op.drop_table('clinical_flags')
    # ### end Alembic commands ###
