"""Add IPD Transfer phase 19 models

Revision ID: a603b23d9039
Revises: 512200f00198
Create Date: 2026-03-24 09:14:12.432139
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a603b23d9039'
down_revision: Union[str, None] = '512200f00198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipd_bed_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('previous_ward', sa.String(), nullable=True),
    sa.Column('previous_bed', sa.String(), nullable=True),
    sa.Column('new_ward', sa.String(), nullable=False),
    sa.Column('new_bed', sa.String(), nullable=False),
    sa.Column('movement_reason', sa.String(), nullable=False),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_transfer_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('current_ward', sa.String(), nullable=False),
    sa.Column('current_bed', sa.String(), nullable=False),
    sa.Column('requested_ward', sa.String(), nullable=False),
    sa.Column('requested_bed_category', sa.String(), nullable=True),
    sa.Column('requested_bed', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('transfer_type', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_transfer_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_request_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('performed_by', sa.String(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['transfer_request_id'], ['ipd_transfer_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_transfer_handovers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_request_id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('identification', sa.Text(), nullable=True),
    sa.Column('situation', sa.Text(), nullable=False),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('assessment', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('documented_by', sa.String(), nullable=False),
    sa.Column('documented_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transfer_request_id'], ['ipd_transfer_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_transfer_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_request_id', sa.UUID(), nullable=False),
    sa.Column('recipient_role', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transfer_request_id'], ['ipd_transfer_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_transfer_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_request_id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('from_ward', sa.String(), nullable=False),
    sa.Column('from_bed', sa.String(), nullable=False),
    sa.Column('to_ward', sa.String(), nullable=False),
    sa.Column('to_bed', sa.String(), nullable=False),
    sa.Column('transfer_type', sa.String(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=False),
    sa.Column('executed_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['transfer_request_id'], ['ipd_transfer_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipd_transfer_records')
    op.drop_table('ipd_transfer_notifications')
    op.drop_table('ipd_transfer_handovers')
    op.drop_table('ipd_transfer_audit_logs')
    op.drop_table('ipd_transfer_requests')
    op.drop_table('ipd_bed_movements')
    # ### end Alembic commands ###
