"""lis_processing_engine

Revision ID: a8ea5db785c5
Revises: be4128d79dcc
Create Date: 2026-03-23 13:39:22.339477
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8ea5db785c5'
down_revision: Union[str, None] = 'be4128d79dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lis_processing_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_processing_audit_action'), 'lis_processing_audit', ['action'], unique=False)
    op.create_table('lis_processing_worklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cr_receipt_id', sa.UUID(), nullable=True),
    sa.Column('sample_id', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('patient_uhid', sa.String(length=50), nullable=True),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('sample_type', sa.String(length=30), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('receipt_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_technician', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_processing_worklist_barcode'), 'lis_processing_worklist', ['barcode'], unique=False)
    op.create_index(op.f('ix_lis_processing_worklist_cr_receipt_id'), 'lis_processing_worklist', ['cr_receipt_id'], unique=False)
    op.create_index(op.f('ix_lis_processing_worklist_department'), 'lis_processing_worklist', ['department'], unique=False)
    op.create_index(op.f('ix_lis_processing_worklist_order_id'), 'lis_processing_worklist', ['order_id'], unique=False)
    op.create_index(op.f('ix_lis_processing_worklist_patient_id'), 'lis_processing_worklist', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lis_processing_worklist_priority'), 'lis_processing_worklist', ['priority'], unique=False)
    op.create_index(op.f('ix_lis_processing_worklist_sample_id'), 'lis_processing_worklist', ['sample_id'], unique=False)
    op.create_index(op.f('ix_lis_processing_worklist_status'), 'lis_processing_worklist', ['status'], unique=False)
    op.create_table('lis_qc_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('qc_lot_number', sa.String(length=50), nullable=False),
    sa.Column('qc_level', sa.String(length=20), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('expected_sd', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('analyzer_id', sa.String(length=100), nullable=True),
    sa.Column('performed_by', sa.String(length=255), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_qc_result_department'), 'lis_qc_result', ['department'], unique=False)
    op.create_table('lis_result_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worklist_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('result_type', sa.String(length=20), nullable=False),
    sa.Column('result_value', sa.Text(), nullable=True),
    sa.Column('result_numeric', sa.Float(), nullable=True),
    sa.Column('result_unit', sa.String(length=30), nullable=True),
    sa.Column('reference_low', sa.Float(), nullable=True),
    sa.Column('reference_high', sa.Float(), nullable=True),
    sa.Column('result_source', sa.String(length=30), nullable=False),
    sa.Column('analyzer_id', sa.String(length=100), nullable=True),
    sa.Column('entered_by', sa.String(length=255), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['worklist_id'], ['lis_processing_worklist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_result_entry_patient_id'), 'lis_result_entry', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lis_result_entry_sample_id'), 'lis_result_entry', ['sample_id'], unique=False)
    op.create_index(op.f('ix_lis_result_entry_worklist_id'), 'lis_result_entry', ['worklist_id'], unique=False)
    op.create_table('lis_delta_check',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('previous_value', sa.Float(), nullable=False),
    sa.Column('previous_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delta_absolute', sa.Float(), nullable=False),
    sa.Column('delta_percent', sa.Float(), nullable=False),
    sa.Column('threshold_percent', sa.Float(), nullable=False),
    sa.Column('is_significant', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['lis_result_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_delta_check_result_id'), 'lis_delta_check', ['result_id'], unique=False)
    op.create_table('lis_result_comment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('comment_type', sa.String(length=30), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.String(length=255), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['lis_result_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_result_comment_result_id'), 'lis_result_comment', ['result_id'], unique=False)
    op.create_table('lis_result_flag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.String(length=20), nullable=False),
    sa.Column('reference_low', sa.Float(), nullable=True),
    sa.Column('reference_high', sa.Float(), nullable=True),
    sa.Column('result_value', sa.Float(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['lis_result_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_result_flag_flag_type'), 'lis_result_flag', ['flag_type'], unique=False)
    op.create_index(op.f('ix_lis_result_flag_result_id'), 'lis_result_flag', ['result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lis_result_flag_result_id'), table_name='lis_result_flag')
    op.drop_index(op.f('ix_lis_result_flag_flag_type'), table_name='lis_result_flag')
    op.drop_table('lis_result_flag')
    op.drop_index(op.f('ix_lis_result_comment_result_id'), table_name='lis_result_comment')
    op.drop_table('lis_result_comment')
    op.drop_index(op.f('ix_lis_delta_check_result_id'), table_name='lis_delta_check')
    op.drop_table('lis_delta_check')
    op.drop_index(op.f('ix_lis_result_entry_worklist_id'), table_name='lis_result_entry')
    op.drop_index(op.f('ix_lis_result_entry_sample_id'), table_name='lis_result_entry')
    op.drop_index(op.f('ix_lis_result_entry_patient_id'), table_name='lis_result_entry')
    op.drop_table('lis_result_entry')
    op.drop_index(op.f('ix_lis_qc_result_department'), table_name='lis_qc_result')
    op.drop_table('lis_qc_result')
    op.drop_index(op.f('ix_lis_processing_worklist_status'), table_name='lis_processing_worklist')
    op.drop_index(op.f('ix_lis_processing_worklist_sample_id'), table_name='lis_processing_worklist')
    op.drop_index(op.f('ix_lis_processing_worklist_priority'), table_name='lis_processing_worklist')
    op.drop_index(op.f('ix_lis_processing_worklist_patient_id'), table_name='lis_processing_worklist')
    op.drop_index(op.f('ix_lis_processing_worklist_order_id'), table_name='lis_processing_worklist')
    op.drop_index(op.f('ix_lis_processing_worklist_department'), table_name='lis_processing_worklist')
    op.drop_index(op.f('ix_lis_processing_worklist_cr_receipt_id'), table_name='lis_processing_worklist')
    op.drop_index(op.f('ix_lis_processing_worklist_barcode'), table_name='lis_processing_worklist')
    op.drop_table('lis_processing_worklist')
    op.drop_index(op.f('ix_lis_processing_audit_action'), table_name='lis_processing_audit')
    op.drop_table('lis_processing_audit')
    # ### end Alembic commands ###
