"""Add IP Pharmacy issues engine

Revision ID: baf9f7765ade
Revises: 6f665620eda0
Create Date: 2026-03-25 08:56:24.564738
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baf9f7765ade'
down_revision: Union[str, None] = '6f665620eda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_ip_pending_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('uhid', sa.String(length=50), nullable=False),
    sa.Column('admission_number', sa.String(length=50), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('bed_number', sa.String(length=50), nullable=True),
    sa.Column('treating_doctor_name', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_ip_pending_issues_admission_number'), 'pharmacy_ip_pending_issues', ['admission_number'], unique=False)
    op.create_index(op.f('ix_pharmacy_ip_pending_issues_patient_id'), 'pharmacy_ip_pending_issues', ['patient_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_ip_pending_issues_uhid'), 'pharmacy_ip_pending_issues', ['uhid'], unique=False)
    op.create_table('pharmacy_ip_dispense_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=True),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=100), nullable=True),
    sa.Column('prescribed_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dispensed_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('instructions', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_non_formulary', sa.Boolean(), nullable=True),
    sa.Column('substituted_for', sa.String(length=255), nullable=True),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('store_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['pharmacy_ip_pending_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_ip_dispense_records_issue_id'), 'pharmacy_ip_dispense_records', ['issue_id'], unique=False)
    op.create_table('pharmacy_ip_order_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('pharmacist_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['pharmacy_ip_pending_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_ip_order_logs_issue_id'), 'pharmacy_ip_order_logs', ['issue_id'], unique=False)
    op.create_table('pharmacy_ip_billing_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('charge_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('billed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_synced', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['pharmacy_ip_pending_issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['pharmacy_ip_dispense_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_ip_billing_records_issue_id'), 'pharmacy_ip_billing_records', ['issue_id'], unique=False)
    op.create_table('pharmacy_ip_dispense_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispense_record_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('quantity_deducted', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dispense_record_id'], ['pharmacy_ip_dispense_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_ip_dispense_batches_dispense_record_id'), 'pharmacy_ip_dispense_batches', ['dispense_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_ip_dispense_batches_dispense_record_id'), table_name='pharmacy_ip_dispense_batches')
    op.drop_table('pharmacy_ip_dispense_batches')
    op.drop_index(op.f('ix_pharmacy_ip_billing_records_issue_id'), table_name='pharmacy_ip_billing_records')
    op.drop_table('pharmacy_ip_billing_records')
    op.drop_index(op.f('ix_pharmacy_ip_order_logs_issue_id'), table_name='pharmacy_ip_order_logs')
    op.drop_table('pharmacy_ip_order_logs')
    op.drop_index(op.f('ix_pharmacy_ip_dispense_records_issue_id'), table_name='pharmacy_ip_dispense_records')
    op.drop_table('pharmacy_ip_dispense_records')
    op.drop_index(op.f('ix_pharmacy_ip_pending_issues_uhid'), table_name='pharmacy_ip_pending_issues')
    op.drop_index(op.f('ix_pharmacy_ip_pending_issues_patient_id'), table_name='pharmacy_ip_pending_issues')
    op.drop_index(op.f('ix_pharmacy_ip_pending_issues_admission_number'), table_name='pharmacy_ip_pending_issues')
    op.drop_table('pharmacy_ip_pending_issues')
    # ### end Alembic commands ###
