"""Remove dispensed_by FK constraint

Revision ID: bb4f91942652
Revises: 24c0f8c59702
Create Date: 2026-03-25 08:32:18.194630
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4f91942652'
down_revision: Union[str, None] = '24c0f8c59702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pharmacy_dispensing_records_dispensed_by_fkey'), 'pharmacy_dispensing_records', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('pharmacy_dispensing_records_dispensed_by_fkey'), 'pharmacy_dispensing_records', 'users', ['dispensed_by'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
