"""lis_central_receiving_engine

Revision ID: be4128d79dcc
Revises: 28a0d958374a
Create Date: 2026-03-23 13:19:07.972741
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be4128d79dcc'
down_revision: Union[str, None] = '28a0d958374a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lis_cr_alert',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('sample_id', sa.String(length=50), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_cr_alert_alert_type'), 'lis_cr_alert', ['alert_type'], unique=False)
    op.create_index(op.f('ix_lis_cr_alert_status'), 'lis_cr_alert', ['status'], unique=False)
    op.create_table('lis_cr_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_cr_audit_action'), 'lis_cr_audit', ['action'], unique=False)
    op.create_table('lis_cr_receipt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('patient_uhid', sa.String(length=50), nullable=True),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('sample_type', sa.String(length=30), nullable=False),
    sa.Column('container_type', sa.String(length=30), nullable=True),
    sa.Column('collection_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collection_location', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('transport_batch_id', sa.String(length=50), nullable=True),
    sa.Column('received_by', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_location', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_cr_receipt_barcode'), 'lis_cr_receipt', ['barcode'], unique=False)
    op.create_index(op.f('ix_lis_cr_receipt_order_id'), 'lis_cr_receipt', ['order_id'], unique=False)
    op.create_index(op.f('ix_lis_cr_receipt_patient_id'), 'lis_cr_receipt', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lis_cr_receipt_priority'), 'lis_cr_receipt', ['priority'], unique=False)
    op.create_index(op.f('ix_lis_cr_receipt_sample_id'), 'lis_cr_receipt', ['sample_id'], unique=False)
    op.create_index(op.f('ix_lis_cr_receipt_status'), 'lis_cr_receipt', ['status'], unique=False)
    op.create_table('lis_cr_chain_of_custody',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('responsible_staff', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['lis_cr_receipt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_cr_chain_of_custody_receipt_id'), 'lis_cr_chain_of_custody', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_lis_cr_chain_of_custody_sample_id'), 'lis_cr_chain_of_custody', ['sample_id'], unique=False)
    op.create_table('lis_cr_rejection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=50), nullable=False),
    sa.Column('rejection_details', sa.Text(), nullable=True),
    sa.Column('rejected_by', sa.String(length=255), nullable=False),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recollection_requested', sa.Boolean(), nullable=False),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('notification_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['lis_cr_receipt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_cr_rejection_receipt_id'), 'lis_cr_rejection', ['receipt_id'], unique=False)
    op.create_table('lis_cr_routing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('target_department', sa.String(length=50), nullable=False),
    sa.Column('routed_by', sa.String(length=255), nullable=False),
    sa.Column('routed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at_dept', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_by_dept', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['lis_cr_receipt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_cr_routing_receipt_id'), 'lis_cr_routing', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_lis_cr_routing_target_department'), 'lis_cr_routing', ['target_department'], unique=False)
    op.create_table('lis_cr_storage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('storage_location', sa.String(length=100), nullable=False),
    sa.Column('storage_temperature', sa.String(length=20), nullable=False),
    sa.Column('max_duration_hours', sa.Integer(), nullable=False),
    sa.Column('stored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stored_by', sa.String(length=255), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('alert_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['lis_cr_receipt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_cr_storage_receipt_id'), 'lis_cr_storage', ['receipt_id'], unique=False)
    op.create_table('lis_cr_verification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('sample_type_correct', sa.Boolean(), nullable=False),
    sa.Column('container_correct', sa.Boolean(), nullable=False),
    sa.Column('volume_adequate', sa.Boolean(), nullable=False),
    sa.Column('labeling_correct', sa.Boolean(), nullable=False),
    sa.Column('transport_ok', sa.Boolean(), nullable=False),
    sa.Column('hemolyzed', sa.Boolean(), nullable=False),
    sa.Column('clotted', sa.Boolean(), nullable=False),
    sa.Column('overall_result', sa.String(length=20), nullable=False),
    sa.Column('verified_by', sa.String(length=255), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['lis_cr_receipt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_cr_verification_receipt_id'), 'lis_cr_verification', ['receipt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lis_cr_verification_receipt_id'), table_name='lis_cr_verification')
    op.drop_table('lis_cr_verification')
    op.drop_index(op.f('ix_lis_cr_storage_receipt_id'), table_name='lis_cr_storage')
    op.drop_table('lis_cr_storage')
    op.drop_index(op.f('ix_lis_cr_routing_target_department'), table_name='lis_cr_routing')
    op.drop_index(op.f('ix_lis_cr_routing_receipt_id'), table_name='lis_cr_routing')
    op.drop_table('lis_cr_routing')
    op.drop_index(op.f('ix_lis_cr_rejection_receipt_id'), table_name='lis_cr_rejection')
    op.drop_table('lis_cr_rejection')
    op.drop_index(op.f('ix_lis_cr_chain_of_custody_sample_id'), table_name='lis_cr_chain_of_custody')
    op.drop_index(op.f('ix_lis_cr_chain_of_custody_receipt_id'), table_name='lis_cr_chain_of_custody')
    op.drop_table('lis_cr_chain_of_custody')
    op.drop_index(op.f('ix_lis_cr_receipt_status'), table_name='lis_cr_receipt')
    op.drop_index(op.f('ix_lis_cr_receipt_sample_id'), table_name='lis_cr_receipt')
    op.drop_index(op.f('ix_lis_cr_receipt_priority'), table_name='lis_cr_receipt')
    op.drop_index(op.f('ix_lis_cr_receipt_patient_id'), table_name='lis_cr_receipt')
    op.drop_index(op.f('ix_lis_cr_receipt_order_id'), table_name='lis_cr_receipt')
    op.drop_index(op.f('ix_lis_cr_receipt_barcode'), table_name='lis_cr_receipt')
    op.drop_table('lis_cr_receipt')
    op.drop_index(op.f('ix_lis_cr_audit_action'), table_name='lis_cr_audit')
    op.drop_table('lis_cr_audit')
    op.drop_index(op.f('ix_lis_cr_alert_status'), table_name='lis_cr_alert')
    op.drop_index(op.f('ix_lis_cr_alert_alert_type'), table_name='lis_cr_alert')
    op.drop_table('lis_cr_alert')
    # ### end Alembic commands ###
