"""add_phase_17_ipd_doctor_models

Revision ID: c1eaee47860e
Revises: 372dbf911a1a
Create Date: 2026-03-24 08:30:28.208925
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1eaee47860e'
down_revision: Union[str, None] = '372dbf911a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipd_clinical_procedures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('procedure_name', sa.String(), nullable=False),
    sa.Column('procedure_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('performing_doctor', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_consultation_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('consulting_department', sa.String(), nullable=False),
    sa.Column('reason_for_referral', sa.Text(), nullable=False),
    sa.Column('urgency_level', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('diagnosis_type', sa.String(), nullable=False),
    sa.Column('icd10_code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('diagnosed_by_name', sa.String(), nullable=False),
    sa.Column('diagnosed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_doctor_coversheets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('primary_diagnosis', sa.String(), nullable=True),
    sa.Column('clinical_summary', sa.Text(), nullable=True),
    sa.Column('verified_by_doctor', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_number')
    )
    op.create_table('ipd_doctor_worklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('doctor_uuid', sa.UUID(), nullable=False),
    sa.Column('doctor_name', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_progress_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('doctor_name', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_treatment_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('therapy_type', sa.String(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('created_by_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipd_treatment_plans')
    op.drop_table('ipd_progress_notes')
    op.drop_table('ipd_doctor_worklist')
    op.drop_table('ipd_doctor_coversheets')
    op.drop_table('ipd_diagnoses')
    op.drop_table('ipd_consultation_requests')
    op.drop_table('ipd_clinical_procedures')
    # ### end Alembic commands ###
