"""lis_test_order_engine

Revision ID: c9dc24290877
Revises: 7858e870dd40
Create Date: 2026-03-23 12:24:44.452078
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9dc24290877'
down_revision: Union[str, None] = '7858e870dd40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lis_test_panels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('panel_code', sa.String(length=50), nullable=False),
    sa.Column('panel_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_test_panels_panel_code'), 'lis_test_panels', ['panel_code'], unique=True)
    op.create_table('lis_test_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('ordering_doctor', sa.String(length=255), nullable=True),
    sa.Column('department_source', sa.String(length=50), nullable=False),
    sa.Column('order_source', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('clinical_indication', sa.Text(), nullable=True),
    sa.Column('provisional_diagnosis', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('medication_history', sa.Text(), nullable=True),
    sa.Column('insurance_validated', sa.Boolean(), nullable=False),
    sa.Column('insurance_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_test_orders_encounter_id'), 'lis_test_orders', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_lis_test_orders_order_number'), 'lis_test_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_lis_test_orders_patient_id'), 'lis_test_orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lis_test_orders_priority'), 'lis_test_orders', ['priority'], unique=False)
    op.create_index(op.f('ix_lis_test_orders_status'), 'lis_test_orders', ['status'], unique=False)
    op.create_index(op.f('ix_lis_test_orders_visit_id'), 'lis_test_orders', ['visit_id'], unique=False)
    op.create_table('lis_test_panel_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('panel_id', sa.UUID(), nullable=False),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('sample_type', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['lis_test_panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_test_panel_items_panel_id'), 'lis_test_panel_items', ['panel_id'], unique=False)
    op.create_table('lis_order_audit_trail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['lis_test_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_order_audit_trail_order_id'), 'lis_order_audit_trail', ['order_id'], unique=False)
    op.create_table('lis_order_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('ocr_extracted_text', sa.Text(), nullable=True),
    sa.Column('detected_tests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['lis_test_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_order_documents_order_id'), 'lis_order_documents', ['order_id'], unique=False)
    op.create_table('lis_test_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('test_code', sa.String(length=50), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('sample_type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('panel_id', sa.UUID(), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('collection_location', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['lis_test_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_test_order_items_barcode'), 'lis_test_order_items', ['barcode'], unique=True)
    op.create_index(op.f('ix_lis_test_order_items_order_id'), 'lis_test_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_lis_test_order_items_test_code'), 'lis_test_order_items', ['test_code'], unique=False)
    op.create_table('lis_barcode_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_type', sa.String(length=30), nullable=False),
    sa.Column('collection_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_collected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['lis_test_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['lis_test_order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_barcode_registry_barcode'), 'lis_barcode_registry', ['barcode'], unique=True)
    op.create_index(op.f('ix_lis_barcode_registry_order_id'), 'lis_barcode_registry', ['order_id'], unique=False)
    op.create_index(op.f('ix_lis_barcode_registry_order_item_id'), 'lis_barcode_registry', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_lis_barcode_registry_patient_id'), 'lis_barcode_registry', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lis_barcode_registry_patient_id'), table_name='lis_barcode_registry')
    op.drop_index(op.f('ix_lis_barcode_registry_order_item_id'), table_name='lis_barcode_registry')
    op.drop_index(op.f('ix_lis_barcode_registry_order_id'), table_name='lis_barcode_registry')
    op.drop_index(op.f('ix_lis_barcode_registry_barcode'), table_name='lis_barcode_registry')
    op.drop_table('lis_barcode_registry')
    op.drop_index(op.f('ix_lis_test_order_items_test_code'), table_name='lis_test_order_items')
    op.drop_index(op.f('ix_lis_test_order_items_order_id'), table_name='lis_test_order_items')
    op.drop_index(op.f('ix_lis_test_order_items_barcode'), table_name='lis_test_order_items')
    op.drop_table('lis_test_order_items')
    op.drop_index(op.f('ix_lis_order_documents_order_id'), table_name='lis_order_documents')
    op.drop_table('lis_order_documents')
    op.drop_index(op.f('ix_lis_order_audit_trail_order_id'), table_name='lis_order_audit_trail')
    op.drop_table('lis_order_audit_trail')
    op.drop_index(op.f('ix_lis_test_panel_items_panel_id'), table_name='lis_test_panel_items')
    op.drop_table('lis_test_panel_items')
    op.drop_index(op.f('ix_lis_test_orders_visit_id'), table_name='lis_test_orders')
    op.drop_index(op.f('ix_lis_test_orders_status'), table_name='lis_test_orders')
    op.drop_index(op.f('ix_lis_test_orders_priority'), table_name='lis_test_orders')
    op.drop_index(op.f('ix_lis_test_orders_patient_id'), table_name='lis_test_orders')
    op.drop_index(op.f('ix_lis_test_orders_order_number'), table_name='lis_test_orders')
    op.drop_index(op.f('ix_lis_test_orders_encounter_id'), table_name='lis_test_orders')
    op.drop_table('lis_test_orders')
    op.drop_index(op.f('ix_lis_test_panels_panel_code'), table_name='lis_test_panels')
    op.drop_table('lis_test_panels')
    # ### end Alembic commands ###
