"""Add phase 5 tasks schema

Revision ID: d26c12df225a
Revises: 0467c51d8416
Create Date: 2026-03-16 15:21:17.206957
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd26c12df225a'
down_revision: Union[str, None] = '0467c51d8416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('default_instructions', sa.Text(), nullable=True),
    sa.Column('default_priority', sa.String(length=10), nullable=False),
    sa.Column('schedule_interval', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_assignments_assigned_to_user_id'), 'task_assignments', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_task_assignments_task_id'), 'task_assignments', ['task_id'], unique=False)
    op.create_table('task_execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('executed_by', sa.UUID(), nullable=False),
    sa.Column('execution_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_execution_logs_task_id'), 'task_execution_logs', ['task_id'], unique=False)
    op.create_table('task_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status_history_task_id'), 'task_status_history', ['task_id'], unique=False)
    op.add_column('tasks', sa.Column('task_uuid', sa.String(length=50), nullable=False))
    op.add_column('tasks', sa.Column('patient_id', sa.UUID(), nullable=False))
    op.add_column('tasks', sa.Column('encounter_id', sa.UUID(), nullable=False))
    op.add_column('tasks', sa.Column('priority', sa.String(length=10), nullable=False))
    op.add_column('tasks', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('schedule_interval', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('next_execution_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_tasks_assigned_to_user'), 'tasks', ['assigned_to_user'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_encounter_id'), 'tasks', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_tasks_patient_id'), 'tasks', ['patient_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_unique_constraint(None, 'tasks', ['task_uuid'])
    op.create_foreign_key(None, 'tasks', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'tasks', 'encounters', ['encounter_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_patient_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_encounter_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_user'), table_name='tasks')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'metadata')
    op.drop_column('tasks', 'next_execution_time')
    op.drop_column('tasks', 'schedule_interval')
    op.drop_column('tasks', 'started_at')
    op.drop_column('tasks', 'instructions')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'encounter_id')
    op.drop_column('tasks', 'patient_id')
    op.drop_column('tasks', 'task_uuid')
    op.drop_index(op.f('ix_task_status_history_task_id'), table_name='task_status_history')
    op.drop_table('task_status_history')
    op.drop_index(op.f('ix_task_execution_logs_task_id'), table_name='task_execution_logs')
    op.drop_table('task_execution_logs')
    op.drop_index(op.f('ix_task_assignments_task_id'), table_name='task_assignments')
    op.drop_index(op.f('ix_task_assignments_assigned_to_user_id'), table_name='task_assignments')
    op.drop_table('task_assignments')
    op.drop_table('task_templates')
    # ### end Alembic commands ###
