"""Advanced Lab Diagnostics Models

Revision ID: d98e23b234b2
Revises: a2b10ab3f23e
Create Date: 2026-03-24 05:48:42.310226
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd98e23b234b2'
down_revision: Union[str, None] = 'a2b10ab3f23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lis_blood_bank_inventory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('blood_group', sa.String(), nullable=False),
    sa.Column('donor_id', sa.String(), nullable=False),
    sa.Column('donor_email', sa.String(), nullable=True),
    sa.Column('collection_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_blood_bank_inventory_blood_group'), 'lis_blood_bank_inventory', ['blood_group'], unique=False)
    op.create_index(op.f('ix_lis_blood_bank_inventory_status'), 'lis_blood_bank_inventory', ['status'], unique=False)
    op.create_index(op.f('ix_lis_blood_bank_inventory_unit_id'), 'lis_blood_bank_inventory', ['unit_id'], unique=True)
    op.create_table('lis_cssd_tests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('test_sample_id', sa.String(), nullable=False),
    sa.Column('control_sample_id', sa.String(), nullable=False),
    sa.Column('sterilization_validated', sa.Boolean(), nullable=True),
    sa.Column('growth_in_test_sample', sa.Boolean(), nullable=True),
    sa.Column('growth_in_control_sample', sa.Boolean(), nullable=True),
    sa.Column('report_sent_to', sa.String(), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lis_histopathology_specimens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('test_order_id', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('macroscopic_notes', sa.String(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('requires_counseling', sa.Boolean(), nullable=True),
    sa.Column('counseling_status', sa.String(), nullable=True),
    sa.Column('is_oncology', sa.Boolean(), nullable=True),
    sa.Column('cross_referral_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_histopathology_specimens_current_stage'), 'lis_histopathology_specimens', ['current_stage'], unique=False)
    op.create_index(op.f('ix_lis_histopathology_specimens_patient_uhid'), 'lis_histopathology_specimens', ['patient_uhid'], unique=False)
    op.create_index(op.f('ix_lis_histopathology_specimens_sample_id'), 'lis_histopathology_specimens', ['sample_id'], unique=False)
    op.create_index(op.f('ix_lis_histopathology_specimens_test_order_id'), 'lis_histopathology_specimens', ['test_order_id'], unique=False)
    op.create_table('lis_microbiology_cultures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('test_order_id', sa.String(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('source_department', sa.String(), nullable=True),
    sa.Column('incubation_type', sa.String(), nullable=True),
    sa.Column('incubation_time_hrs', sa.Integer(), nullable=True),
    sa.Column('growth_findings', sa.String(), nullable=True),
    sa.Column('organism_identified', sa.String(), nullable=True),
    sa.Column('is_infection_control_screen', sa.Boolean(), nullable=True),
    sa.Column('infection_control_report_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_microbiology_cultures_patient_uhid'), 'lis_microbiology_cultures', ['patient_uhid'], unique=False)
    op.create_index(op.f('ix_lis_microbiology_cultures_sample_id'), 'lis_microbiology_cultures', ['sample_id'], unique=False)
    op.create_index(op.f('ix_lis_microbiology_cultures_test_order_id'), 'lis_microbiology_cultures', ['test_order_id'], unique=False)
    op.create_table('lis_antibiotic_sensitivity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('culture_id', sa.String(), nullable=True),
    sa.Column('antibiotic_name', sa.String(), nullable=False),
    sa.Column('mic_value', sa.Float(), nullable=True),
    sa.Column('susceptibility', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['culture_id'], ['lis_microbiology_cultures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_antibiotic_sensitivity_culture_id'), 'lis_antibiotic_sensitivity', ['culture_id'], unique=False)
    op.create_table('lis_histopathology_blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('specimen_id', sa.String(), nullable=True),
    sa.Column('block_label', sa.String(), nullable=False),
    sa.Column('embedding_status', sa.String(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['specimen_id'], ['lis_histopathology_specimens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_histopathology_blocks_specimen_id'), 'lis_histopathology_blocks', ['specimen_id'], unique=False)
    op.create_table('lis_histopathology_slides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('block_id', sa.String(), nullable=True),
    sa.Column('slide_label', sa.String(), nullable=False),
    sa.Column('staining_type', sa.String(), nullable=True),
    sa.Column('microscopic_diagnosis', sa.String(), nullable=True),
    sa.Column('microscopic_images', sa.JSON(), nullable=True),
    sa.Column('prepared_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['lis_histopathology_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lis_histopathology_slides_block_id'), 'lis_histopathology_slides', ['block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lis_histopathology_slides_block_id'), table_name='lis_histopathology_slides')
    op.drop_table('lis_histopathology_slides')
    op.drop_index(op.f('ix_lis_histopathology_blocks_specimen_id'), table_name='lis_histopathology_blocks')
    op.drop_table('lis_histopathology_blocks')
    op.drop_index(op.f('ix_lis_antibiotic_sensitivity_culture_id'), table_name='lis_antibiotic_sensitivity')
    op.drop_table('lis_antibiotic_sensitivity')
    op.drop_index(op.f('ix_lis_microbiology_cultures_test_order_id'), table_name='lis_microbiology_cultures')
    op.drop_index(op.f('ix_lis_microbiology_cultures_sample_id'), table_name='lis_microbiology_cultures')
    op.drop_index(op.f('ix_lis_microbiology_cultures_patient_uhid'), table_name='lis_microbiology_cultures')
    op.drop_table('lis_microbiology_cultures')
    op.drop_index(op.f('ix_lis_histopathology_specimens_test_order_id'), table_name='lis_histopathology_specimens')
    op.drop_index(op.f('ix_lis_histopathology_specimens_sample_id'), table_name='lis_histopathology_specimens')
    op.drop_index(op.f('ix_lis_histopathology_specimens_patient_uhid'), table_name='lis_histopathology_specimens')
    op.drop_index(op.f('ix_lis_histopathology_specimens_current_stage'), table_name='lis_histopathology_specimens')
    op.drop_table('lis_histopathology_specimens')
    op.drop_table('lis_cssd_tests')
    op.drop_index(op.f('ix_lis_blood_bank_inventory_unit_id'), table_name='lis_blood_bank_inventory')
    op.drop_index(op.f('ix_lis_blood_bank_inventory_status'), table_name='lis_blood_bank_inventory')
    op.drop_index(op.f('ix_lis_blood_bank_inventory_blood_group'), table_name='lis_blood_bank_inventory')
    op.drop_table('lis_blood_bank_inventory')
    # ### end Alembic commands ###
