"""phase14_operating_theatre

Revision ID: db572ea2eb88
Revises: f6df7223933a
Create Date: 2026-03-18 08:12:04.360774
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db572ea2eb88'
down_revision: Union[str, None] = 'f6df7223933a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operating_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_code', sa.String(length=50), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('equipment_profile', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operating_rooms_room_code'), 'operating_rooms', ['room_code'], unique=True)
    op.create_table('surgical_procedures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('procedure_code', sa.String(length=50), nullable=False),
    sa.Column('procedure_name', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('expected_duration', sa.Integer(), nullable=False),
    sa.Column('billing_code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surgical_procedures_procedure_code'), 'surgical_procedures', ['procedure_code'], unique=True)
    op.create_table('surgery_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('procedure_id', sa.UUID(), nullable=False),
    sa.Column('operating_room_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operating_room_id'], ['operating_rooms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['procedure_id'], ['surgical_procedures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scheduled_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surgery_schedule_encounter_id'), 'surgery_schedule', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_surgery_schedule_operating_room_id'), 'surgery_schedule', ['operating_room_id'], unique=False)
    op.create_index(op.f('ix_surgery_schedule_patient_id'), 'surgery_schedule', ['patient_id'], unique=False)
    op.create_index(op.f('ix_surgery_schedule_procedure_id'), 'surgery_schedule', ['procedure_id'], unique=False)
    op.create_table('anesthesia_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('anesthesia_type', sa.String(length=50), nullable=False),
    sa.Column('anesthesia_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anesthesia_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anesthesiologist_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['anesthesiologist_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['surgery_schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id')
    )
    op.create_table('postoperative_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['surgery_schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postoperative_events_schedule_id'), 'postoperative_events', ['schedule_id'], unique=False)
    op.create_table('surgery_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['surgery_schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surgery_events_schedule_id'), 'surgery_events', ['schedule_id'], unique=False)
    op.create_table('surgery_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['surgery_schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surgery_notes_schedule_id'), 'surgery_notes', ['schedule_id'], unique=False)
    op.create_table('surgical_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('lead_surgeon_id', sa.UUID(), nullable=True),
    sa.Column('assistant_surgeon_id', sa.UUID(), nullable=True),
    sa.Column('anesthesiologist_id', sa.UUID(), nullable=True),
    sa.Column('scrub_nurse_id', sa.UUID(), nullable=True),
    sa.Column('circulating_nurse_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anesthesiologist_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assistant_surgeon_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['circulating_nurse_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_surgeon_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['surgery_schedule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scrub_nurse_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surgical_teams')
    op.drop_index(op.f('ix_surgery_notes_schedule_id'), table_name='surgery_notes')
    op.drop_table('surgery_notes')
    op.drop_index(op.f('ix_surgery_events_schedule_id'), table_name='surgery_events')
    op.drop_table('surgery_events')
    op.drop_index(op.f('ix_postoperative_events_schedule_id'), table_name='postoperative_events')
    op.drop_table('postoperative_events')
    op.drop_table('anesthesia_records')
    op.drop_index(op.f('ix_surgery_schedule_procedure_id'), table_name='surgery_schedule')
    op.drop_index(op.f('ix_surgery_schedule_patient_id'), table_name='surgery_schedule')
    op.drop_index(op.f('ix_surgery_schedule_operating_room_id'), table_name='surgery_schedule')
    op.drop_index(op.f('ix_surgery_schedule_encounter_id'), table_name='surgery_schedule')
    op.drop_table('surgery_schedule')
    op.drop_index(op.f('ix_surgical_procedures_procedure_code'), table_name='surgical_procedures')
    op.drop_table('surgical_procedures')
    op.drop_index(op.f('ix_operating_rooms_room_code'), table_name='operating_rooms')
    op.drop_table('operating_rooms')
    # ### end Alembic commands ###
