"""Phase 25: RPIW Clinical Action Engine

Revision ID: dfbcfec086a1
Revises: 6dd8020356c9
Create Date: 2026-03-24 11:48:14.948988
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfbcfec086a1'
down_revision: Union[str, None] = '6dd8020356c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpiw_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=True),
    sa.Column('visit_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('created_by_role', sa.String(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('validation_remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_actions_admission_number'), 'rpiw_actions', ['admission_number'], unique=False)
    op.create_index(op.f('ix_rpiw_actions_patient_uhid'), 'rpiw_actions', ['patient_uhid'], unique=False)
    op.create_index(op.f('ix_rpiw_actions_visit_id'), 'rpiw_actions', ['visit_id'], unique=False)
    op.create_table('rpiw_action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_code', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['rpiw_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_action_logs_action_id'), 'rpiw_action_logs', ['action_id'], unique=False)
    op.create_table('rpiw_clinical_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_signed', sa.Boolean(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['rpiw_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_clinical_notes_action_id'), 'rpiw_clinical_notes', ['action_id'], unique=False)
    op.create_table('rpiw_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('order_category', sa.String(), nullable=False),
    sa.Column('item_code', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('routed_to_module', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['rpiw_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_orders_action_id'), 'rpiw_orders', ['action_id'], unique=False)
    op.create_table('rpiw_prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('drug_name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('routed_to_pharmacy', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['rpiw_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_prescriptions_action_id'), 'rpiw_prescriptions', ['action_id'], unique=False)
    op.create_table('rpiw_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('assigned_role', sa.String(), nullable=False),
    sa.Column('assigned_user_id', sa.String(), nullable=True),
    sa.Column('task_description', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['rpiw_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpiw_tasks_action_id'), 'rpiw_tasks', ['action_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rpiw_tasks_action_id'), table_name='rpiw_tasks')
    op.drop_table('rpiw_tasks')
    op.drop_index(op.f('ix_rpiw_prescriptions_action_id'), table_name='rpiw_prescriptions')
    op.drop_table('rpiw_prescriptions')
    op.drop_index(op.f('ix_rpiw_orders_action_id'), table_name='rpiw_orders')
    op.drop_table('rpiw_orders')
    op.drop_index(op.f('ix_rpiw_clinical_notes_action_id'), table_name='rpiw_clinical_notes')
    op.drop_table('rpiw_clinical_notes')
    op.drop_index(op.f('ix_rpiw_action_logs_action_id'), table_name='rpiw_action_logs')
    op.drop_table('rpiw_action_logs')
    op.drop_index(op.f('ix_rpiw_actions_visit_id'), table_name='rpiw_actions')
    op.drop_index(op.f('ix_rpiw_actions_patient_uhid'), table_name='rpiw_actions')
    op.drop_index(op.f('ix_rpiw_actions_admission_number'), table_name='rpiw_actions')
    op.drop_table('rpiw_actions')
    # ### end Alembic commands ###
