"""Pharmacy Core Infrastructure Enhancement

Revision ID: f3b77f861a2d
Revises: 5a4671e66a16
Create Date: 2026-03-24 12:20:57.660146
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3b77f861a2d'
down_revision: Union[str, None] = '5a4671e66a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_dosage_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=False),
    sa.Column('patient_category', sa.String(length=50), nullable=False),
    sa.Column('dosage_per_kg', sa.Numeric(), nullable=True),
    sa.Column('fixed_dosage', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_dosage_rules_generic_name'), 'pharmacy_dosage_rules', ['generic_name'], unique=False)
    op.create_table('pharmacy_drug_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_a_generic', sa.String(length=200), nullable=False),
    sa.Column('drug_b_generic', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('interaction_effect', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_drug_interactions_drug_a_generic'), 'pharmacy_drug_interactions', ['drug_a_generic'], unique=False)
    op.create_index(op.f('ix_pharmacy_drug_interactions_drug_b_generic'), 'pharmacy_drug_interactions', ['drug_b_generic'], unique=False)
    op.create_table('pharmacy_drug_master_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_drug_master_audits_drug_id'), 'pharmacy_drug_master_audits', ['drug_id'], unique=False)
    op.create_table('pharmacy_drug_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_name', sa.String(length=50), nullable=False),
    sa.Column('requires_prescription', sa.Boolean(), nullable=True),
    sa.Column('strict_narcotic', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_name')
    )
    op.create_table('pharmacy_role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('can_dispense', sa.Boolean(), nullable=True),
    sa.Column('can_manage_inventory', sa.Boolean(), nullable=True),
    sa.Column('can_manage_master', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('pharmacy_generic_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('brand_substitute_rank', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_generic_mapping_generic_name'), 'pharmacy_generic_mapping', ['generic_name'], unique=False)
    op.add_column('medications', sa.Column('pack_size', sa.String(length=50), nullable=True))
    op.add_column('medications', sa.Column('schedule_category', sa.String(length=50), nullable=True))
    op.add_column('medications', sa.Column('global_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'global_code')
    op.drop_column('medications', 'schedule_category')
    op.drop_column('medications', 'pack_size')
    op.drop_index(op.f('ix_pharmacy_generic_mapping_generic_name'), table_name='pharmacy_generic_mapping')
    op.drop_table('pharmacy_generic_mapping')
    op.drop_table('pharmacy_role_permissions')
    op.drop_table('pharmacy_drug_schedules')
    op.drop_index(op.f('ix_pharmacy_drug_master_audits_drug_id'), table_name='pharmacy_drug_master_audits')
    op.drop_table('pharmacy_drug_master_audits')
    op.drop_index(op.f('ix_pharmacy_drug_interactions_drug_b_generic'), table_name='pharmacy_drug_interactions')
    op.drop_index(op.f('ix_pharmacy_drug_interactions_drug_a_generic'), table_name='pharmacy_drug_interactions')
    op.drop_table('pharmacy_drug_interactions')
    op.drop_index(op.f('ix_pharmacy_dosage_rules_generic_name'), table_name='pharmacy_dosage_rules')
    op.drop_table('pharmacy_dosage_rules')
    # ### end Alembic commands ###
