"""add_linen_and_laundry_management

Revision ID: fa130d3daacb
Revises: avatar_001
Create Date: 2026-04-01 12:30:51.296419
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa130d3daacb'
down_revision: Union[str, None] = 'avatar_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linen_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_lifespan_washes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linen_categories_name'), 'linen_categories', ['name'], unique=True)
    op.create_index(op.f('ix_linen_categories_org_id'), 'linen_categories', ['org_id'], unique=False)

    op.create_table('laundry_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('washer_machine_id', sa.String(length=50), nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laundry_batches_batch_number'), 'laundry_batches', ['batch_number'], unique=True)
    op.create_index(op.f('ix_laundry_batches_org_id'), 'laundry_batches', ['org_id'], unique=False)

    op.create_table('linen_inventory_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.String(length=50), nullable=False),
    sa.Column('clean_quantity', sa.Integer(), nullable=False),
    sa.Column('dirty_quantity', sa.Integer(), nullable=False),
    sa.Column('in_wash_quantity', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['linen_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linen_inventory_ledger_department_id'), 'linen_inventory_ledger', ['department_id'], unique=False)
    op.create_index(op.f('ix_linen_inventory_ledger_org_id'), 'linen_inventory_ledger', ['org_id'], unique=False)

    op.create_table('linen_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('issue_to_ward', 'collect_from_ward', 'send_to_laundry', 'receive_from_laundry', 'condemn', 'new_stock', name='transactiontype'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('source_department', sa.String(length=50), nullable=True),
    sa.Column('destination_department', sa.String(length=50), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['laundry_batches.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['linen_categories.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linen_transactions_org_id'), 'linen_transactions', ['org_id'], unique=False)
    op.create_index(op.f('ix_linen_transactions_transaction_date'), 'linen_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_linen_transactions_transaction_type'), 'linen_transactions', ['transaction_type'], unique=False)


def downgrade() -> None:
    pass
