"""opd_visit_intelligence_engine

Revision ID: fad1c641d064
Revises: e60a33cf38d3
Create Date: 2026-03-23 10:23:38.325446
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad1c641d064'
down_revision: Union[str, None] = 'e60a33cf38d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multi_visit_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit_analytics_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analytics_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('total_visits', sa.Integer(), nullable=True),
    sa.Column('routine_visits', sa.Integer(), nullable=True),
    sa.Column('priority_visits', sa.Integer(), nullable=True),
    sa.Column('emergency_visits', sa.Integer(), nullable=True),
    sa.Column('completed_visits', sa.Integer(), nullable=True),
    sa.Column('cancelled_visits', sa.Integer(), nullable=True),
    sa.Column('no_show_visits', sa.Integer(), nullable=True),
    sa.Column('avg_wait_time_min', sa.Float(), nullable=True),
    sa.Column('avg_consult_time_min', sa.Float(), nullable=True),
    sa.Column('top_specialties', sa.JSON(), nullable=True),
    sa.Column('top_complaints', sa.JSON(), nullable=True),
    sa.Column('doctor_load_distribution', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visit_analytics_date', 'visit_analytics_snapshots', ['analytics_date'], unique=False)
    op.create_table('visit_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.String(length=32), nullable=False),
    sa.Column('encounter_id', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('patient_uhid', sa.String(length=50), nullable=True),
    sa.Column('visit_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visit_type', sa.String(length=30), nullable=True),
    sa.Column('visit_source', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('clinic_location', sa.String(length=200), nullable=True),
    sa.Column('referral_type', sa.String(length=50), nullable=True),
    sa.Column('referral_source', sa.String(length=200), nullable=True),
    sa.Column('payment_entitlement', sa.String(length=50), nullable=True),
    sa.Column('priority_tag', sa.String(length=20), nullable=True),
    sa.Column('is_follow_up', sa.Boolean(), nullable=True),
    sa.Column('parent_visit_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('billing_id', sa.UUID(), nullable=True),
    sa.Column('queue_token', sa.String(length=20), nullable=True),
    sa.Column('estimated_wait_min', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visit_date', 'visit_master', ['visit_date_time'], unique=False)
    op.create_index('ix_visit_doctor', 'visit_master', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_visit_master_encounter_id'), 'visit_master', ['encounter_id'], unique=True)
    op.create_index(op.f('ix_visit_master_visit_id'), 'visit_master', ['visit_id'], unique=True)
    op.create_index('ix_visit_patient', 'visit_master', ['patient_id'], unique=False)
    op.create_index('ix_visit_priority', 'visit_master', ['priority_tag'], unique=False)
    op.create_index('ix_visit_status', 'visit_master', ['status'], unique=False)
    op.create_table('visit_questionnaire_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questionnaire_specialty', 'visit_questionnaire_templates', ['specialty'], unique=False)
    op.create_table('visit_classification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('triggered_rules', sa.JSON(), nullable=True),
    sa.Column('complaint_severity', sa.Float(), nullable=True),
    sa.Column('vitals_abnormal', sa.Boolean(), nullable=True),
    sa.Column('has_chronic_disease', sa.Boolean(), nullable=True),
    sa.Column('age_risk', sa.Boolean(), nullable=True),
    sa.Column('vitals_snapshot', sa.JSON(), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=True),
    sa.Column('override_by', sa.UUID(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visit_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_index('ix_classification_visit', 'visit_classification', ['visit_id'], unique=False)
    op.create_table('visit_complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('raw_complaint_text', sa.Text(), nullable=True),
    sa.Column('input_mode', sa.String(length=30), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('structured_symptoms', sa.JSON(), nullable=True),
    sa.Column('medical_keywords', sa.JSON(), nullable=True),
    sa.Column('icpc_codes', sa.JSON(), nullable=True),
    sa.Column('icd_suggestions', sa.JSON(), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visit_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_complaint_visit', 'visit_complaints', ['visit_id'], unique=False)
    op.create_table('visit_context_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('previous_diagnoses', sa.JSON(), nullable=True),
    sa.Column('previous_prescriptions', sa.JSON(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('chronic_conditions', sa.JSON(), nullable=True),
    sa.Column('last_visit_notes', sa.Text(), nullable=True),
    sa.Column('last_visit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recent_lab_reports', sa.JSON(), nullable=True),
    sa.Column('recent_radiology_reports', sa.JSON(), nullable=True),
    sa.Column('active_medications', sa.JSON(), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('aggregated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visit_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_index('ix_context_visit', 'visit_context_snapshot', ['visit_id'], unique=False)
    op.create_table('visit_doctor_recommendation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('recommended_specialty', sa.String(length=100), nullable=True),
    sa.Column('recommended_doctors', sa.JSON(), nullable=True),
    sa.Column('based_on_symptoms', sa.JSON(), nullable=True),
    sa.Column('based_on_icpc', sa.JSON(), nullable=True),
    sa.Column('based_on_history', sa.Boolean(), nullable=True),
    sa.Column('previous_doctor_id', sa.UUID(), nullable=True),
    sa.Column('selection_mode', sa.String(length=20), nullable=True),
    sa.Column('selected_doctor_id', sa.UUID(), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visit_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendation_visit', 'visit_doctor_recommendation', ['visit_id'], unique=False)
    op.create_table('visit_questionnaire_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=True),
    sa.Column('completion_source', sa.String(length=30), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['visit_questionnaire_templates.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qresponse_visit', 'visit_questionnaire_responses', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qresponse_visit', table_name='visit_questionnaire_responses')
    op.drop_table('visit_questionnaire_responses')
    op.drop_index('ix_recommendation_visit', table_name='visit_doctor_recommendation')
    op.drop_table('visit_doctor_recommendation')
    op.drop_index('ix_context_visit', table_name='visit_context_snapshot')
    op.drop_table('visit_context_snapshot')
    op.drop_index('ix_complaint_visit', table_name='visit_complaints')
    op.drop_table('visit_complaints')
    op.drop_index('ix_classification_visit', table_name='visit_classification')
    op.drop_table('visit_classification')
    op.drop_index('ix_questionnaire_specialty', table_name='visit_questionnaire_templates')
    op.drop_table('visit_questionnaire_templates')
    op.drop_index('ix_visit_status', table_name='visit_master')
    op.drop_index('ix_visit_priority', table_name='visit_master')
    op.drop_index('ix_visit_patient', table_name='visit_master')
    op.drop_index(op.f('ix_visit_master_visit_id'), table_name='visit_master')
    op.drop_index(op.f('ix_visit_master_encounter_id'), table_name='visit_master')
    op.drop_index('ix_visit_doctor', table_name='visit_master')
    op.drop_index('ix_visit_date', table_name='visit_master')
    op.drop_table('visit_master')
    op.drop_index('ix_visit_analytics_date', table_name='visit_analytics_snapshots')
    op.drop_table('visit_analytics_snapshots')
    op.drop_table('multi_visit_rules')
    # ### end Alembic commands ###
