"""Add IPD Smart Admission and Cost Estimation Engine models

Revision ID: fbfbf19c4e1e
Revises: 1b7db9a40792
Create Date: 2026-03-24 07:10:04.312361
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbfbf19c4e1e'
down_revision: Union[str, None] = '1b7db9a40792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipd_cost_estimations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('patient_uhid', sa.String(), nullable=False),
    sa.Column('selected_bed_category', sa.String(), nullable=False),
    sa.Column('planned_procedures', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('planned_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_cost_lower', sa.Float(), nullable=True),
    sa.Column('estimated_cost_upper', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['ipd_admission_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipd_cost_estimations_request_id'), 'ipd_cost_estimations', ['request_id'], unique=False)
    op.create_table('ipd_admission_checklists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('registration_completed', sa.Boolean(), nullable=True),
    sa.Column('identity_proof_verified', sa.Boolean(), nullable=True),
    sa.Column('insurance_captured', sa.Boolean(), nullable=True),
    sa.Column('preauth_initiated', sa.Boolean(), nullable=True),
    sa.Column('consent_taken', sa.Boolean(), nullable=True),
    sa.Column('kin_details_recorded', sa.Boolean(), nullable=True),
    sa.Column('deposit_collected', sa.Boolean(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipd_admission_checklists_admission_number'), 'ipd_admission_checklists', ['admission_number'], unique=False)
    op.create_table('ipd_admission_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_deposit_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('receipt_number', sa.String(), nullable=False),
    sa.Column('deposit_amount', sa.Float(), nullable=False),
    sa.Column('payment_mode', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_table('ipd_insurance_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('policy_number', sa.String(), nullable=False),
    sa.Column('total_sum_assured', sa.Float(), nullable=True),
    sa.Column('bed_charge_limit_percent', sa.Float(), nullable=True),
    sa.Column('eligible_bed_category', sa.String(), nullable=True),
    sa.Column('preauth_number', sa.String(), nullable=True),
    sa.Column('preauth_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_patient_transport',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('transport_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipd_projected_bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(), nullable=False),
    sa.Column('bed_charges', sa.Float(), nullable=True),
    sa.Column('investigations', sa.Float(), nullable=True),
    sa.Column('procedures', sa.Float(), nullable=True),
    sa.Column('medications', sa.Float(), nullable=True),
    sa.Column('consumables', sa.Float(), nullable=True),
    sa.Column('other_charges', sa.Float(), nullable=True),
    sa.Column('total_projected_amount', sa.Float(), nullable=True),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_number'], ['ipd_admission_records.admission_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipd_projected_bills')
    op.drop_table('ipd_patient_transport')
    op.drop_table('ipd_insurance_details')
    op.drop_table('ipd_deposit_records')
    op.drop_table('ipd_admission_documents')
    op.drop_index(op.f('ix_ipd_admission_checklists_admission_number'), table_name='ipd_admission_checklists')
    op.drop_table('ipd_admission_checklists')
    op.drop_index(op.f('ix_ipd_cost_estimations_request_id'), table_name='ipd_cost_estimations')
    op.drop_table('ipd_cost_estimations')
    # ### end Alembic commands ###
