import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, Integer, ForeignKey, DateTime, Boolean, JSON, Text, Float
from sqlalchemy.dialects.postgresql import UUID, JSONB
from app.database import Base


class RpiwAiContext(Base):
    """Snapshot of clinical context used by AI for decision support generation."""
    __tablename__ = "rpiw_ai_context"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    patient_uhid = Column(String, nullable=False, index=True)
    user_id = Column(String, nullable=False)
    role_code = Column(String, nullable=False)
    
    # Context snapshots
    clinical_summary = Column(Text, nullable=True)
    recent_vitals = Column(JSONB, nullable=True)
    active_medications = Column(JSONB, nullable=True)
    latest_labs = Column(JSONB, nullable=True)
    
    analyzed_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


class RpiwAiSuggestion(Base):
    """Suggestions generated by the AI (e.g., draft note, order recommendation)."""
    __tablename__ = "rpiw_ai_suggestions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    context_id = Column(UUID(as_uuid=True), ForeignKey("rpiw_ai_context.id", ondelete="CASCADE"), nullable=False)
    patient_uhid = Column(String, nullable=False, index=True)
    user_id = Column(String, nullable=False)
    target_role = Column(String, nullable=False)  # doctor, nurse, phlebotomist
    
    suggestion_type = Column(String, nullable=False) # DraftNote, OrderRecommendation, CareProtocol, DifferentialDiagnosis
    title = Column(String, nullable=False)
    content = Column(Text, nullable=False)
    structured_data = Column(JSONB, nullable=True) # Payload that can be passed to Clinical Action Engine
    
    status = Column(String, default="Pending") # Pending, Accepted, Rejected, Ignored
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    resolved_at = Column(DateTime(timezone=True), nullable=True)


class RpiwAiAlert(Base):
    """Clinical risk alerts detected by the AI Assistant."""
    __tablename__ = "rpiw_ai_alerts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    patient_uhid = Column(String, nullable=False, index=True)
    target_role = Column(String, nullable=False)
    
    risk_category = Column(String, nullable=False) # AbnormalVitals, DrugInteraction, CriticalLab
    severity = Column(String, nullable=False) # High, Medium, Low
    message = Column(Text, nullable=False)
    is_acknowledged = Column(Boolean, default=False)
    
    detected_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)
    acknowledged_by = Column(String, nullable=True)


class RpiwAiFeedback(Base):
    """User feedback loop for continuous AI learning."""
    __tablename__ = "rpiw_ai_feedback"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    suggestion_id = Column(UUID(as_uuid=True), ForeignKey("rpiw_ai_suggestions.id"), nullable=False, unique=True)
    user_id = Column(String, nullable=False)
    feedback_rating = Column(String, nullable=False) # Helpful, Irrelevant, Incorrect
    comments = Column(Text, nullable=True)
    submitted_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


class RpiwAiActivityLog(Base):
    """Immutable audit trail for all AI interactions."""
    __tablename__ = "rpiw_ai_activity_logs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    patient_uhid = Column(String, nullable=False, index=True)
    user_id = Column(String, nullable=False)
    role_code = Column(String, nullable=False)
    
    event_type = Column(String, nullable=False) # ContextAnalyzed, SuggestionGenerated, SuggestionAccepted, SuggestionRejected
    reference_id = Column(String, nullable=True) # ID of suggestion or context
    metadata_payload = Column(JSONB, nullable=True)
    
    timestamp = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
